# Automatically generated by Pynguin.
import caso_covertura_004 as module0


def test_case_0():
    try:
        var0 = False
        var1 = '4wUa0X*]boBRBME}rO]'
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_1():
    try:
        var0 = False
        var1 = -624
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_2():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = 1810.0
        var4 = 2092.6206
        var5 = module0.search(var3, var4)
    except BaseException:
        pass


def test_case_3():
    try:
        var0 = 'JQr\nxHO2vn&$=2lZ//\n'
        var1 = True
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_4():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = 'WShqAuX@\x0bu6qNOz$4'
        var4 = 2873
        var5 = module0.search(var3, var4)
    except BaseException:
        pass


def test_case_5():
    try:
        var0 = False
        var1 = 'zCAKlYO\x0cX:_'
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_6():
    try:
        var0 = True
        var1 = None
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_7():
    try:
        var0 = 'F'
        var1 = -745.42942
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_8():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = -1422.4
        var4 = module0.search(var0, var3)
    except BaseException:
        pass


def test_case_9():
    try:
        var0 = None
        var1 = True
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_10():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = None
        var4 = 'T\x0cTlq[MgY,t\rtWpZJ'
        var5 = module0.search(var3, var4)
    except BaseException:
        pass


def test_case_11():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = -1046.4138
        var4 = True
        var5 = module0.search(var3, var4)
    except BaseException:
        pass


def test_case_12():
    try:
        var0 = 1919
        var1 = 2160
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_13():
    try:
        var0 = -2864.1281
        var1 = False
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_14():
    try:
        var0 = 'Vtb9d\\d'
        var1 = -3231
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_15():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = False
        var4 = 'b1FpE?v3=8o(x!C\nTC]B'
        var5 = module0.search(var3, var4)
    except BaseException:
        pass


def test_case_16():
    try:
        var0 = -4968
        var1 = "nBAi'IaG009}pgTn(M"
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_17():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = -3062.04
        var4 = 815.8156
        var5 = module0.search(var3, var4)
    except BaseException:
        pass


def test_case_18():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = -705
        var4 = module0.search(var3, var1)
    except BaseException:
        pass


def test_case_19():
    try:
        var0 = True
        var1 = -164
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_20():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = -840
        var4 = module0.search(var1, var3)
    except BaseException:
        pass


def test_case_21():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = '5*:Z{/wY]iy`V_#,.'
        var4 = "|wCIymb'HiL^\\qQ4|L~"
        var5 = module0.search(var3, var4)
        assert var5 == 16
        var6 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var7 = module0.search(var6, var6)
        assert var7 == 19
        var8 = 489
        var9 = module0.search(var8, var3)
    except BaseException:
        pass


def test_case_22():
    try:
        var0 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var1 = module0.search(var0, var0)
        assert var1 == 19
        var2 = '5*:Z{/wY]iy`V_#,.'
        var3 = "|wCIymb'HiL^\\qQ4|L~"
        var4 = module0.search(var2, var3)
        assert var4 == 16
        var5 = 'P1c'
        var6 = '=a1V0,-=IpP\tYI6yF{'
        var7 = module0.search(var5, var6)
        assert var7 == 17
        var8 = False
        var9 = -497
        var10 = module0.search(var8, var9)
    except BaseException:
        pass


def test_case_23():
    try:
        var0 = ''
        var1 = -221.5
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_24():
    try:
        var0 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var1 = module0.search(var0, var0)
        assert var1 == 19
        var2 = 'P1c'
        var3 = '=a1V0,-=IpP\tYI6yF{'
        var4 = module0.search(var2, var3)
        assert var4 == 17
        var5 = '5*:Z{/wY]iy`V_#,.'
        var6 = "|wCIymb'HiL^\\qQ4|L~"
        var7 = module0.search(var5, var6)
        assert var7 == 16
        var8 = '.!%Bqs;WHY*{F'
        var9 = 1342.419879
        var10 = module0.search(var8, var9)
    except BaseException:
        pass


def test_case_25():
    try:
        var0 = False
        var1 = '"\x0b l/1nvO+|'
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_26():
    try:
        var0 = -3340.21059
        var1 = "Bv'6\r2@"
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_27():
    try:
        var0 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var1 = module0.search(var0, var0)
        assert var1 == 19
        var2 = 'P1c'
        var3 = '=a1V0,-=IpP\tYI6yF{'
        var4 = module0.search(var2, var3)
        assert var4 == 17
        var5 = True
        var6 = -864.18
        var7 = module0.search(var5, var6)
    except BaseException:
        pass


def test_case_28():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var4 = module0.search(var3, var3)
        assert var4 == 19
        var5 = '5*:Z{/wY]iy`V_#,.'
        var6 = "|wCIymb'HiL^\\qQ4|L~"
        var7 = module0.search(var5, var6)
        assert var7 == 16
        var8 = None
        var9 = module0.search(var8, var8)
    except BaseException:
        pass


def test_case_29():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = '5*:Z{/wY]iy`V_#,.'
        var4 = "|wCIymb'HiL^\\qQ4|L~"
        var5 = module0.search(var3, var4)
        assert var5 == 16
        var6 = '|wdcKu\x0bL%xB ~I'
        var7 = 'z}DPJwn'
        var8 = module0.search(var6, var7)
        assert var8 == 7
        var9 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var10 = module0.search(var9, var9)
        assert var10 == 19
        var11 = '5*:Z{/wY]iy`V_#,.'
        var12 = "|wCIymb'HiL^\\qQ4|L~"
        var13 = module0.search(var11, var12)
        assert var13 == 16
        var14 = 'NS(zW\\~'
        var15 = False
        var16 = module0.search(var14, var15)
    except BaseException:
        pass


def test_case_30():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = '5*:Z{/wY]iy`V_#,.'
        var4 = "|wCIymb'HiL^\\qQ4|L~"
        var5 = module0.search(var3, var4)
        assert var5 == 16
        var6 = '|wdcKu\x0bL%xB ~I'
        var7 = 'z}DPJwn'
        var8 = module0.search(var6, var7)
        assert var8 == 7
        var9 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var10 = module0.search(var9, var9)
        assert var10 == 19
        var11 = 'P1c'
        var12 = '=a1V0,-=IpP\tYI6yF{'
        var13 = module0.search(var11, var12)
        assert var13 == 17
        var14 = '5*:Z{/wY]iy`V_#,.'
        var15 = "|wCIymb'HiL^\\qQ4|L~"
        var16 = module0.search(var14, var15)
        assert var16 == 16
        var17 = 2011
        var18 = module0.search(var17, var11)
    except BaseException:
        pass


def test_case_31():
    try:
        var0 = '5*:Z{/wY]iy`V_#,.'
        var1 = "|wCIymb'HiL^\\qQ4|L~"
        var2 = module0.search(var0, var1)
        assert var2 == 16
        var3 = None
        var4 = module0.search(var3, var3)
    except BaseException:
        pass


def test_case_32():
    try:
        var0 = '5*:Z{/wY]iy`V_#,.'
        var1 = "|wCIymb'HiL^\\qQ4|L~"
        var2 = module0.search(var0, var1)
        assert var2 == 16
        var3 = 'P1c'
        var4 = '=a1V0,-=IpP\tYI6yF{'
        var5 = module0.search(var3, var4)
        assert var5 == 17
        var6 = 4102.43
        var7 = 980.01
        var8 = module0.search(var6, var7)
    except BaseException:
        pass


def test_case_33():
    try:
        var0 = '5*:Z{/wY]iy`V_#,.'
        var1 = "|wCIymb'HiL^\\qQ4|L~"
        var2 = module0.search(var0, var1)
        assert var2 == 16
        var3 = -1315.0
        var4 = module0.search(var3, var3)
    except BaseException:
        pass


def test_case_34():
    try:
        var0 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var1 = module0.search(var0, var0)
        assert var1 == 19
        var2 = 'Y\r/'
        var3 = module0.search(var2, var0)
        assert var3 == 19
        var4 = 'P1c'
        var5 = '=a1V0,-=IpP\tYI6yF{'
        var6 = module0.search(var4, var5)
        assert var6 == 17
        var7 = '5*:Z{/wY]iy`V_#,.'
        var8 = "|wCIymb'HiL^\\qQ4|L~"
        var9 = module0.search(var7, var8)
        assert var9 == 16
        var10 = '|wdcKu\x0bL%xB ~I'
        var11 = 'z}DPJwn'
        var12 = module0.search(var10, var11)
        assert var12 == 7
        var13 = '5*:Z{/wY]iy`V_#,.'
        var14 = "|wCIymb'HiL^\\qQ4|L~"
        var15 = module0.search(var13, var14)
        assert var15 == 16
        var16 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var17 = module0.search(var16, var16)
        assert var17 == 19
        var18 = 'P1c'
        var19 = '=a1V0,-=IpP\tYI6yF{'
        var20 = module0.search(var18, var19)
        assert var20 == 17
        var21 = '<Vz('
        var22 = 715.0089
        var23 = module0.search(var21, var22)
    except BaseException:
        pass


def test_case_35():
    try:
        var0 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var1 = module0.search(var0, var0)
        assert var1 == 19
        var2 = '5*:Z{/wY]iy`V_#,.'
        var3 = "|wCIymb'HiL^\\qQ4|L~"
        var4 = module0.search(var2, var3)
        assert var4 == 16
        var5 = 'P1c'
        var6 = '=a1V0,-=IpP\tYI6yF{'
        var7 = module0.search(var5, var6)
        assert var7 == 17
        var8 = 'UL='
        var9 = '~/n\t\\*k!L'
        var10 = module0.search(var8, var9)
        assert var10 == 9
        var11 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var12 = module0.search(var11, var11)
        assert var12 == 19
        var13 = 'Y\r/'
        var14 = module0.search(var13, var11)
        assert var14 == 19
        var15 = 'P1c'
        var16 = '=a1V0,-=IpP\tYI6yF{'
        var17 = module0.search(var15, var16)
        assert var17 == 17
        var18 = -3761
        var19 = 1612.849907
        var20 = module0.search(var18, var19)
    except BaseException:
        pass


def test_case_36():
    try:
        var0 = 543
        var1 = True
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_37():
    try:
        var0 = '5*:Z{/wY]iy`V_#,.'
        var1 = "|wCIymb'HiL^\\qQ4|L~"
        var2 = module0.search(var0, var1)
        assert var2 == 16
        var3 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var4 = module0.search(var3, var3)
        assert var4 == 19
        var5 = 'Y\r/'
        var6 = module0.search(var5, var3)
        assert var6 == 19
        var7 = 'P1c'
        var8 = '=a1V0,-=IpP\tYI6yF{'
        var9 = module0.search(var7, var8)
        assert var9 == 17
        var10 = '5*:Z{/wY]iy`V_#,.'
        var11 = "|wCIymb'HiL^\\qQ4|L~"
        var12 = module0.search(var10, var11)
        assert var12 == 16
        var13 = '|wdcKu\x0bL%xB ~I'
        var14 = 'z}DPJwn'
        var15 = module0.search(var13, var14)
        assert var15 == 7
        var16 = 'P1c'
        var17 = '=a1V0,-=IpP\tYI6yF{'
        var18 = module0.search(var16, var17)
        assert var18 == 17
        var19 = 'P1c'
        var20 = '=a1V0,-=IpP\tYI6yF{'
        var21 = module0.search(var19, var20)
        assert var21 == 17
        var22 = 'UL='
        var23 = '~/n\t\\*k!L'
        var24 = module0.search(var22, var23)
        assert var24 == 9
        var25 = '5i<\\t+)Uf?-"\\<2sX'
        var26 = True
        var27 = module0.search(var25, var26)
    except BaseException:
        pass


def test_case_38():
    try:
        var0 = -3130
        var1 = '@tHVaO0'
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_39():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = 'UL='
        var4 = '~/n\t\\*k!L'
        var5 = module0.search(var3, var4)
        assert var5 == 9
        var6 = 'P1c'
        var7 = '=a1V0,-=IpP\tYI6yF{'
        var8 = module0.search(var6, var7)
        assert var8 == 17
        var9 = None
        var10 = module0.search(var9, var0)
    except BaseException:
        pass


def test_case_40():
    try:
        var0 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var1 = module0.search(var0, var0)
        assert var1 == 19
        var2 = 'Y\r/'
        var3 = module0.search(var2, var0)
        assert var3 == 19
        var4 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var5 = module0.search(var4, var4)
        assert var5 == 19
        var6 = 434
        var7 = module0.search(var0, var6)
    except BaseException:
        pass


def test_case_41():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = '5*:Z{/wY]iy`V_#,.'
        var4 = "|wCIymb'HiL^\\qQ4|L~"
        var5 = module0.search(var3, var4)
        assert var5 == 16
        var6 = '|wdcKu\x0bL%xB ~I'
        var7 = 'z}DPJwn'
        var8 = module0.search(var6, var7)
        assert var8 == 7
        var9 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var10 = module0.search(var9, var9)
        assert var10 == 19
        var11 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var12 = module0.search(var11, var11)
        assert var12 == 19
        var13 = 'Y\r/'
        var14 = module0.search(var13, var11)
        assert var14 == 19
        var15 = True
        var16 = '~hl}'
        var17 = module0.search(var15, var16)
    except BaseException:
        pass


def test_case_42():
    try:
        var0 = 'O9{I=s6j\\\x0bT`RK\nzW;'
        var1 = -537
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_43():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = '5*:Z{/wY]iy`V_#,.'
        var4 = "|wCIymb'HiL^\\qQ4|L~"
        var5 = module0.search(var3, var4)
        assert var5 == 16
        var6 = '|wdcKu\x0bL%xB ~I'
        var7 = 'z}DPJwn'
        var8 = module0.search(var6, var7)
        assert var8 == 7
        var9 = 'P1c'
        var10 = '=a1V0,-=IpP\tYI6yF{'
        var11 = module0.search(var9, var10)
        assert var11 == 17
        var12 = -3146
        var13 = 2246
        var14 = module0.search(var12, var13)
    except BaseException:
        pass


def test_case_44():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = 'UL='
        var4 = '~/n\t\\*k!L'
        var5 = module0.search(var3, var4)
        assert var5 == 9
        var6 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var7 = module0.search(var6, var6)
        assert var7 == 19
        var8 = 'Y\r/'
        var9 = module0.search(var8, var6)
        assert var9 == 19
        var10 = 'P1c'
        var11 = '=a1V0,-=IpP\tYI6yF{'
        var12 = module0.search(var10, var11)
        assert var12 == 17
        var13 = '5*:Z{/wY]iy`V_#,.'
        var14 = "|wCIymb'HiL^\\qQ4|L~"
        var15 = module0.search(var13, var14)
        assert var15 == 16
        var16 = 'P1c'
        var17 = '=a1V0,-=IpP\tYI6yF{'
        var18 = module0.search(var16, var17)
        assert var18 == 17
        var19 = '5*:Z{/wY]iy`V_#,.'
        var20 = "|wCIymb'HiL^\\qQ4|L~"
        var21 = module0.search(var19, var20)
        assert var21 == 16
        var22 = '|wdcKu\x0bL%xB ~I'
        var23 = 'z}DPJwn'
        var24 = module0.search(var22, var23)
        assert var24 == 7
        var25 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var26 = module0.search(var25, var25)
        assert var26 == 19
        var27 = None
        var28 = module0.search(var20, var27)
    except BaseException:
        pass


def test_case_45():
    try:
        var0 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var1 = module0.search(var0, var0)
        assert var1 == 19
        var2 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var3 = module0.search(var2, var2)
        assert var3 == 19
        var4 = 'Y\r/'
        var5 = module0.search(var4, var2)
        assert var5 == 19
        var6 = 183
        var7 = 1354.898
        var8 = module0.search(var6, var7)
    except BaseException:
        pass


def test_case_46():
    try:
        var0 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var1 = module0.search(var0, var0)
        assert var1 == 19
        var2 = 'P1c'
        var3 = '=a1V0,-=IpP\tYI6yF{'
        var4 = module0.search(var2, var3)
        assert var4 == 17
        var5 = 'UL='
        var6 = '~/n\t\\*k!L'
        var7 = module0.search(var5, var6)
        assert var7 == 9
        var8 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var9 = module0.search(var8, var8)
        assert var9 == 19
        var10 = 'Y\r/'
        var11 = module0.search(var10, var8)
        assert var11 == 19
        var12 = False
        var13 = True
        var14 = module0.search(var12, var13)
    except BaseException:
        pass


def test_case_47():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = '5*:Z{/wY]iy`V_#,.'
        var4 = "|wCIymb'HiL^\\qQ4|L~"
        var5 = module0.search(var3, var4)
        assert var5 == 16
        var6 = '|wdcKu\x0bL%xB ~I'
        var7 = 'z}DPJwn'
        var8 = module0.search(var6, var7)
        assert var8 == 7
        var9 = 'P1c'
        var10 = '=a1V0,-=IpP\tYI6yF{'
        var11 = module0.search(var9, var10)
        assert var11 == 17
        var12 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var13 = module0.search(var12, var12)
        assert var13 == 19
        var14 = 'P1c'
        var15 = '=a1V0,-=IpP\tYI6yF{'
        var16 = module0.search(var14, var15)
        assert var16 == 17
        var17 = 'UL='
        var18 = '~/n\t\\*k!L'
        var19 = module0.search(var17, var18)
        assert var19 == 9
        var20 = '5*:Z{/wY]iy`V_#,.'
        var21 = "|wCIymb'HiL^\\qQ4|L~"
        var22 = module0.search(var20, var21)
        assert var22 == 16
        var23 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var24 = module0.search(var23, var23)
        assert var24 == 19
        var25 = 'Y\r/'
        var26 = module0.search(var25, var23)
        assert var26 == 19
        var27 = '`d'
        var28 = 585.46843
        var29 = module0.search(var27, var28)
    except BaseException:
        pass


def test_case_48():
    try:
        var0 = True
        var1 = None
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_49():
    try:
        var0 = ">o4,o~/R^10.U}mYB'E"
        var1 = None
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_50():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var4 = module0.search(var3, var3)
        assert var4 == 19
        var5 = 'Y\r/'
        var6 = module0.search(var5, var3)
        assert var6 == 19
        var7 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var8 = module0.search(var7, var7)
        assert var8 == 19
        var9 = 'P1c'
        var10 = '=a1V0,-=IpP\tYI6yF{'
        var11 = module0.search(var9, var10)
        assert var11 == 17
        var12 = 'UL='
        var13 = '~/n\t\\*k!L'
        var14 = module0.search(var12, var13)
        assert var14 == 9
        var15 = '5*:Z{/wY]iy`V_#,.'
        var16 = "|wCIymb'HiL^\\qQ4|L~"
        var17 = module0.search(var15, var16)
        assert var17 == 16
        var18 = 'P1c'
        var19 = '=a1V0,-=IpP\tYI6yF{'
        var20 = module0.search(var18, var19)
        assert var20 == 17
        var21 = '5*:Z{/wY]iy`V_#,.'
        var22 = "|wCIymb'HiL^\\qQ4|L~"
        var23 = module0.search(var21, var22)
        assert var23 == 16
        var24 = '|wdcKu\x0bL%xB ~I'
        var25 = 'z}DPJwn'
        var26 = module0.search(var24, var25)
        assert var26 == 7
        var27 = '=ekR8l\\];'
        var28 = -1065
        var29 = module0.search(var27, var28)
    except BaseException:
        pass


def test_case_51():
    try:
        var0 = '5*:Z{/wY]iy`V_#,.'
        var1 = "|wCIymb'HiL^\\qQ4|L~"
        var2 = module0.search(var0, var1)
        assert var2 == 16
        var3 = 'P1c'
        var4 = '=a1V0,-=IpP\tYI6yF{'
        var5 = module0.search(var3, var4)
        assert var5 == 17
        var6 = 'UL='
        var7 = '~/n\t\\*k!L'
        var8 = module0.search(var6, var7)
        assert var8 == 9
        var9 = 'P1c'
        var10 = '=a1V0,-=IpP\tYI6yF{'
        var11 = module0.search(var9, var10)
        assert var11 == 17
        var12 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var13 = module0.search(var12, var12)
        assert var13 == 19
        var14 = -3704
        var15 = module0.search(var14, var6)
    except BaseException:
        pass


def test_case_52():
    try:
        var0 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var1 = module0.search(var0, var0)
        assert var1 == 19
        var2 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var3 = module0.search(var2, var2)
        assert var3 == 19
        var4 = 'Y\r/'
        var5 = module0.search(var4, var2)
        assert var5 == 19
        var6 = 5626
        var7 = module0.search(var6, var4)
    except BaseException:
        pass


def test_case_53():
    try:
        var0 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var1 = module0.search(var0, var0)
        assert var1 == 19
        var2 = 'Y\r/'
        var3 = module0.search(var2, var0)
        assert var3 == 19
        var4 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var5 = module0.search(var4, var4)
        assert var5 == 19
        var6 = 'P1c'
        var7 = '=a1V0,-=IpP\tYI6yF{'
        var8 = module0.search(var6, var7)
        assert var8 == 17
        var9 = 'P1c'
        var10 = '=a1V0,-=IpP\tYI6yF{'
        var11 = module0.search(var9, var10)
        assert var11 == 17
        var12 = 'A`cR|~hY.yY*\x0bq'
        var13 = module0.search(var12, var12)
        assert var13 == 13
        var14 = '5*:Z{/wY]iy`V_#,.'
        var15 = "|wCIymb'HiL^\\qQ4|L~"
        var16 = module0.search(var14, var15)
        assert var16 == 16
        var17 = 'P1c'
        var18 = '=a1V0,-=IpP\tYI6yF{'
        var19 = module0.search(var17, var18)
        assert var19 == 17
        var20 = '5*:Z{/wY]iy`V_#,.'
        var21 = "|wCIymb'HiL^\\qQ4|L~"
        var22 = module0.search(var20, var21)
        assert var22 == 16
        var23 = '|wdcKu\x0bL%xB ~I'
        var24 = 'z}DPJwn'
        var25 = module0.search(var23, var24)
        assert var25 == 7
        var26 = 1238
        var27 = False
        var28 = module0.search(var26, var27)
    except BaseException:
        pass


def test_case_54():
    try:
        var0 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var1 = module0.search(var0, var0)
        assert var1 == 19
        var2 = 'Y\r/'
        var3 = module0.search(var2, var0)
        assert var3 == 19
        var4 = 'P1c'
        var5 = '=a1V0,-=IpP\tYI6yF{'
        var6 = module0.search(var4, var5)
        assert var6 == 17
        var7 = '5*:Z{/wY]iy`V_#,.'
        var8 = "|wCIymb'HiL^\\qQ4|L~"
        var9 = module0.search(var7, var8)
        assert var9 == 16
        var10 = '|wdcKu\x0bL%xB ~I'
        var11 = 'z}DPJwn'
        var12 = module0.search(var10, var11)
        assert var12 == 7
        var13 = 'P1c'
        var14 = '=a1V0,-=IpP\tYI6yF{'
        var15 = module0.search(var13, var14)
        assert var15 == 17
        var16 = 'P1c'
        var17 = '=a1V0,-=IpP\tYI6yF{'
        var18 = module0.search(var16, var17)
        assert var18 == 17
        var19 = 'A`cR|~hY.yY*\x0bq'
        var20 = module0.search(var19, var19)
        assert var20 == 13
        var21 = 'P1c'
        var22 = '=a1V0,-=IpP\tYI6yF{'
        var23 = module0.search(var21, var22)
        assert var23 == 17
        var24 = 'jrC,0)q%!Y'
        var25 = module0.search(var22, var24)
        assert var25 == 9
        var26 = False
        var27 = '|3RIKr_?x'
        var28 = module0.search(var26, var27)
    except BaseException:
        pass


def test_case_55():
    try:
        var0 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var1 = module0.search(var0, var0)
        assert var1 == 19
        var2 = 'P1c'
        var3 = '=a1V0,-=IpP\tYI6yF{'
        var4 = module0.search(var2, var3)
        assert var4 == 17
        var5 = 'jrC,0)q%!Y'
        var6 = module0.search(var3, var5)
        assert var6 == 9
        var7 = 'P1c'
        var8 = '=a1V0,-=IpP\tYI6yF{'
        var9 = module0.search(var7, var8)
        assert var9 == 17
        var10 = 'UL='
        var11 = '~/n\t\\*k!L'
        var12 = module0.search(var10, var11)
        assert var12 == 9
        var13 = 'P1c'
        var14 = '=a1V0,-=IpP\tYI6yF{'
        var15 = module0.search(var13, var14)
        assert var15 == 17
        var16 = 3315.297624
        var17 = True
        var18 = module0.search(var16, var17)
    except BaseException:
        pass


def test_case_56():
    try:
        var0 = '5*:Z{/wY]iy`V_#,.'
        var1 = "|wCIymb'HiL^\\qQ4|L~"
        var2 = module0.search(var0, var1)
        assert var2 == 16
        var3 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var4 = module0.search(var3, var3)
        assert var4 == 19
        var5 = 'Y\r/'
        var6 = module0.search(var5, var3)
        assert var6 == 19
        var7 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var8 = module0.search(var7, var7)
        assert var8 == 19
        var9 = 'P1c'
        var10 = '=a1V0,-=IpP\tYI6yF{'
        var11 = module0.search(var9, var10)
        assert var11 == 17
        var12 = -6278.0
        var13 = True
        var14 = module0.search(var12, var13)
    except BaseException:
        pass


def test_case_57():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = '5*:Z{/wY]iy`V_#,.'
        var4 = "|wCIymb'HiL^\\qQ4|L~"
        var5 = module0.search(var3, var4)
        assert var5 == 16
        var6 = '|wdcKu\x0bL%xB ~I'
        var7 = 'z}DPJwn'
        var8 = module0.search(var6, var7)
        assert var8 == 7
        var9 = 'P1c'
        var10 = '=a1V0,-=IpP\tYI6yF{'
        var11 = module0.search(var9, var10)
        assert var11 == 17
        var12 = 'P1c'
        var13 = '=a1V0,-=IpP\tYI6yF{'
        var14 = module0.search(var12, var13)
        assert var14 == 17
        var15 = 'jrC,0)q%!Y'
        var16 = module0.search(var13, var15)
        assert var16 == 9
        var17 = 'P1c'
        var18 = '=a1V0,-=IpP\tYI6yF{'
        var19 = module0.search(var17, var18)
        assert var19 == 17
        var20 = 'A`cR|~hY.yY*\x0bq'
        var21 = module0.search(var20, var20)
        assert var21 == 13
        var22 = 'P1c'
        var23 = '=a1V0,-=IpP\tYI6yF{'
        var24 = module0.search(var22, var23)
        assert var24 == 17
        var25 = 'UL='
        var26 = '~/n\t\\*k!L'
        var27 = module0.search(var25, var26)
        assert var27 == 9
        var28 = '5*:Z{/wY]iy`V_#,.'
        var29 = "|wCIymb'HiL^\\qQ4|L~"
        var30 = module0.search(var28, var29)
        assert var30 == 16
        var31 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var32 = module0.search(var31, var31)
        assert var32 == 19
        var33 = True
        var34 = True
        var35 = module0.search(var33, var34)
    except BaseException:
        pass


def test_case_58():
    try:
        var0 = -400.1072
        var1 = 174.908021
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_59():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = 'UL='
        var4 = '~/n\t\\*k!L'
        var5 = module0.search(var3, var4)
        assert var5 == 9
        var6 = 'P1c'
        var7 = '=a1V0,-=IpP\tYI6yF{'
        var8 = module0.search(var6, var7)
        assert var8 == 17
        var9 = 'jrC,0)q%!Y'
        var10 = module0.search(var7, var9)
        assert var10 == 9
        var11 = 688.73115
        var12 = 'dQo>_r0M0t'
        var13 = module0.search(var11, var12)
    except BaseException:
        pass


def test_case_60():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = 'jrC,0)q%!Y'
        var4 = module0.search(var1, var3)
        assert var4 == 9
        var5 = 'P1c'
        var6 = '=a1V0,-=IpP\tYI6yF{'
        var7 = module0.search(var5, var6)
        assert var7 == 17
        var8 = '5*:Z{/wY]iy`V_#,.'
        var9 = "|wCIymb'HiL^\\qQ4|L~"
        var10 = module0.search(var8, var9)
        assert var10 == 16
        var11 = '|wdcKu\x0bL%xB ~I'
        var12 = 'z}DPJwn'
        var13 = module0.search(var11, var12)
        assert var13 == 7
        var14 = 'P1c'
        var15 = '=a1V0,-=IpP\tYI6yF{'
        var16 = module0.search(var14, var15)
        assert var16 == 17
        var17 = 'A`cR|~hY.yY*\x0bq'
        var18 = module0.search(var17, var17)
        assert var18 == 13
        var19 = 'P1c'
        var20 = '=a1V0,-=IpP\tYI6yF{'
        var21 = module0.search(var19, var20)
        assert var21 == 17
        var22 = '5*:Z{/wY]iy`V_#,.'
        var23 = "|wCIymb'HiL^\\qQ4|L~"
        var24 = module0.search(var22, var23)
        assert var24 == 16
        var25 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var26 = module0.search(var25, var25)
        assert var26 == 19
        var27 = 'Y\r/'
        var28 = module0.search(var27, var25)
        assert var28 == 19
        var29 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var30 = module0.search(var29, var29)
        assert var30 == 19
        var31 = -660.0
        var32 = -1117
        var33 = module0.search(var31, var32)
    except BaseException:
        pass


def test_case_61():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = 'UL='
        var4 = '~/n\t\\*k!L'
        var5 = module0.search(var3, var4)
        assert var5 == 9
        var6 = '\n>N'
        var7 = 211
        var8 = module0.search(var6, var7)
    except BaseException:
        pass


def test_case_62():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = '5*:Z{/wY]iy`V_#,.'
        var4 = "|wCIymb'HiL^\\qQ4|L~"
        var5 = module0.search(var3, var4)
        assert var5 == 16
        var6 = '|wdcKu\x0bL%xB ~I'
        var7 = 'z}DPJwn'
        var8 = module0.search(var6, var7)
        assert var8 == 7
        var9 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var10 = module0.search(var9, var9)
        assert var10 == 19
        var11 = 'W++ce\x0bg'
        var12 = None
        var13 = module0.search(var11, var12)
    except BaseException:
        pass


def test_case_63():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = 'UL='
        var4 = '~/n\t\\*k!L'
        var5 = module0.search(var3, var4)
        assert var5 == 9
        var6 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var7 = module0.search(var6, var6)
        assert var7 == 19
        var8 = 'Y\r/'
        var9 = module0.search(var8, var6)
        assert var9 == 19
        var10 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var11 = module0.search(var10, var10)
        assert var11 == 19
        var12 = '5*:Z{/wY]iy`V_#,.'
        var13 = "|wCIymb'HiL^\\qQ4|L~"
        var14 = module0.search(var12, var13)
        assert var14 == 16
        var15 = 'P1c'
        var16 = '=a1V0,-=IpP\tYI6yF{'
        var17 = module0.search(var15, var16)
        assert var17 == 17
        var18 = 'jrC,0)q%!Y'
        var19 = module0.search(var16, var18)
        assert var19 == 9
        var20 = None
        var21 = False
        var22 = module0.search(var20, var21)
    except BaseException:
        pass


def test_case_64():
    try:
        var0 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var1 = module0.search(var0, var0)
        assert var1 == 19
        var2 = 'P1c'
        var3 = '=a1V0,-=IpP\tYI6yF{'
        var4 = module0.search(var2, var3)
        assert var4 == 17
        var5 = 'jrC,0)q%!Y'
        var6 = module0.search(var3, var5)
        assert var6 == 9
        var7 = 3733
        var8 = True
        var9 = module0.search(var7, var8)
    except BaseException:
        pass


def test_case_65():
    try:
        var0 = 547
        var1 = 'e4`c\n'
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_66():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = 'jrC,0)q%!Y'
        var4 = module0.search(var1, var3)
        assert var4 == 9
        var5 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var6 = module0.search(var5, var5)
        assert var6 == 19
        var7 = 'Y\r/'
        var8 = module0.search(var7, var5)
        assert var8 == 19
        var9 = 'P1c'
        var10 = '=a1V0,-=IpP\tYI6yF{'
        var11 = module0.search(var9, var10)
        assert var11 == 17
        var12 = 'A`cR|~hY.yY*\x0bq'
        var13 = module0.search(var12, var12)
        assert var13 == 13
        var14 = '5*:Z{/wY]iy`V_#,.'
        var15 = "|wCIymb'HiL^\\qQ4|L~"
        var16 = module0.search(var14, var15)
        assert var16 == 16
        var17 = 'P1c'
        var18 = '=a1V0,-=IpP\tYI6yF{'
        var19 = module0.search(var17, var18)
        assert var19 == 17
        var20 = 'UL='
        var21 = '~/n\t\\*k!L'
        var22 = module0.search(var20, var21)
        assert var22 == 9
        var23 = None
        var24 = 793
        var25 = module0.search(var23, var24)
    except BaseException:
        pass


def test_case_67():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = 'P1c'
        var4 = '=a1V0,-=IpP\tYI6yF{'
        var5 = module0.search(var3, var4)
        assert var5 == 17
        var6 = '5*:Z{/wY]iy`V_#,.'
        var7 = "|wCIymb'HiL^\\qQ4|L~"
        var8 = module0.search(var6, var7)
        assert var8 == 16
        var9 = '|wdcKu\x0bL%xB ~I'
        var10 = 'z}DPJwn'
        var11 = module0.search(var9, var10)
        assert var11 == 7
        var12 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var13 = module0.search(var12, var12)
        assert var13 == 19
        var14 = 'P1c'
        var15 = '=a1V0,-=IpP\tYI6yF{'
        var16 = module0.search(var14, var15)
        assert var16 == 17
        var17 = 'UL='
        var18 = '~/n\t\\*k!L'
        var19 = module0.search(var17, var18)
        assert var19 == 9
        var20 = '5*:Z{/wY]iy`V_#,.'
        var21 = "|wCIymb'HiL^\\qQ4|L~"
        var22 = module0.search(var20, var21)
        assert var22 == 16
        var23 = True
        var24 = 1373
        var25 = module0.search(var23, var24)
    except BaseException:
        pass


def test_case_68():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = 'jrC,0)q%!Y'
        var4 = module0.search(var1, var3)
        assert var4 == 9
        var5 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var6 = module0.search(var5, var5)
        assert var6 == 19
        var7 = 'P1c'
        var8 = '=a1V0,-=IpP\tYI6yF{'
        var9 = module0.search(var7, var8)
        assert var9 == 17
        var10 = 'UL='
        var11 = '~/n\t\\*k!L'
        var12 = module0.search(var10, var11)
        assert var12 == 9
        var13 = '5*:Z{/wY]iy`V_#,.'
        var14 = "|wCIymb'HiL^\\qQ4|L~"
        var15 = module0.search(var13, var14)
        assert var15 == 16
        var16 = 'P1c'
        var17 = '=a1V0,-=IpP\tYI6yF{'
        var18 = module0.search(var16, var17)
        assert var18 == 17
        var19 = 'A`cR|~hY.yY*\x0bq'
        var20 = module0.search(var19, var19)
        assert var20 == 13
        var21 = 'P1c'
        var22 = '=a1V0,-=IpP\tYI6yF{'
        var23 = module0.search(var21, var22)
        assert var23 == 17
        var24 = 'P1c'
        var25 = '=a1V0,-=IpP\tYI6yF{'
        var26 = module0.search(var24, var25)
        assert var26 == 17
        var27 = '5*:Z{/wY]iy`V_#,.'
        var28 = "|wCIymb'HiL^\\qQ4|L~"
        var29 = module0.search(var27, var28)
        assert var29 == 16
        var30 = '|wdcKu\x0bL%xB ~I'
        var31 = 'z}DPJwn'
        var32 = module0.search(var30, var31)
        assert var32 == 7
        var33 = 4356.0
        var34 = module0.search(var33, var33)
    except BaseException:
        pass


def test_case_69():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = 'jrC,0)q%!Y'
        var4 = module0.search(var1, var3)
        assert var4 == 9
        var5 = 'P1c'
        var6 = '=a1V0,-=IpP\tYI6yF{'
        var7 = module0.search(var5, var6)
        assert var7 == 17
        var8 = 'P1c'
        var9 = '=a1V0,-=IpP\tYI6yF{'
        var10 = module0.search(var8, var9)
        assert var10 == 17
        var11 = 'A`cR|~hY.yY*\x0bq'
        var12 = module0.search(var11, var11)
        assert var12 == 13
        var13 = 'P1c'
        var14 = '=a1V0,-=IpP\tYI6yF{'
        var15 = module0.search(var13, var14)
        assert var15 == 17
        var16 = '5*:Z{/wY]iy`V_#,.'
        var17 = "|wCIymb'HiL^\\qQ4|L~"
        var18 = module0.search(var16, var17)
        assert var18 == 16
        var19 = '|wdcKu\x0bL%xB ~I'
        var20 = 'z}DPJwn'
        var21 = module0.search(var19, var20)
        assert var21 == 7
        var22 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var23 = module0.search(var22, var22)
        assert var23 == 19
        var24 = 'Y\r/'
        var25 = module0.search(var24, var22)
        assert var25 == 19
        var26 = 89
        var27 = module0.search(var26, var26)
    except BaseException:
        pass


def test_case_70():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var4 = module0.search(var3, var3)
        assert var4 == 19
        var5 = 'P1c'
        var6 = '=a1V0,-=IpP\tYI6yF{'
        var7 = module0.search(var5, var6)
        assert var7 == 17
        var8 = 'jrC,0)q%!Y'
        var9 = module0.search(var6, var8)
        assert var9 == 9
        var10 = False
        var11 = 931.0
        var12 = module0.search(var10, var11)
    except BaseException:
        pass


def test_case_71():
    try:
        var0 = '5*:Z{/wY]iy`V_#,.'
        var1 = "|wCIymb'HiL^\\qQ4|L~"
        var2 = module0.search(var0, var1)
        assert var2 == 16
        var3 = 'Zk.7/\\~6'
        var4 = 297
        var5 = module0.search(var3, var4)
    except BaseException:
        pass


def test_case_72():
    try:
        var0 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var1 = module0.search(var0, var0)
        assert var1 == 19
        var2 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var3 = module0.search(var2, var2)
        assert var3 == 19
        var4 = 'Y\r/'
        var5 = module0.search(var4, var2)
        assert var5 == 19
        var6 = '"bFZiI<w[#[mUz0=2_~'
        var7 = module0.search(var6, var6)
        assert var7 == 1
        var8 = None
        var9 = module0.search(var8, var8)
    except BaseException:
        pass


def test_case_73():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = 'P1c'
        var4 = '=a1V0,-=IpP\tYI6yF{'
        var5 = module0.search(var3, var4)
        assert var5 == 17
        var6 = 'UL='
        var7 = '~/n\t\\*k!L'
        var8 = module0.search(var6, var7)
        assert var8 == 9
        var9 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var10 = module0.search(var9, var9)
        assert var10 == 19
        var11 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var12 = module0.search(var11, var11)
        assert var12 == 19
        var13 = 'Y\r/'
        var14 = module0.search(var13, var11)
        assert var14 == 19
        var15 = 'P1c'
        var16 = '=a1V0,-=IpP\tYI6yF{'
        var17 = module0.search(var15, var16)
        assert var17 == 17
        var18 = 'A`cR|~hY.yY*\x0bq'
        var19 = module0.search(var18, var18)
        assert var19 == 13
        var20 = '5*:Z{/wY]iy`V_#,.'
        var21 = "|wCIymb'HiL^\\qQ4|L~"
        var22 = module0.search(var20, var21)
        assert var22 == 16
        var23 = False
        var24 = '(k9_cHbsspIa\x0b`V9K{ek'
        var25 = module0.search(var23, var24)
    except BaseException:
        pass


def test_case_74():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = -2940
        var4 = 'VfI*]<?'
        var5 = module0.search(var3, var4)
    except BaseException:
        pass


def test_case_75():
    try:
        var0 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var1 = module0.search(var0, var0)
        assert var1 == 19
        var2 = 'P1c'
        var3 = '=a1V0,-=IpP\tYI6yF{'
        var4 = module0.search(var2, var3)
        assert var4 == 17
        var5 = 'jrC,0)q%!Y'
        var6 = module0.search(var3, var5)
        assert var6 == 9
        var7 = '5*:Z{/wY]iy`V_#,.'
        var8 = "|wCIymb'HiL^\\qQ4|L~"
        var9 = module0.search(var7, var8)
        assert var9 == 16
        var10 = '"bFZiI<w[#[mUz0=2_~'
        var11 = module0.search(var10, var10)
        assert var11 == 1
        var12 = 'P1c'
        var13 = '=a1V0,-=IpP\tYI6yF{'
        var14 = module0.search(var12, var13)
        assert var14 == 17
        var15 = 'UL='
        var16 = '~/n\t\\*k!L'
        var17 = module0.search(var15, var16)
        assert var17 == 9
        var18 = 'P1c'
        var19 = '=a1V0,-=IpP\tYI6yF{'
        var20 = module0.search(var18, var19)
        assert var20 == 17
        var21 = 'P1c'
        var22 = '=a1V0,-=IpP\tYI6yF{'
        var23 = module0.search(var21, var22)
        assert var23 == 17
        var24 = 'A`cR|~hY.yY*\x0bq'
        var25 = module0.search(var24, var24)
        assert var25 == 13
        var26 = 't^\n*S\t5%qC N<PoRc'
        var27 = True
        var28 = module0.search(var26, var27)
    except BaseException:
        pass


def test_case_76():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = '5*:Z{/wY]iy`V_#,.'
        var4 = "|wCIymb'HiL^\\qQ4|L~"
        var5 = module0.search(var3, var4)
        assert var5 == 16
        var6 = '|wdcKu\x0bL%xB ~I'
        var7 = 'z}DPJwn'
        var8 = module0.search(var6, var7)
        assert var8 == 7
        var9 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var10 = module0.search(var9, var9)
        assert var10 == 19
        var11 = '"bFZiI<w[#[mUz0=2_~'
        var12 = module0.search(var11, var11)
        assert var12 == 1
        var13 = 'P1c'
        var14 = '=a1V0,-=IpP\tYI6yF{'
        var15 = module0.search(var13, var14)
        assert var15 == 17
        var16 = -884
        var17 = '-7Jt'
        var18 = module0.search(var16, var17)
    except BaseException:
        pass


def test_case_77():
    try:
        var0 = '"bFZiI<w[#[mUz0=2_~'
        var1 = module0.search(var0, var0)
        assert var1 == 1
        var2 = 'P1c'
        var3 = '=a1V0,-=IpP\tYI6yF{'
        var4 = module0.search(var2, var3)
        assert var4 == 17
        var5 = 'jrC,0)q%!Y'
        var6 = module0.search(var3, var5)
        assert var6 == 9
        var7 = '5*:Z{/wY]iy`V_#,.'
        var8 = "|wCIymb'HiL^\\qQ4|L~"
        var9 = module0.search(var7, var8)
        assert var9 == 16
        var10 = 'P1c'
        var11 = '=a1V0,-=IpP\tYI6yF{'
        var12 = module0.search(var10, var11)
        assert var12 == 17
        var13 = 'P1c'
        var14 = '=a1V0,-=IpP\tYI6yF{'
        var15 = module0.search(var13, var14)
        assert var15 == 17
        var16 = 'UL='
        var17 = '~/n\t\\*k!L'
        var18 = module0.search(var16, var17)
        assert var18 == 9
        var19 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var20 = module0.search(var19, var19)
        assert var20 == 19
        var21 = 'P1c'
        var22 = '=a1V0,-=IpP\tYI6yF{'
        var23 = module0.search(var21, var22)
        assert var23 == 17
        var24 = 'A`cR|~hY.yY*\x0bq'
        var25 = module0.search(var24, var24)
        assert var25 == 13
        var26 = 'V~6N?u`4'
        var27 = 2216.73272
        var28 = module0.search(var26, var27)
    except BaseException:
        pass


def test_case_78():
    try:
        var0 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var1 = module0.search(var0, var0)
        assert var1 == 19
        var2 = 'Y\r/'
        var3 = module0.search(var2, var0)
        assert var3 == 19
        var4 = 'P1c'
        var5 = '=a1V0,-=IpP\tYI6yF{'
        var6 = module0.search(var4, var5)
        assert var6 == 17
        var7 = 'P1c'
        var8 = '=a1V0,-=IpP\tYI6yF{'
        var9 = module0.search(var7, var8)
        assert var9 == 17
        var10 = 'jrC,0)q%!Y'
        var11 = module0.search(var8, var10)
        assert var11 == 9
        var12 = 'P1c'
        var13 = '=a1V0,-=IpP\tYI6yF{'
        var14 = module0.search(var12, var13)
        assert var14 == 17
        var15 = 'UL='
        var16 = '~/n\t\\*k!L'
        var17 = module0.search(var15, var16)
        assert var17 == 9
        var18 = '"bFZiI<w[#[mUz0=2_~'
        var19 = module0.search(var18, var18)
        assert var19 == 1
        var20 = -113
        var21 = "-^_'QHZr7"
        var22 = module0.search(var20, var21)
    except BaseException:
        pass


def test_case_79():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = 'UL='
        var4 = '~/n\t\\*k!L'
        var5 = module0.search(var3, var4)
        assert var5 == 9
        var6 = '5*:Z{/wY]iy`V_#,.'
        var7 = "|wCIymb'HiL^\\qQ4|L~"
        var8 = module0.search(var6, var7)
        assert var8 == 16
        var9 = 'P1c'
        var10 = '=a1V0,-=IpP\tYI6yF{'
        var11 = module0.search(var9, var10)
        assert var11 == 17
        var12 = 'jrC,0)q%!Y'
        var13 = module0.search(var10, var12)
        assert var13 == 9
        var14 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var15 = module0.search(var14, var14)
        assert var15 == 19
        var16 = 'Y\r/'
        var17 = module0.search(var16, var14)
        assert var17 == 19
        var18 = False
        var19 = '3WQ8v7AvgG>)_\x0c\x0bB8'
        var20 = module0.search(var18, var19)
    except BaseException:
        pass


def test_case_80():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = '5*:Z{/wY]iy`V_#,.'
        var4 = "|wCIymb'HiL^\\qQ4|L~"
        var5 = module0.search(var3, var4)
        assert var5 == 16
        var6 = '|wdcKu\x0bL%xB ~I'
        var7 = 'z}DPJwn'
        var8 = module0.search(var6, var7)
        assert var8 == 7
        var9 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var10 = module0.search(var9, var9)
        assert var10 == 19
        var11 = 'P1c'
        var12 = '=a1V0,-=IpP\tYI6yF{'
        var13 = module0.search(var11, var12)
        assert var13 == 17
        var14 = 'P1c'
        var15 = '=a1V0,-=IpP\tYI6yF{'
        var16 = module0.search(var14, var15)
        assert var16 == 17
        var17 = 'A`cR|~hY.yY*\x0bq'
        var18 = module0.search(var17, var17)
        assert var18 == 13
        var19 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var20 = module0.search(var19, var19)
        assert var20 == 19
        var21 = 'Y\r/'
        var22 = module0.search(var21, var19)
        assert var22 == 19
        var23 = '5*:Z{/wY]iy`V_#,.'
        var24 = "|wCIymb'HiL^\\qQ4|L~"
        var25 = module0.search(var23, var24)
        assert var25 == 16
        var26 = '"bFZiI<w[#[mUz0=2_~'
        var27 = module0.search(var26, var26)
        assert var27 == 1
        var28 = 'P1c'
        var29 = '=a1V0,-=IpP\tYI6yF{'
        var30 = module0.search(var28, var29)
        assert var30 == 17
        var31 = 'jrC,0)q%!Y'
        var32 = module0.search(var29, var31)
        assert var32 == 9
        var33 = 'P1c'
        var34 = '=a1V0,-=IpP\tYI6yF{'
        var35 = module0.search(var33, var34)
        assert var35 == 17
        var36 = 'UL='
        var37 = '~/n\t\\*k!L'
        var38 = module0.search(var36, var37)
        assert var38 == 9
        var39 = '`}66q[RWGvQa\x0cN#^'
        var40 = 728.99
        var41 = module0.search(var39, var40)
    except BaseException:
        pass


def test_case_81():
    try:
        var0 = '.mgzGy&a)M0G\rD%3D_|p'
        var1 = -3162.2
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_82():
    try:
        var0 = '"bFZiI<w[#[mUz0=2_~'
        var1 = module0.search(var0, var0)
        assert var1 == 1
        var2 = 'P1c'
        var3 = '=a1V0,-=IpP\tYI6yF{'
        var4 = module0.search(var2, var3)
        assert var4 == 17
        var5 = 'UL='
        var6 = '~/n\t\\*k!L'
        var7 = module0.search(var5, var6)
        assert var7 == 9
        var8 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var9 = module0.search(var8, var8)
        assert var9 == 19
        var10 = -1264
        var11 = '*Sq'
        var12 = module0.search(var10, var11)
    except BaseException:
        pass


def test_case_83():
    try:
        var0 = 3250.0
        var1 = True
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_84():
    try:
        var0 = '5*:Z{/wY]iy`V_#,.'
        var1 = "|wCIymb'HiL^\\qQ4|L~"
        var2 = module0.search(var0, var1)
        assert var2 == 16
        var3 = '"bFZiI<w[#[mUz0=2_~'
        var4 = module0.search(var3, var3)
        assert var4 == 1
        var5 = 'P1c'
        var6 = '=a1V0,-=IpP\tYI6yF{'
        var7 = module0.search(var5, var6)
        assert var7 == 17
        var8 = '5*:Z{/wY]iy`V_#,.'
        var9 = "|wCIymb'HiL^\\qQ4|L~"
        var10 = module0.search(var8, var9)
        assert var10 == 16
        var11 = '|wdcKu\x0bL%xB ~I'
        var12 = 'z}DPJwn'
        var13 = module0.search(var11, var12)
        assert var13 == 7
        var14 = 'P1c'
        var15 = '=a1V0,-=IpP\tYI6yF{'
        var16 = module0.search(var14, var15)
        assert var16 == 17
        var17 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var18 = module0.search(var17, var17)
        assert var18 == 19
        var19 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var20 = module0.search(var19, var19)
        assert var20 == 19
        var21 = 'Y\r/'
        var22 = module0.search(var21, var19)
        assert var22 == 19
        var23 = 'P1c'
        var24 = '=a1V0,-=IpP\tYI6yF{'
        var25 = module0.search(var23, var24)
        assert var25 == 17
        var26 = 'A`cR|~hY.yY*\x0bq'
        var27 = module0.search(var26, var26)
        assert var27 == 13
        var28 = 'P1c'
        var29 = '=a1V0,-=IpP\tYI6yF{'
        var30 = module0.search(var28, var29)
        assert var30 == 17
        var31 = 'UL='
        var32 = '~/n\t\\*k!L'
        var33 = module0.search(var31, var32)
        assert var33 == 9
        var34 = 'P1c'
        var35 = '=a1V0,-=IpP\tYI6yF{'
        var36 = module0.search(var34, var35)
        assert var36 == 17
        var37 = 'jrC,0)q%!Y'
        var38 = module0.search(var35, var37)
        assert var38 == 9
        var39 = -439
        var40 = module0.search(var39, var39)
    except BaseException:
        pass


def test_case_85():
    try:
        var0 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var1 = module0.search(var0, var0)
        assert var1 == 19
        var2 = 'Y\r/'
        var3 = module0.search(var2, var0)
        assert var3 == 19
        var4 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var5 = module0.search(var4, var4)
        assert var5 == 19
        var6 = 2235.69992
        var7 = 'WP>R'
        var8 = module0.search(var6, var7)
    except BaseException:
        pass


def test_case_86():
    try:
        var0 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var1 = module0.search(var0, var0)
        assert var1 == 19
        var2 = 'Y\r/'
        var3 = module0.search(var2, var0)
        assert var3 == 19
        var4 = '5*:Z{/wY]iy`V_#,.'
        var5 = "|wCIymb'HiL^\\qQ4|L~"
        var6 = module0.search(var4, var5)
        assert var6 == 16
        var7 = 'P1c'
        var8 = '=a1V0,-=IpP\tYI6yF{'
        var9 = module0.search(var7, var8)
        assert var9 == 17
        var10 = 'jrC,0)q%!Y'
        var11 = module0.search(var8, var10)
        assert var11 == 9
        var12 = False
        var13 = -1370
        var14 = module0.search(var12, var13)
    except BaseException:
        pass


def test_case_87():
    try:
        var0 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var1 = module0.search(var0, var0)
        assert var1 == 19
        var2 = 'Y\r/'
        var3 = module0.search(var2, var0)
        assert var3 == 19
        var4 = 'P1c'
        var5 = '=a1V0,-=IpP\tYI6yF{'
        var6 = module0.search(var4, var5)
        assert var6 == 17
        var7 = 'A`cR|~hY.yY*\x0bq'
        var8 = module0.search(var7, var7)
        assert var8 == 13
        var9 = 'P1c'
        var10 = '=a1V0,-=IpP\tYI6yF{'
        var11 = module0.search(var9, var10)
        assert var11 == 17
        var12 = 'jrC,0)q%!Y'
        var13 = module0.search(var10, var12)
        assert var13 == 9
        var14 = '"bFZiI<w[#[mUz0=2_~'
        var15 = module0.search(var14, var14)
        assert var15 == 1
        var16 = 'P1c'
        var17 = '=a1V0,-=IpP\tYI6yF{'
        var18 = module0.search(var16, var17)
        assert var18 == 17
        var19 = 'P1c'
        var20 = '=a1V0,-=IpP\tYI6yF{'
        var21 = module0.search(var19, var20)
        assert var21 == 17
        var22 = 'UL='
        var23 = '~/n\t\\*k!L'
        var24 = module0.search(var22, var23)
        assert var24 == 9
        var25 = '5*:Z{/wY]iy`V_#,.'
        var26 = "|wCIymb'HiL^\\qQ4|L~"
        var27 = module0.search(var25, var26)
        assert var27 == 16
        var28 = 'Zft1SG[4WS3d'
        var29 = None
        var30 = module0.search(var28, var29)
    except BaseException:
        pass


def test_case_88():
    try:
        var0 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var1 = module0.search(var0, var0)
        assert var1 == 19
        var2 = 'P1c'
        var3 = '=a1V0,-=IpP\tYI6yF{'
        var4 = module0.search(var2, var3)
        assert var4 == 17
        var5 = '5*:Z{/wY]iy`V_#,.'
        var6 = "|wCIymb'HiL^\\qQ4|L~"
        var7 = module0.search(var5, var6)
        assert var7 == 16
        var8 = '|wdcKu\x0bL%xB ~I'
        var9 = 'z}DPJwn'
        var10 = module0.search(var8, var9)
        assert var10 == 7
        var11 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var12 = module0.search(var11, var11)
        assert var12 == 19
        var13 = 'Y\r/'
        var14 = module0.search(var13, var11)
        assert var14 == 19
        var15 = 'P1c'
        var16 = '=a1V0,-=IpP\tYI6yF{'
        var17 = module0.search(var15, var16)
        assert var17 == 17
        var18 = 'jrC,0)q%!Y'
        var19 = module0.search(var16, var18)
        assert var19 == 9
        var20 = '"bFZiI<w[#[mUz0=2_~'
        var21 = module0.search(var20, var20)
        assert var21 == 1
        var22 = 'P1c'
        var23 = '=a1V0,-=IpP\tYI6yF{'
        var24 = module0.search(var22, var23)
        assert var24 == 17
        var25 = 'A`cR|~hY.yY*\x0bq'
        var26 = module0.search(var25, var25)
        assert var26 == 13
        var27 = 729.259
        var28 = None
        var29 = module0.search(var27, var28)
    except BaseException:
        pass


def test_case_89():
    try:
        var0 = '"bFZiI<w[#[mUz0=2_~'
        var1 = module0.search(var0, var0)
        assert var1 == 1
        var2 = '5*:Z{/wY]iy`V_#,.'
        var3 = "|wCIymb'HiL^\\qQ4|L~"
        var4 = module0.search(var2, var3)
        assert var4 == 16
        var5 = 'P1c'
        var6 = '=a1V0,-=IpP\tYI6yF{'
        var7 = module0.search(var5, var6)
        assert var7 == 17
        var8 = 'jrC,0)q%!Y'
        var9 = module0.search(var6, var8)
        assert var9 == 9
        var10 = 1957.922
        var11 = 'frge:Yk\\agz'
        var12 = module0.search(var10, var11)
    except BaseException:
        pass


def test_case_90():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = 'A`cR|~hY.yY*\x0bq'
        var4 = module0.search(var3, var3)
        assert var4 == 13
        var5 = '"bFZiI<w[#[mUz0=2_~'
        var6 = module0.search(var5, var5)
        assert var6 == 1
        var7 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var8 = module0.search(var7, var7)
        assert var8 == 19
        var9 = 'kwM3x(d47O$~#mplZk\\F'
        var10 = 'lY4GQ|J@&;7SL%'
        var11 = module0.search(var9, var10)
        assert var11 == 14
        var12 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var13 = module0.search(var12, var12)
        assert var13 == 19
        var14 = 'P1c'
        var15 = '=a1V0,-=IpP\tYI6yF{'
        var16 = module0.search(var14, var15)
        assert var16 == 17
        var17 = 'P1c'
        var18 = '=a1V0,-=IpP\tYI6yF{'
        var19 = module0.search(var17, var18)
        assert var19 == 17
        var20 = 'jrC,0)q%!Y'
        var21 = module0.search(var18, var20)
        assert var21 == 9
        var22 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var23 = module0.search(var22, var22)
        assert var23 == 19
        var24 = 'Y\r/'
        var25 = module0.search(var24, var22)
        assert var25 == 19
        var26 = 'P1c'
        var27 = '=a1V0,-=IpP\tYI6yF{'
        var28 = module0.search(var26, var27)
        assert var28 == 17
        var29 = 'UL='
        var30 = '~/n\t\\*k!L'
        var31 = module0.search(var29, var30)
        assert var31 == 9
        var32 = '5*:Z{/wY]iy`V_#,.'
        var33 = "|wCIymb'HiL^\\qQ4|L~"
        var34 = module0.search(var32, var33)
        assert var34 == 16
        var35 = 'P1c'
        var36 = '=a1V0,-=IpP\tYI6yF{'
        var37 = module0.search(var35, var36)
        assert var37 == 17
        var38 = '5*:Z{/wY]iy`V_#,.'
        var39 = "|wCIymb'HiL^\\qQ4|L~"
        var40 = module0.search(var38, var39)
        assert var40 == 16
        var41 = '|wdcKu\x0bL%xB ~I'
        var42 = 'z}DPJwn'
        var43 = module0.search(var41, var42)
        assert var43 == 7
        var44 = False
        var45 = module0.search(var44, var44)
    except BaseException:
        pass


def test_case_91():
    try:
        var0 = '\r,tIx'
        var1 = 1963.11
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_92():
    try:
        var0 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var1 = module0.search(var0, var0)
        assert var1 == 19
        var2 = '5*:Z{/wY]iy`V_#,.'
        var3 = "|wCIymb'HiL^\\qQ4|L~"
        var4 = module0.search(var2, var3)
        assert var4 == 16
        var5 = 'P1c'
        var6 = '=a1V0,-=IpP\tYI6yF{'
        var7 = module0.search(var5, var6)
        assert var7 == 17
        var8 = 'jrC,0)q%!Y'
        var9 = module0.search(var6, var8)
        assert var9 == 9
        var10 = 'P1c'
        var11 = '=a1V0,-=IpP\tYI6yF{'
        var12 = module0.search(var10, var11)
        assert var12 == 17
        var13 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var14 = module0.search(var13, var13)
        assert var14 == 19
        var15 = 'Y\r/'
        var16 = module0.search(var15, var13)
        assert var16 == 19
        var17 = 'P1c'
        var18 = '=a1V0,-=IpP\tYI6yF{'
        var19 = module0.search(var17, var18)
        assert var19 == 17
        var20 = 'UL='
        var21 = '~/n\t\\*k!L'
        var22 = module0.search(var20, var21)
        assert var22 == 9
        var23 = None
        var24 = 'Z\x0b\n|,V_|/Y&<'
        var25 = module0.search(var23, var24)
    except BaseException:
        pass


def test_case_93():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = 'jrC,0)q%!Y'
        var4 = module0.search(var1, var3)
        assert var4 == 9
        var5 = 'P1c'
        var6 = '=a1V0,-=IpP\tYI6yF{'
        var7 = module0.search(var5, var6)
        assert var7 == 17
        var8 = 'A`cR|~hY.yY*\x0bq'
        var9 = module0.search(var8, var8)
        assert var9 == 13
        var10 = '5*:Z{/wY]iy`V_#,.'
        var11 = "|wCIymb'HiL^\\qQ4|L~"
        var12 = module0.search(var10, var11)
        assert var12 == 16
        var13 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var14 = module0.search(var13, var13)
        assert var14 == 19
        var15 = 'kwM3x(d47O$~#mplZk\\F'
        var16 = 'lY4GQ|J@&;7SL%'
        var17 = module0.search(var15, var16)
        assert var17 == 14
        var18 = True
        var19 = True
        var20 = module0.search(var18, var19)
    except BaseException:
        pass


def test_case_94():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = 'UL='
        var4 = '~/n\t\\*k!L'
        var5 = module0.search(var3, var4)
        assert var5 == 9
        var6 = -1800.132726
        var7 = '~{YX*E!?/?'
        var8 = module0.search(var6, var7)
    except BaseException:
        pass


def test_case_95():
    try:
        var0 = '5*:Z{/wY]iy`V_#,.'
        var1 = "|wCIymb'HiL^\\qQ4|L~"
        var2 = module0.search(var0, var1)
        assert var2 == 16
        var3 = '"bFZiI<w[#[mUz0=2_~'
        var4 = module0.search(var3, var3)
        assert var4 == 1
        var5 = -1624
        var6 = 1290.94
        var7 = module0.search(var5, var6)
    except BaseException:
        pass


def test_case_96():
    try:
        var0 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var1 = module0.search(var0, var0)
        assert var1 == 19
        var2 = 'Y\r/'
        var3 = module0.search(var2, var0)
        assert var3 == 19
        var4 = 'P1c'
        var5 = '=a1V0,-=IpP\tYI6yF{'
        var6 = module0.search(var4, var5)
        assert var6 == 17
        var7 = '5*:Z{/wY]iy`V_#,.'
        var8 = "|wCIymb'HiL^\\qQ4|L~"
        var9 = module0.search(var7, var8)
        assert var9 == 16
        var10 = '|wdcKu\x0bL%xB ~I'
        var11 = 'z}DPJwn'
        var12 = module0.search(var10, var11)
        assert var12 == 7
        var13 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var14 = module0.search(var13, var13)
        assert var14 == 19
        var15 = 'kwM3x(d47O$~#mplZk\\F'
        var16 = 'lY4GQ|J@&;7SL%'
        var17 = module0.search(var15, var16)
        assert var17 == 14
        var18 = 'P1c'
        var19 = '=a1V0,-=IpP\tYI6yF{'
        var20 = module0.search(var18, var19)
        assert var20 == 17
        var21 = '5*:Z{/wY]iy`V_#,.'
        var22 = "|wCIymb'HiL^\\qQ4|L~"
        var23 = module0.search(var21, var22)
        assert var23 == 16
        var24 = '"bFZiI<w[#[mUz0=2_~'
        var25 = module0.search(var24, var24)
        assert var25 == 1
        var26 = None
        var27 = module0.search(var18, var26)
    except BaseException:
        pass


def test_case_97():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = '5*:Z{/wY]iy`V_#,.'
        var4 = "|wCIymb'HiL^\\qQ4|L~"
        var5 = module0.search(var3, var4)
        assert var5 == 16
        var6 = '|wdcKu\x0bL%xB ~I'
        var7 = 'z}DPJwn'
        var8 = module0.search(var6, var7)
        assert var8 == 7
        var9 = 'P1c'
        var10 = '=a1V0,-=IpP\tYI6yF{'
        var11 = module0.search(var9, var10)
        assert var11 == 17
        var12 = '5*:Z{/wY]iy`V_#,.'
        var13 = "|wCIymb'HiL^\\qQ4|L~"
        var14 = module0.search(var12, var13)
        assert var14 == 16
        var15 = 'P1c'
        var16 = '=a1V0,-=IpP\tYI6yF{'
        var17 = module0.search(var15, var16)
        assert var17 == 17
        var18 = 'jrC,0)q%!Y'
        var19 = module0.search(var16, var18)
        assert var19 == 9
        var20 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var21 = module0.search(var20, var20)
        assert var21 == 19
        var22 = 'kwM3x(d47O$~#mplZk\\F'
        var23 = 'lY4GQ|J@&;7SL%'
        var24 = module0.search(var22, var23)
        assert var24 == 14
        var25 = 'o++s`<-S20}Bdy<1H'
        var26 = 1470.17
        var27 = module0.search(var25, var26)
    except BaseException:
        pass


def test_case_98():
    try:
        var0 = '5*:Z{/wY]iy`V_#,.'
        var1 = "|wCIymb'HiL^\\qQ4|L~"
        var2 = module0.search(var0, var1)
        assert var2 == 16
        var3 = 'P1c'
        var4 = '=a1V0,-=IpP\tYI6yF{'
        var5 = module0.search(var3, var4)
        assert var5 == 17
        var6 = 'UL='
        var7 = '~/n\t\\*k!L'
        var8 = module0.search(var6, var7)
        assert var8 == 9
        var9 = 4055
        var10 = module0.search(var4, var9)
    except BaseException:
        pass


def test_case_99():
    try:
        var0 = '5*:Z{/wY]iy`V_#,.'
        var1 = "|wCIymb'HiL^\\qQ4|L~"
        var2 = module0.search(var0, var1)
        assert var2 == 16
        var3 = '"bFZiI<w[#[mUz0=2_~'
        var4 = module0.search(var3, var3)
        assert var4 == 1
        var5 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var6 = module0.search(var5, var5)
        assert var6 == 19
        var7 = 'P1c'
        var8 = '=a1V0,-=IpP\tYI6yF{'
        var9 = module0.search(var7, var8)
        assert var9 == 17
        var10 = 'jrC,0)q%!Y'
        var11 = module0.search(var8, var10)
        assert var11 == 9
        var12 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var13 = module0.search(var12, var12)
        assert var13 == 19
        var14 = 'kwM3x(d47O$~#mplZk\\F'
        var15 = 'lY4GQ|J@&;7SL%'
        var16 = module0.search(var14, var15)
        assert var16 == 14
        var17 = 'P1c'
        var18 = '=a1V0,-=IpP\tYI6yF{'
        var19 = module0.search(var17, var18)
        assert var19 == 17
        var20 = '5*:Z{/wY]iy`V_#,.'
        var21 = "|wCIymb'HiL^\\qQ4|L~"
        var22 = module0.search(var20, var21)
        assert var22 == 16
        var23 = '|wdcKu\x0bL%xB ~I'
        var24 = 'z}DPJwn'
        var25 = module0.search(var23, var24)
        assert var25 == 7
        var26 = 'P1c'
        var27 = '=a1V0,-=IpP\tYI6yF{'
        var28 = module0.search(var26, var27)
        assert var28 == 17
        var29 = 'UL='
        var30 = '~/n\t\\*k!L'
        var31 = module0.search(var29, var30)
        assert var31 == 9
        var32 = 'P1c'
        var33 = '=a1V0,-=IpP\tYI6yF{'
        var34 = module0.search(var32, var33)
        assert var34 == 17
        var35 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var36 = module0.search(var35, var35)
        assert var36 == 19
        var37 = 'Y\r/'
        var38 = module0.search(var37, var35)
        assert var38 == 19
        var39 = False
        var40 = 'tOBC'
        var41 = module0.search(var39, var40)
    except BaseException:
        pass


def test_case_100():
    try:
        var0 = '"bFZiI<w[#[mUz0=2_~'
        var1 = module0.search(var0, var0)
        assert var1 == 1
        var2 = 'P1c'
        var3 = '=a1V0,-=IpP\tYI6yF{'
        var4 = module0.search(var2, var3)
        assert var4 == 17
        var5 = 'A`cR|~hY.yY*\x0bq'
        var6 = module0.search(var5, var5)
        assert var6 == 13
        var7 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var8 = module0.search(var7, var7)
        assert var8 == 19
        var9 = 'Y\r/'
        var10 = module0.search(var9, var7)
        assert var10 == 19
        var11 = 'P1c'
        var12 = '=a1V0,-=IpP\tYI6yF{'
        var13 = module0.search(var11, var12)
        assert var13 == 17
        var14 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var15 = module0.search(var14, var14)
        assert var15 == 19
        var16 = '5*:Z{/wY]iy`V_#,.'
        var17 = "|wCIymb'HiL^\\qQ4|L~"
        var18 = module0.search(var16, var17)
        assert var18 == 16
        var19 = -2144.0
        var20 = module0.search(var19, var14)
    except BaseException:
        pass


def test_case_101():
    try:
        var0 = 'UK6M^_?'
        var1 = -3574.477536
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_102():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = '5*:Z{/wY]iy`V_#,.'
        var4 = "|wCIymb'HiL^\\qQ4|L~"
        var5 = module0.search(var3, var4)
        assert var5 == 16
        var6 = '|wdcKu\x0bL%xB ~I'
        var7 = 'z}DPJwn'
        var8 = module0.search(var6, var7)
        assert var8 == 7
        var9 = 'P1c'
        var10 = '=a1V0,-=IpP\tYI6yF{'
        var11 = module0.search(var9, var10)
        assert var11 == 17
        var12 = 'UL='
        var13 = '~/n\t\\*k!L'
        var14 = module0.search(var12, var13)
        assert var14 == 9
        var15 = 'P1c'
        var16 = '=a1V0,-=IpP\tYI6yF{'
        var17 = module0.search(var15, var16)
        assert var17 == 17
        var18 = 'A`cR|~hY.yY*\x0bq'
        var19 = module0.search(var18, var18)
        assert var19 == 13
        var20 = '"bFZiI<w[#[mUz0=2_~'
        var21 = module0.search(var20, var20)
        assert var21 == 1
        var22 = '5*:Z{/wY]iy`V_#,.'
        var23 = "|wCIymb'HiL^\\qQ4|L~"
        var24 = module0.search(var22, var23)
        assert var24 == 16
        var25 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var26 = module0.search(var25, var25)
        assert var26 == 19
        var27 = 'P1c'
        var28 = '=a1V0,-=IpP\tYI6yF{'
        var29 = module0.search(var27, var28)
        assert var29 == 17
        var30 = 'jrC,0)q%!Y'
        var31 = module0.search(var28, var30)
        assert var31 == 9
        var32 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var33 = module0.search(var32, var32)
        assert var33 == 19
        var34 = 'kwM3x(d47O$~#mplZk\\F'
        var35 = 'lY4GQ|J@&;7SL%'
        var36 = module0.search(var34, var35)
        assert var36 == 14
        var37 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var38 = module0.search(var37, var37)
        assert var38 == 19
        var39 = 'Y\r/'
        var40 = module0.search(var39, var37)
        assert var40 == 19
        var41 = None
        var42 = module0.search(var9, var41)
    except BaseException:
        pass


def test_case_103():
    try:
        var0 = '"bFZiI<w[#[mUz0=2_~'
        var1 = module0.search(var0, var0)
        assert var1 == 1
        var2 = 'P1c'
        var3 = '=a1V0,-=IpP\tYI6yF{'
        var4 = module0.search(var2, var3)
        assert var4 == 17
        var5 = 'P1c'
        var6 = '=a1V0,-=IpP\tYI6yF{'
        var7 = module0.search(var5, var6)
        assert var7 == 17
        var8 = 'UL='
        var9 = '~/n\t\\*k!L'
        var10 = module0.search(var8, var9)
        assert var10 == 9
        var11 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var12 = module0.search(var11, var11)
        assert var12 == 19
        var13 = 'kwM3x(d47O$~#mplZk\\F'
        var14 = 'lY4GQ|J@&;7SL%'
        var15 = module0.search(var13, var14)
        assert var15 == 14
        var16 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var17 = module0.search(var16, var16)
        assert var17 == 19
        var18 = 'P1c'
        var19 = '=a1V0,-=IpP\tYI6yF{'
        var20 = module0.search(var18, var19)
        assert var20 == 17
        var21 = '5*:Z{/wY]iy`V_#,.'
        var22 = "|wCIymb'HiL^\\qQ4|L~"
        var23 = module0.search(var21, var22)
        assert var23 == 16
        var24 = '|wdcKu\x0bL%xB ~I'
        var25 = 'z}DPJwn'
        var26 = module0.search(var24, var25)
        assert var26 == 7
        var27 = 'P1c'
        var28 = '=a1V0,-=IpP\tYI6yF{'
        var29 = module0.search(var27, var28)
        assert var29 == 17
        var30 = 'jrC,0)q%!Y'
        var31 = module0.search(var28, var30)
        assert var31 == 9
        var32 = 'P1c'
        var33 = '=a1V0,-=IpP\tYI6yF{'
        var34 = module0.search(var32, var33)
        assert var34 == 17
        var35 = 'A`cR|~hY.yY*\x0bq'
        var36 = module0.search(var35, var35)
        assert var36 == 13
        var37 = -1411
        var38 = False
        var39 = module0.search(var37, var38)
    except BaseException:
        pass


def test_case_104():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = 'jrC,0)q%!Y'
        var4 = module0.search(var1, var3)
        assert var4 == 9
        var5 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var6 = module0.search(var5, var5)
        assert var6 == 19
        var7 = 'kwM3x(d47O$~#mplZk\\F'
        var8 = 'lY4GQ|J@&;7SL%'
        var9 = module0.search(var7, var8)
        assert var9 == 14
        var10 = '5*:Z{/wY]iy`V_#,.'
        var11 = "|wCIymb'HiL^\\qQ4|L~"
        var12 = module0.search(var10, var11)
        assert var12 == 16
        var13 = '"bFZiI<w[#[mUz0=2_~'
        var14 = module0.search(var13, var13)
        assert var14 == 1
        var15 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var16 = module0.search(var15, var15)
        assert var16 == 19
        var17 = 'P1c'
        var18 = '=a1V0,-=IpP\tYI6yF{'
        var19 = module0.search(var17, var18)
        assert var19 == 17
        var20 = '5*:Z{/wY]iy`V_#,.'
        var21 = "|wCIymb'HiL^\\qQ4|L~"
        var22 = module0.search(var20, var21)
        assert var22 == 16
        var23 = '|wdcKu\x0bL%xB ~I'
        var24 = 'z}DPJwn'
        var25 = module0.search(var23, var24)
        assert var25 == 7
        var26 = 'P1c'
        var27 = '=a1V0,-=IpP\tYI6yF{'
        var28 = module0.search(var26, var27)
        assert var28 == 17
        var29 = 'A`cR|~hY.yY*\x0bq'
        var30 = module0.search(var29, var29)
        assert var30 == 13
        var31 = 'P1c'
        var32 = '=a1V0,-=IpP\tYI6yF{'
        var33 = module0.search(var31, var32)
        assert var33 == 17
        var34 = 'UL='
        var35 = '~/n\t\\*k!L'
        var36 = module0.search(var34, var35)
        assert var36 == 9
        var37 = 'P1c'
        var38 = '=a1V0,-=IpP\tYI6yF{'
        var39 = module0.search(var37, var38)
        assert var39 == 17
        var40 = ''
        var41 = 2404.55
        var42 = module0.search(var40, var41)
    except BaseException:
        pass


def test_case_105():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = 'A`cR|~hY.yY*\x0bq'
        var4 = module0.search(var3, var3)
        assert var4 == 13
        var5 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var6 = module0.search(var5, var5)
        assert var6 == 19
        var7 = 'Y\r/'
        var8 = module0.search(var7, var5)
        assert var8 == 19
        var9 = 'P1c'
        var10 = '=a1V0,-=IpP\tYI6yF{'
        var11 = module0.search(var9, var10)
        assert var11 == 17
        var12 = 'UL='
        var13 = '~/n\t\\*k!L'
        var14 = module0.search(var12, var13)
        assert var14 == 9
        var15 = '5*:Z{/wY]iy`V_#,.'
        var16 = "|wCIymb'HiL^\\qQ4|L~"
        var17 = module0.search(var15, var16)
        assert var17 == 16
        var18 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var19 = module0.search(var18, var18)
        assert var19 == 19
        var20 = 'kwM3x(d47O$~#mplZk\\F'
        var21 = 'lY4GQ|J@&;7SL%'
        var22 = module0.search(var20, var21)
        assert var22 == 14
        var23 = 'P1c'
        var24 = '=a1V0,-=IpP\tYI6yF{'
        var25 = module0.search(var23, var24)
        assert var25 == 17
        var26 = '5*:Z{/wY]iy`V_#,.'
        var27 = "|wCIymb'HiL^\\qQ4|L~"
        var28 = module0.search(var26, var27)
        assert var28 == 16
        var29 = '|wdcKu\x0bL%xB ~I'
        var30 = 'z}DPJwn'
        var31 = module0.search(var29, var30)
        assert var31 == 7
        var32 = True
        var33 = module0.search(var20, var32)
    except BaseException:
        pass


def test_case_106():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = 'A`cR|~hY.yY*\x0bq'
        var4 = module0.search(var3, var3)
        assert var4 == 13
        var5 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var6 = module0.search(var5, var5)
        assert var6 == 19
        var7 = 'kwM3x(d47O$~#mplZk\\F'
        var8 = 'lY4GQ|J@&;7SL%'
        var9 = module0.search(var7, var8)
        assert var9 == 14
        var10 = 'P1c'
        var11 = '=a1V0,-=IpP\tYI6yF{'
        var12 = module0.search(var10, var11)
        assert var12 == 17
        var13 = 'jrC,0)q%!Y'
        var14 = module0.search(var11, var13)
        assert var14 == 9
        var15 = True
        var16 = module0.search(var15, var15)
    except BaseException:
        pass


def test_case_107():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = 'jrC,0)q%!Y'
        var4 = module0.search(var1, var3)
        assert var4 == 9
        var5 = 'i;(y='
        var6 = None
        var7 = module0.search(var5, var6)
    except BaseException:
        pass


def test_case_108():
    try:
        var0 = '5*:Z{/wY]iy`V_#,.'
        var1 = "|wCIymb'HiL^\\qQ4|L~"
        var2 = module0.search(var0, var1)
        assert var2 == 16
        var3 = 'P1c'
        var4 = '=a1V0,-=IpP\tYI6yF{'
        var5 = module0.search(var3, var4)
        assert var5 == 17
        var6 = True
        var7 = module0.search(var6, var6)
    except BaseException:
        pass


def test_case_109():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = 'P1c'
        var4 = '=a1V0,-=IpP\tYI6yF{'
        var5 = module0.search(var3, var4)
        assert var5 == 17
        var6 = 'jrC,0)q%!Y'
        var7 = module0.search(var4, var6)
        assert var7 == 9
        var8 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var9 = module0.search(var8, var8)
        assert var9 == 19
        var10 = 'P1c'
        var11 = '=a1V0,-=IpP\tYI6yF{'
        var12 = module0.search(var10, var11)
        assert var12 == 17
        var13 = '5*:Z{/wY]iy`V_#,.'
        var14 = "|wCIymb'HiL^\\qQ4|L~"
        var15 = module0.search(var13, var14)
        assert var15 == 16
        var16 = '|wdcKu\x0bL%xB ~I'
        var17 = 'z}DPJwn'
        var18 = module0.search(var16, var17)
        assert var18 == 7
        var19 = 'P1c'
        var20 = '=a1V0,-=IpP\tYI6yF{'
        var21 = module0.search(var19, var20)
        assert var21 == 17
        var22 = 'A`cR|~hY.yY*\x0bq'
        var23 = module0.search(var22, var22)
        assert var23 == 13
        var24 = 'P1c'
        var25 = '=a1V0,-=IpP\tYI6yF{'
        var26 = module0.search(var24, var25)
        assert var26 == 17
        var27 = 'UL='
        var28 = '~/n\t\\*k!L'
        var29 = module0.search(var27, var28)
        assert var29 == 9
        var30 = '\x0c.Zd\t6\x0c@'
        var31 = 3118
        var32 = module0.search(var30, var31)
    except BaseException:
        pass


def test_case_110():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = '5*:Z{/wY]iy`V_#,.'
        var4 = "|wCIymb'HiL^\\qQ4|L~"
        var5 = module0.search(var3, var4)
        assert var5 == 16
        var6 = '|wdcKu\x0bL%xB ~I'
        var7 = 'z}DPJwn'
        var8 = module0.search(var6, var7)
        assert var8 == 7
        var9 = '"bFZiI<w[#[mUz0=2_~'
        var10 = module0.search(var9, var9)
        assert var10 == 1
        var11 = 'P1c'
        var12 = '=a1V0,-=IpP\tYI6yF{'
        var13 = module0.search(var11, var12)
        assert var13 == 17
        var14 = 'jrC,0)q%!Y'
        var15 = module0.search(var12, var14)
        assert var15 == 9
        var16 = -1605.442699
        var17 = None
        var18 = module0.search(var16, var17)
    except BaseException:
        pass


def test_case_111():
    try:
        var0 = 678
        var1 = '3MbKi36^5D ^/'
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_112():
    try:
        var0 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var1 = module0.search(var0, var0)
        assert var1 == 19
        var2 = 'kwM3x(d47O$~#mplZk\\F'
        var3 = 'lY4GQ|J@&;7SL%'
        var4 = module0.search(var2, var3)
        assert var4 == 14
        var5 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var6 = module0.search(var5, var5)
        assert var6 == 19
        var7 = 'Y\r/'
        var8 = module0.search(var7, var5)
        assert var8 == 19
        var9 = 'P1c'
        var10 = '=a1V0,-=IpP\tYI6yF{'
        var11 = module0.search(var9, var10)
        assert var11 == 17
        var12 = '5*:Z{/wY]iy`V_#,.'
        var13 = "|wCIymb'HiL^\\qQ4|L~"
        var14 = module0.search(var12, var13)
        assert var14 == 16
        var15 = '|wdcKu\x0bL%xB ~I'
        var16 = 'z}DPJwn'
        var17 = module0.search(var15, var16)
        assert var17 == 7
        var18 = 'P1c'
        var19 = '=a1V0,-=IpP\tYI6yF{'
        var20 = module0.search(var18, var19)
        assert var20 == 17
        var21 = 'P1c'
        var22 = '=a1V0,-=IpP\tYI6yF{'
        var23 = module0.search(var21, var22)
        assert var23 == 17
        var24 = 'jrC,0)q%!Y'
        var25 = module0.search(var22, var24)
        assert var25 == 9
        var26 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var27 = module0.search(var26, var26)
        assert var27 == 19
        var28 = 'P1c'
        var29 = '=a1V0,-=IpP\tYI6yF{'
        var30 = module0.search(var28, var29)
        assert var30 == 17
        var31 = 'UL='
        var32 = '~/n\t\\*k!L'
        var33 = module0.search(var31, var32)
        assert var33 == 9
        var34 = 897
        var35 = 1436.937
        var36 = module0.search(var34, var35)
    except BaseException:
        pass


def test_case_113():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = 'UL='
        var4 = '~/n\t\\*k!L'
        var5 = module0.search(var3, var4)
        assert var5 == 9
        var6 = '"bFZiI<w[#[mUz0=2_~'
        var7 = module0.search(var6, var6)
        assert var7 == 1
        var8 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var9 = module0.search(var8, var8)
        assert var9 == 19
        var10 = 'P1c'
        var11 = '=a1V0,-=IpP\tYI6yF{'
        var12 = module0.search(var10, var11)
        assert var12 == 17
        var13 = '5*:Z{/wY]iy`V_#,.'
        var14 = "|wCIymb'HiL^\\qQ4|L~"
        var15 = module0.search(var13, var14)
        assert var15 == 16
        var16 = '|wdcKu\x0bL%xB ~I'
        var17 = 'z}DPJwn'
        var18 = module0.search(var16, var17)
        assert var18 == 7
        var19 = 'P1c'
        var20 = '=a1V0,-=IpP\tYI6yF{'
        var21 = module0.search(var19, var20)
        assert var21 == 17
        var22 = 'P1c'
        var23 = '=a1V0,-=IpP\tYI6yF{'
        var24 = module0.search(var22, var23)
        assert var24 == 17
        var25 = 'A`cR|~hY.yY*\x0bq'
        var26 = module0.search(var25, var25)
        assert var26 == 13
        var27 = 1364
        var28 = None
        var29 = module0.search(var27, var28)
    except BaseException:
        pass


def test_case_114():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = 'P1c'
        var4 = '=a1V0,-=IpP\tYI6yF{'
        var5 = module0.search(var3, var4)
        assert var5 == 17
        var6 = 'A`cR|~hY.yY*\x0bq'
        var7 = module0.search(var6, var6)
        assert var7 == 13
        var8 = 'P1c'
        var9 = '=a1V0,-=IpP\tYI6yF{'
        var10 = module0.search(var8, var9)
        assert var10 == 17
        var11 = 'UL='
        var12 = '~/n\t\\*k!L'
        var13 = module0.search(var11, var12)
        assert var13 == 9
        var14 = 'P1c'
        var15 = '=a1V0,-=IpP\tYI6yF{'
        var16 = module0.search(var14, var15)
        assert var16 == 17
        var17 = '5*:Z{/wY]iy`V_#,.'
        var18 = "|wCIymb'HiL^\\qQ4|L~"
        var19 = module0.search(var17, var18)
        assert var19 == 16
        var20 = '|wdcKu\x0bL%xB ~I'
        var21 = 'z}DPJwn'
        var22 = module0.search(var20, var21)
        assert var22 == 7
        var23 = '5*:Z{/wY]iy`V_#,.'
        var24 = "|wCIymb'HiL^\\qQ4|L~"
        var25 = module0.search(var23, var24)
        assert var25 == 16
        var26 = '"bFZiI<w[#[mUz0=2_~'
        var27 = module0.search(var26, var26)
        assert var27 == 1
        var28 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var29 = module0.search(var28, var28)
        assert var29 == 19
        var30 = 'Y\r/'
        var31 = module0.search(var30, var28)
        assert var31 == 19
        var32 = 'P1c'
        var33 = '=a1V0,-=IpP\tYI6yF{'
        var34 = module0.search(var32, var33)
        assert var34 == 17
        var35 = 'jrC,0)q%!Y'
        var36 = module0.search(var33, var35)
        assert var36 == 9
        var37 = 181
        var38 = module0.search(var37, var30)
    except BaseException:
        pass


def test_case_115():
    try:
        var0 = None
        var1 = module0.search(var0, var0)
    except BaseException:
        pass


def test_case_116():
    try:
        var0 = '5*:Z{/wY]iy`V_#,.'
        var1 = "|wCIymb'HiL^\\qQ4|L~"
        var2 = module0.search(var0, var1)
        assert var2 == 16
        var3 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var4 = module0.search(var3, var3)
        assert var4 == 19
        var5 = 'Y\r/'
        var6 = module0.search(var5, var3)
        assert var6 == 19
        var7 = 'P1c'
        var8 = '=a1V0,-=IpP\tYI6yF{'
        var9 = module0.search(var7, var8)
        assert var9 == 17
        var10 = 'A`cR|~hY.yY*\x0bq'
        var11 = module0.search(var10, var10)
        assert var11 == 13
        var12 = '"bFZiI<w[#[mUz0=2_~'
        var13 = module0.search(var12, var12)
        assert var13 == 1
        var14 = None
        var15 = 5967
        var16 = module0.search(var14, var15)
    except BaseException:
        pass


def test_case_117():
    try:
        var0 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var1 = module0.search(var0, var0)
        assert var1 == 19
        var2 = 'Y\r/'
        var3 = module0.search(var2, var0)
        assert var3 == 19
        var4 = '5*:Z{/wY]iy`V_#,.'
        var5 = "|wCIymb'HiL^\\qQ4|L~"
        var6 = module0.search(var4, var5)
        assert var6 == 16
        var7 = 'P1c'
        var8 = '=a1V0,-=IpP\tYI6yF{'
        var9 = module0.search(var7, var8)
        assert var9 == 17
        var10 = '5*:Z{/wY]iy`V_#,.'
        var11 = "|wCIymb'HiL^\\qQ4|L~"
        var12 = module0.search(var10, var11)
        assert var12 == 16
        var13 = '|wdcKu\x0bL%xB ~I'
        var14 = 'z}DPJwn'
        var15 = module0.search(var13, var14)
        assert var15 == 7
        var16 = 'P1c'
        var17 = '=a1V0,-=IpP\tYI6yF{'
        var18 = module0.search(var16, var17)
        assert var18 == 17
        var19 = 'UL='
        var20 = '~/n\t\\*k!L'
        var21 = module0.search(var19, var20)
        assert var21 == 9
        var22 = 328.7
        var23 = -38
        var24 = module0.search(var22, var23)
    except BaseException:
        pass


def test_case_118():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = '5*:Z{/wY]iy`V_#,.'
        var4 = "|wCIymb'HiL^\\qQ4|L~"
        var5 = module0.search(var3, var4)
        assert var5 == 16
        var6 = 'P1c'
        var7 = '=a1V0,-=IpP\tYI6yF{'
        var8 = module0.search(var6, var7)
        assert var8 == 17
        var9 = 'UL='
        var10 = '~/n\t\\*k!L'
        var11 = module0.search(var9, var10)
        assert var11 == 9
        var12 = '"bFZiI<w[#[mUz0=2_~'
        var13 = module0.search(var12, var12)
        assert var13 == 1
        var14 = 'P1c'
        var15 = '=a1V0,-=IpP\tYI6yF{'
        var16 = module0.search(var14, var15)
        assert var16 == 17
        var17 = 'jrC,0)q%!Y'
        var18 = module0.search(var15, var17)
        assert var18 == 9
        var19 = 1207
        var20 = 'gXP5'
        var21 = module0.search(var19, var20)
    except BaseException:
        pass


def test_case_119():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = 'A`cR|~hY.yY*\x0bq'
        var4 = module0.search(var3, var3)
        assert var4 == 13
        var5 = 'P1c'
        var6 = '=a1V0,-=IpP\tYI6yF{'
        var7 = module0.search(var5, var6)
        assert var7 == 17
        var8 = '"bFZiI<w[#[mUz0=2_~'
        var9 = module0.search(var8, var8)
        assert var9 == 1
        var10 = 'P1c'
        var11 = '=a1V0,-=IpP\tYI6yF{'
        var12 = module0.search(var10, var11)
        assert var12 == 17
        var13 = 'jrC,0)q%!Y'
        var14 = module0.search(var11, var13)
        assert var14 == 9
        var15 = '"t{uk\'MNBg.nQ&<vsJ'
        var16 = 1843.9852
        var17 = module0.search(var15, var16)
    except BaseException:
        pass


def test_case_120():
    try:
        var0 = '"bFZiI<w[#[mUz0=2_~'
        var1 = module0.search(var0, var0)
        assert var1 == 1
        var2 = 'P1c'
        var3 = '=a1V0,-=IpP\tYI6yF{'
        var4 = module0.search(var2, var3)
        assert var4 == 17
        var5 = 'A`cR|~hY.yY*\x0bq'
        var6 = module0.search(var5, var5)
        assert var6 == 13
        var7 = 'P1c'
        var8 = '=a1V0,-=IpP\tYI6yF{'
        var9 = module0.search(var7, var8)
        assert var9 == 17
        var10 = 'P1c'
        var11 = '=a1V0,-=IpP\tYI6yF{'
        var12 = module0.search(var10, var11)
        assert var12 == 17
        var13 = '5*:Z{/wY]iy`V_#,.'
        var14 = "|wCIymb'HiL^\\qQ4|L~"
        var15 = module0.search(var13, var14)
        assert var15 == 16
        var16 = '|wdcKu\x0bL%xB ~I'
        var17 = 'z}DPJwn'
        var18 = module0.search(var16, var17)
        assert var18 == 7
        var19 = 'P1c'
        var20 = '=a1V0,-=IpP\tYI6yF{'
        var21 = module0.search(var19, var20)
        assert var21 == 17
        var22 = 'jrC,0)q%!Y'
        var23 = module0.search(var20, var22)
        assert var23 == 9
        var24 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var25 = module0.search(var24, var24)
        assert var25 == 19
        var26 = 'kwM3x(d47O$~#mplZk\\F'
        var27 = 'lY4GQ|J@&;7SL%'
        var28 = module0.search(var26, var27)
        assert var28 == 14
        var29 = False
        var30 = 'I\x0c7qkmP\x0cyg!65Y'
        var31 = module0.search(var29, var30)
    except BaseException:
        pass


def test_case_121():
    try:
        var0 = '5*:Z{/wY]iy`V_#,.'
        var1 = "|wCIymb'HiL^\\qQ4|L~"
        var2 = module0.search(var0, var1)
        assert var2 == 16
        var3 = 'P1c'
        var4 = '=a1V0,-=IpP\tYI6yF{'
        var5 = module0.search(var3, var4)
        assert var5 == 17
        var6 = 'A`cR|~hY.yY*\x0bq'
        var7 = module0.search(var6, var6)
        assert var7 == 13
        var8 = 'P1c'
        var9 = '=a1V0,-=IpP\tYI6yF{'
        var10 = module0.search(var8, var9)
        assert var10 == 17
        var11 = 'UL='
        var12 = '~/n\t\\*k!L'
        var13 = module0.search(var11, var12)
        assert var13 == 9
        var14 = 'P1c'
        var15 = '=a1V0,-=IpP\tYI6yF{'
        var16 = module0.search(var14, var15)
        assert var16 == 17
        var17 = '5*:Z{/wY]iy`V_#,.'
        var18 = "|wCIymb'HiL^\\qQ4|L~"
        var19 = module0.search(var17, var18)
        assert var19 == 16
        var20 = '|wdcKu\x0bL%xB ~I'
        var21 = 'z}DPJwn'
        var22 = module0.search(var20, var21)
        assert var22 == 7
        var23 = -2612
        var24 = module0.search(var23, var23)
    except BaseException:
        pass


def test_case_122():
    try:
        var0 = '5*:Z{/wY]iy`V_#,.'
        var1 = "|wCIymb'HiL^\\qQ4|L~"
        var2 = module0.search(var0, var1)
        assert var2 == 16
        var3 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var4 = module0.search(var3, var3)
        assert var4 == 19
        var5 = 'kwM3x(d47O$~#mplZk\\F'
        var6 = 'lY4GQ|J@&;7SL%'
        var7 = module0.search(var5, var6)
        assert var7 == 14
        var8 = 'P1c'
        var9 = '=a1V0,-=IpP\tYI6yF{'
        var10 = module0.search(var8, var9)
        assert var10 == 17
        var11 = 'jrC,0)q%!Y'
        var12 = module0.search(var9, var11)
        assert var12 == 9
        var13 = 'P1c'
        var14 = '=a1V0,-=IpP\tYI6yF{'
        var15 = module0.search(var13, var14)
        assert var15 == 17
        var16 = 'UL='
        var17 = '~/n\t\\*k!L'
        var18 = module0.search(var16, var17)
        assert var18 == 9
        var19 = "-bb=EM:!'iLTD#Y7"
        var20 = -736
        var21 = module0.search(var19, var20)
    except BaseException:
        pass


def test_case_123():
    try:
        var0 = '5*:Z{/wY]iy`V_#,.'
        var1 = "|wCIymb'HiL^\\qQ4|L~"
        var2 = module0.search(var0, var1)
        assert var2 == 16
        var3 = '"bFZiI<w[#[mUz0=2_~'
        var4 = module0.search(var3, var3)
        assert var4 == 1
        var5 = 'P1c'
        var6 = '=a1V0,-=IpP\tYI6yF{'
        var7 = module0.search(var5, var6)
        assert var7 == 17
        var8 = '5*:Z{/wY]iy`V_#,.'
        var9 = "|wCIymb'HiL^\\qQ4|L~"
        var10 = module0.search(var8, var9)
        assert var10 == 16
        var11 = '|wdcKu\x0bL%xB ~I'
        var12 = 'z}DPJwn'
        var13 = module0.search(var11, var12)
        assert var13 == 7
        var14 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var15 = module0.search(var14, var14)
        assert var15 == 19
        var16 = 'kwM3x(d47O$~#mplZk\\F'
        var17 = 'lY4GQ|J@&;7SL%'
        var18 = module0.search(var16, var17)
        assert var18 == 14
        var19 = 'P1c'
        var20 = '=a1V0,-=IpP\tYI6yF{'
        var21 = module0.search(var19, var20)
        assert var21 == 17
        var22 = False
        var23 = module0.search(var22, var19)
    except BaseException:
        pass


def test_case_124():
    try:
        var0 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var1 = module0.search(var0, var0)
        assert var1 == 19
        var2 = 'Y\r/'
        var3 = module0.search(var2, var0)
        assert var3 == 19
        var4 = "dS'["
        var5 = None
        var6 = module0.search(var4, var5)
    except BaseException:
        pass


def test_case_125():
    try:
        var0 = 'S1;F]pfj\r[CIgHpP.\t>x'
        var1 = module0.search(var0, var0)
        assert var1 == 19
        var2 = 'Y\r/'
        var3 = module0.search(var2, var0)
        assert var3 == 19
        var4 = 'P1c'
        var5 = '=a1V0,-=IpP\tYI6yF{'
        var6 = module0.search(var4, var5)
        assert var6 == 17
        var7 = '5*:Z{/wY]iy`V_#,.'
        var8 = "|wCIymb'HiL^\\qQ4|L~"
        var9 = module0.search(var7, var8)
        assert var9 == 16
        var10 = '|wdcKu\x0bL%xB ~I'
        var11 = 'z}DPJwn'
        var12 = module0.search(var10, var11)
        assert var12 == 7
        var13 = 'P1c'
        var14 = '=a1V0,-=IpP\tYI6yF{'
        var15 = module0.search(var13, var14)
        assert var15 == 17
        var16 = '5*:Z{/wY]iy`V_#,.'
        var17 = "|wCIymb'HiL^\\qQ4|L~"
        var18 = module0.search(var16, var17)
        assert var18 == 16
        var19 = 'P1c'
        var20 = '=a1V0,-=IpP\tYI6yF{'
        var21 = module0.search(var19, var20)
        assert var21 == 17
        var22 = 'jrC,0)q%!Y'
        var23 = module0.search(var20, var22)
        assert var23 == 9
        var24 = 'P1c'
        var25 = '=a1V0,-=IpP\tYI6yF{'
        var26 = module0.search(var24, var25)
        assert var26 == 17
        var27 = 'A`cR|~hY.yY*\x0bq'
        var28 = module0.search(var27, var27)
        assert var28 == 13
        var29 = '"bFZiI<w[#[mUz0=2_~'
        var30 = module0.search(var29, var29)
        assert var30 == 1
        var31 = -3929
        var32 = module0.search(var19, var31)
    except BaseException:
        pass


def test_case_126():
    try:
        var0 = '5*:Z{/wY]iy`V_#,.'
        var1 = "|wCIymb'HiL^\\qQ4|L~"
        var2 = module0.search(var0, var1)
        assert var2 == 16
        var3 = 'P1c'
        var4 = '=a1V0,-=IpP\tYI6yF{'
        var5 = module0.search(var3, var4)
        assert var5 == 17
        var6 = 3912.96
        var7 = 'I=0'
        var8 = module0.search(var6, var7)
    except BaseException:
        pass


def test_case_127():
    try:
        var0 = 'P1c'
        var1 = '=a1V0,-=IpP\tYI6yF{'
        var2 = module0.search(var0, var1)
        assert var2 == 17
        var3 = 'UL='
        var4 = '~/n\t\\*k!L'
        var5 = module0.search(var3, var4)
        assert var5 == 9
        var6 = '5*:Z{/wY]iy`V_#,.'
        var7 = "|wCIymb'HiL^\\qQ4|L~"
        var8 = module0.search(var6, var7)
        assert var8 == 16
        var9 = True
        var10 = 'gfEFOf3k9B$DUSx6E3'
        var11 = module0.search(var9, var10)
    except BaseException:
        pass
