# Automatically generated by Pynguin.
import caso_covertura_008 as module0


def test_case_0():
    var0 = 'k=r`-h)%I'
    var1 = '>*b&B8ZqC'
    var2 = module0.search(var0, var1)
    assert var2 == 7


def test_case_1():
    var0 = 'k=r`-h)%I'
    var1 = '>*b&B8ZqC'
    var2 = module0.search(var0, var1)
    assert var2 == 7
    var3 = 'K|Af8T ?&6XJ B'
    var4 = 'boYNF&dRL*>Y'
    var5 = module0.search(var3, var4)
    assert var5 == 0


def test_case_2():
    var0 = 'k=r`-h)%I'
    var1 = '>*b&B8ZqC'
    var2 = module0.search(var0, var1)
    assert var2 == 7
    var3 = 'K|Af8T ?&6XJ B'
    var4 = 'boYNF&dRL*>Y'
    var5 = module0.search(var3, var4)
    assert var5 == 0
    var6 = 'k=r`-h)%I'
    var7 = '>*b&B8ZqC'
    var8 = module0.search(var6, var7)
    assert var8 == 7
    var9 = ';S-op`\td`'
    var10 = module0.search(var6, var9)
    assert var10 == 3


def test_case_3():
    var0 = 'k=r`-h)%I'
    var1 = '>*b&B8ZqC'
    var2 = module0.search(var0, var1)
    assert var2 == 7
    var3 = 'K|Af8T ?&6XJ B'
    var4 = 'boYNF&dRL*>Y'
    var5 = module0.search(var3, var4)
    assert var5 == 0
    var6 = True
    var7 = ''
    var8 = module0.search(var6, var7)
    assert var8 == 0
