# Automatically generated by Pynguin.
import caso_covertura_176 as module0


def test_case_0():
    var0 = "'Pc@?.*y_TSb"
    var1 = module0.remove_extras(var0)
    assert var1 is not None


def test_case_1():
    var0 = 'l\n'
    var1 = module0.remove_extras(var0)
    assert var1 is not None


def test_case_2():
    var0 = 'l\n'
    var1 = module0.remove_extras(var0)
    assert var1 is not None
    var2 = "'Pc@?.*y_TSb"
    var3 = module0.remove_extras(var2)
    assert var3 is not None
    var4 = ']ifhpZdYeE*m'
    var5 = module0.remove_extras(var4)
    assert var5 is not None


def test_case_3():
    var0 = "'Pc@?.*y_TSb"
    var1 = module0.remove_extras(var0)
    assert var1 is not None
    var2 = 'h]MX9d\x0cBUfOl4w>'
    var3 = module0.remove_extras(var2)
    assert var3 is not None


def test_case_4():
    var0 = 'slU{'
    var1 = module0.remove_extras(var0)
    assert var1 is not None


def test_case_5():
    var0 = "'Pc@?.*y_TSb"
    var1 = module0.remove_extras(var0)
    assert var1 is not None
    var2 = "'Pc@?.*y_TSb"
    var3 = module0.remove_extras(var2)
    assert var3 is not None
    var4 = 'h]MX9d\x0cBUfOl4w>'
    var5 = module0.remove_extras(var4)
    assert var5 is not None
    var6 = 'slU{'
    var7 = module0.remove_extras(var6)
    assert var7 is not None
    var8 = 'l\n'
    var9 = module0.remove_extras(var8)
    assert var9 is not None
    var10 = "_/'"
    var11 = module0.remove_extras(var10)
    assert var11 is not None


def test_case_6():
    var0 = 'slU{'
    var1 = module0.remove_extras(var0)
    assert var1 is not None
    var2 = "'Pc@?.*y_TSb"
    var3 = module0.remove_extras(var2)
    assert var3 is not None
    var4 = "9(\x0c~V4'U[9^_$Dn<8Srt"
    var5 = module0.remove_extras(var4)
    assert var5 is not None


def test_case_7():
    var0 = "'Pc@?.*y_TSb"
    var1 = module0.remove_extras(var0)
    assert var1 is not None
    var2 = 'l\n'
    var3 = module0.remove_extras(var2)
    assert var3 is not None
    var4 = "'Pc@?.*y_TSb"
    var5 = module0.remove_extras(var4)
    assert var5 is not None
    var6 = ']ifhpZdYeE*m'
    var7 = module0.remove_extras(var6)
    assert var7 is not None
    var8 = "'Pc@?.*y_TSb"
    var9 = module0.remove_extras(var8)
    assert var9 is not None
    var10 = 'h]MX9d\x0cBUfOl4w>'
    var11 = module0.remove_extras(var10)
    assert var11 is not None
    var12 = 'slU{'
    var13 = module0.remove_extras(var12)
    assert var13 is not None
    var14 = 'slU{'
    var15 = module0.remove_extras(var14)
    assert var15 is not None
    var16 = "'Pc@?.*y_TSb"
    var17 = module0.remove_extras(var16)
    assert var17 is not None
    var18 = "9(\x0c~V4'U[9^_$Dn<8Srt"
    var19 = module0.remove_extras(var18)
    assert var19 is not None
    var20 = "p8N3*]_R}'}f\r"
    var21 = module0.remove_extras(var20)
    assert var21 is not None


def test_case_8():
    var0 = 'slU{'
    var1 = module0.remove_extras(var0)
    assert var1 is not None
    var2 = 'l\n'
    var3 = module0.remove_extras(var2)
    assert var3 is not None
    var4 = "'Pc@?.*y_TSb"
    var5 = module0.remove_extras(var4)
    assert var5 is not None
    var6 = ']ifhpZdYeE*m'
    var7 = module0.remove_extras(var6)
    assert var7 is not None
    var8 = 'slU{'
    var9 = module0.remove_extras(var8)
    assert var9 is not None
    var10 = "'Pc@?.*y_TSb"
    var11 = module0.remove_extras(var10)
    assert var11 is not None
    var12 = "9(\x0c~V4'U[9^_$Dn<8Srt"
    var13 = module0.remove_extras(var12)
    assert var13 is not None
    var14 = 'EJoA\ni[w'
    var15 = module0.remove_extras(var14)
    assert var15 is not None


def test_case_9():
    var0 = 'slU{'
    var1 = module0.remove_extras(var0)
    assert var1 is not None
    var2 = module0.remove_extras(var0)
    assert var2 is not None


def test_case_10():
    var0 = 'slU{'
    var1 = module0.remove_extras(var0)
    assert var1 is not None
    var2 = module0.remove_extras(var0)
    assert var2 is not None
    var3 = 'slU{'
    var4 = module0.remove_extras(var3)
    assert var4 is not None
    var5 = 'l\n'
    var6 = module0.remove_extras(var5)
    assert var6 is not None
    var7 = "'Pc@?.*y_TSb"
    var8 = module0.remove_extras(var7)
    assert var8 is not None
    var9 = ']ifhpZdYeE*m'
    var10 = module0.remove_extras(var9)
    assert var10 is not None
    var11 = 'l\n'
    var12 = module0.remove_extras(var11)
    assert var12 is not None
    var13 = 'pb5'
    var14 = module0.remove_extras(var13)
    assert var14 is not None


def test_case_11():
    var0 = 'l\n'
    var1 = module0.remove_extras(var0)
    assert var1 is not None
    var2 = "'Pc@?.*y_TSb"
    var3 = module0.remove_extras(var2)
    assert var3 is not None
    var4 = 'h]MX9d\x0cBUfOl4w>'
    var5 = module0.remove_extras(var4)
    assert var5 is not None
    var6 = "'Pc@?.*y_TSb"
    var7 = module0.remove_extras(var6)
    assert var7 is not None
    var8 = 'slU{'
    var9 = module0.remove_extras(var8)
    assert var9 is not None
    var10 = 'slU{'
    var11 = module0.remove_extras(var10)
    assert var11 is not None
    var12 = "'Pc@?.*y_TSb"
    var13 = module0.remove_extras(var12)
    assert var13 is not None
    var14 = "9(\x0c~V4'U[9^_$Dn<8Srt"
    var15 = module0.remove_extras(var14)
    assert var15 is not None
    var16 = 'slU{'
    var17 = module0.remove_extras(var16)
    assert var17 is not None
    var18 = module0.remove_extras(var16)
    assert var18 is not None
    var19 = 'l\n'
    var20 = module0.remove_extras(var19)
    assert var20 is not None
    var21 = "'Pc@?.*y_TSb"
    var22 = module0.remove_extras(var21)
    assert var22 is not None
    var23 = ']ifhpZdYeE*m'
    var24 = module0.remove_extras(var23)
    assert var24 is not None
    var25 = 'kX/2Eg,&tFn04^['
    var26 = module0.remove_extras(var25)
    assert var26 is not None


def test_case_12():
    var0 = "'Pc@?.*y_TSb"
    var1 = module0.remove_extras(var0)
    assert var1 is not None
    var2 = 'slU{'
    var3 = module0.remove_extras(var2)
    assert var3 is not None
    var4 = module0.remove_extras(var2)
    assert var4 is not None
    var5 = 'G1\'vwZ\n2"0&~`'
    var6 = module0.remove_extras(var5)
    assert var6 is not None


def test_case_13():
    var0 = "'Pc@?.*y_TSb"
    var1 = module0.remove_extras(var0)
    assert var1 is not None
    var2 = 'slU{'
    var3 = module0.remove_extras(var2)
    assert var3 is not None
    var4 = module0.remove_extras(var2)
    assert var4 is not None
    var5 = 'G1\'vwZ\n2"0&~`'
    var6 = module0.remove_extras(var5)
    assert var6 is not None
    var7 = 'l\n'
    var8 = module0.remove_extras(var7)
    assert var8 is not None
    var9 = "'Pc@?.*y_TSb"
    var10 = module0.remove_extras(var9)
    assert var10 is not None
    var11 = 'h]MX9d\x0cBUfOl4w>'
    var12 = module0.remove_extras(var11)
    assert var12 is not None
    var13 = 'slU{'
    var14 = module0.remove_extras(var13)
    assert var14 is not None
    var15 = "'Pc@?.*y_TSb"
    var16 = module0.remove_extras(var15)
    assert var16 is not None
    var17 = "9(\x0c~V4'U[9^_$Dn<8Srt"
    var18 = module0.remove_extras(var17)
    assert var18 is not None
    var19 = 'slU{'
    var20 = module0.remove_extras(var19)
    assert var20 is not None
    var21 = 'l\n'
    var22 = module0.remove_extras(var21)
    assert var22 is not None
    var23 = "'Pc@?.*y_TSb"
    var24 = module0.remove_extras(var23)
    assert var24 is not None
    var25 = ']ifhpZdYeE*m'
    var26 = module0.remove_extras(var25)
    assert var26 is not None
    var27 = 'slU{'
    var28 = module0.remove_extras(var27)
    assert var28 is not None
    var29 = module0.remove_extras(var27)
    assert var29 is not None
    var30 = "'Pc@?.*y_TSb"
    var31 = module0.remove_extras(var30)
    assert var31 is not None
    var32 = 'vR-JJV!\x0c}~}c=`pdH|;'
    var33 = module0.remove_extras(var32)
    assert var33 is not None


def test_case_14():
    var0 = 'slU{'
    var1 = module0.remove_extras(var0)
    assert var1 is not None
    var2 = "'Pc@?.*y_TSb"
    var3 = module0.remove_extras(var2)
    assert var3 is not None
    var4 = "9(\x0c~V4'U[9^_$Dn<8Srt"
    var5 = module0.remove_extras(var4)
    assert var5 is not None
    var6 = 'KY|]M\x0bdR1lErK*ra'
    var7 = module0.remove_extras(var6)
    assert var7 is not None


def test_case_15():
    var0 = "'Pc@?.*y_TSb"
    var1 = module0.remove_extras(var0)
    assert var1 is not None
    var2 = 'slU{'
    var3 = module0.remove_extras(var2)
    assert var3 is not None
    var4 = module0.remove_extras(var2)
    assert var4 is not None
    var5 = 'G1\'vwZ\n2"0&~`'
    var6 = module0.remove_extras(var5)
    assert var6 is not None
    var7 = 'slU{'
    var8 = module0.remove_extras(var7)
    assert var8 is not None
    var9 = module0.remove_extras(var7)
    assert var9 is not None
    var10 = 'slU{'
    var11 = module0.remove_extras(var10)
    assert var11 is not None
    var12 = "'Pc@?.*y_TSb"
    var13 = module0.remove_extras(var12)
    assert var13 is not None
    var14 = "'Pc@?.*y_TSb"
    var15 = module0.remove_extras(var14)
    assert var15 is not None
    var16 = 'h]MX9d\x0cBUfOl4w>'
    var17 = module0.remove_extras(var16)
    assert var17 is not None
    var18 = 'slU{'
    var19 = module0.remove_extras(var18)
    assert var19 is not None
    var20 = "'Pc@?.*y_TSb"
    var21 = module0.remove_extras(var20)
    assert var21 is not None
    var22 = "9(\x0c~V4'U[9^_$Dn<8Srt"
    var23 = module0.remove_extras(var22)
    assert var23 is not None
    var24 = 'l\n'
    var25 = module0.remove_extras(var24)
    assert var25 is not None
    var26 = 'D$JgS<qXI'
    var27 = module0.remove_extras(var26)
    assert var27 is not None


def test_case_16():
    var0 = 'l\n'
    var1 = module0.remove_extras(var0)
    assert var1 is not None
    var2 = "'Pc@?.*y_TSb"
    var3 = module0.remove_extras(var2)
    assert var3 is not None
    var4 = ']ifhpZdYeE*m'
    var5 = module0.remove_extras(var4)
    assert var5 is not None
    var6 = "'Pc@?.*y_TSb"
    var7 = module0.remove_extras(var6)
    assert var7 is not None
    var8 = 'slU{'
    var9 = module0.remove_extras(var8)
    assert var9 is not None
    var10 = module0.remove_extras(var8)
    assert var10 is not None
    var11 = 'G1\'vwZ\n2"0&~`'
    var12 = module0.remove_extras(var11)
    assert var12 is not None
    var13 = "'Pc@?.*y_TSb"
    var14 = module0.remove_extras(var13)
    assert var14 is not None
    var15 = 'h]MX9d\x0cBUfOl4w>'
    var16 = module0.remove_extras(var15)
    assert var16 is not None
    var17 = module0.remove_extras(var4)
    assert var17 is not None


def test_case_17():
    var0 = 'slU{'
    var1 = module0.remove_extras(var0)
    assert var1 is not None
    var2 = "'Pc@?.*y_TSb"
    var3 = module0.remove_extras(var2)
    assert var3 is not None
    var4 = "9(\x0c~V4'U[9^_$Dn<8Srt"
    var5 = module0.remove_extras(var4)
    assert var5 is not None
    var6 = 'slU{'
    var7 = module0.remove_extras(var6)
    assert var7 is not None
    var8 = module0.remove_extras(var6)
    assert var8 is not None
    var9 = 'l\n'
    var10 = module0.remove_extras(var9)
    assert var10 is not None
    var11 = "'Pc@?.*y_TSb"
    var12 = module0.remove_extras(var11)
    assert var12 is not None
    var13 = ']ifhpZdYeE*m'
    var14 = module0.remove_extras(var13)
    assert var14 is not None
    var15 = 'TZck|C-~c"\r,<m5'
    var16 = module0.remove_extras(var15)
    assert var16 is not None


def test_case_18():
    var0 = 'slU{'
    var1 = module0.remove_extras(var0)
    assert var1 is not None
    var2 = "'Pc@?.*y_TSb"
    var3 = module0.remove_extras(var2)
    assert var3 is not None
    var4 = 'l\n'
    var5 = module0.remove_extras(var4)
    assert var5 is not None
    var6 = "'Pc@?.*y_TSb"
    var7 = module0.remove_extras(var6)
    assert var7 is not None
    var8 = 'h]MX9d\x0cBUfOl4w>'
    var9 = module0.remove_extras(var8)
    assert var9 is not None
    var10 = 'slU{'
    var11 = module0.remove_extras(var10)
    assert var11 is not None
    var12 = "'Pc@?.*y_TSb"
    var13 = module0.remove_extras(var12)
    assert var13 is not None
    var14 = "9(\x0c~V4'U[9^_$Dn<8Srt"
    var15 = module0.remove_extras(var14)
    assert var15 is not None
    var16 = 'KY|]M\x0bdR1lErK*ra'
    var17 = module0.remove_extras(var16)
    assert var17 is not None
    var18 = 'l\n'
    var19 = module0.remove_extras(var18)
    assert var19 is not None
    var20 = "'Pc@?.*y_TSb"
    var21 = module0.remove_extras(var20)
    assert var21 is not None
    var22 = ']ifhpZdYeE*m'
    var23 = module0.remove_extras(var22)
    assert var23 is not None
    var24 = 'slU{'
    var25 = module0.remove_extras(var24)
    assert var25 is not None
    var26 = module0.remove_extras(var24)
    assert var26 is not None
    var27 = "'Pc@?.*y_TSb"
    var28 = module0.remove_extras(var27)
    assert var28 is not None
    var29 = 'slU{'
    var30 = module0.remove_extras(var29)
    assert var30 is not None
    var31 = module0.remove_extras(var29)
    assert var31 is not None
    var32 = 'G1\'vwZ\n2"0&~`'
    var33 = module0.remove_extras(var32)
    assert var33 is not None
    var34 = 'slU{'
    var35 = module0.remove_extras(var34)
    assert var35 is not None
    var36 = "'Pc@?.*y_TSb"
    var37 = module0.remove_extras(var36)
    assert var37 is not None
    var38 = "9(\x0c~V4'U[9^_$Dn<8Srt"
    var39 = module0.remove_extras(var38)
    assert var39 is not None
    var40 = module0.remove_extras(var18)
    assert var40 is not None


def test_case_19():
    var0 = 'slU{'
    var1 = module0.remove_extras(var0)
    assert var1 is not None
    var2 = "'Pc@?.*y_TSb"
    var3 = module0.remove_extras(var2)
    assert var3 is not None
    var4 = 'slU{'
    var5 = module0.remove_extras(var4)
    assert var5 is not None
    var6 = module0.remove_extras(var4)
    assert var6 is not None
    var7 = 'G1\'vwZ\n2"0&~`'
    var8 = module0.remove_extras(var7)
    assert var8 is not None
    var9 = "'Pc@?.*y_TSb"
    var10 = module0.remove_extras(var9)
    assert var10 is not None
    var11 = 'h]MX9d\x0cBUfOl4w>'
    var12 = module0.remove_extras(var11)
    assert var12 is not None
    var13 = 'l\n'
    var14 = module0.remove_extras(var13)
    assert var14 is not None
    var15 = "'Pc@?.*y_TSb"
    var16 = module0.remove_extras(var15)
    assert var16 is not None
    var17 = ']ifhpZdYeE*m'
    var18 = module0.remove_extras(var17)
    assert var18 is not None
    var19 = 'slU{'
    var20 = module0.remove_extras(var19)
    assert var20 is not None
    var21 = "'Pc@?.*y_TSb"
    var22 = module0.remove_extras(var21)
    assert var22 is not None
    var23 = "9(\x0c~V4'U[9^_$Dn<8Srt"
    var24 = module0.remove_extras(var23)
    assert var24 is not None
    var25 = 'KY|]M\x0bdR1lErK*ra'
    var26 = module0.remove_extras(var25)
    assert var26 is not None
    var27 = module0.remove_extras(var21)
    assert var27 is not None


def test_case_20():
    var0 = 'us'
    var1 = module0.remove_extras(var0)
    assert var1 is not None


def test_case_21():
    var0 = 'slU{'
    var1 = module0.remove_extras(var0)
    assert var1 is not None
    var2 = "'Pc@?.*y_TSb"
    var3 = module0.remove_extras(var2)
    assert var3 is not None
    var4 = "9(\x0c~V4'U[9^_$Dn<8Srt"
    var5 = module0.remove_extras(var4)
    assert var5 is not None
    var6 = 'KY|]M\x0bdR1lErK*ra'
    var7 = module0.remove_extras(var6)
    assert var7 is not None
    var8 = "'Pc@?.*y_TSb"
    var9 = module0.remove_extras(var8)
    assert var9 is not None
    var10 = 'h]MX9d\x0cBUfOl4w>'
    var11 = module0.remove_extras(var10)
    assert var11 is not None
    var12 = 'slU{'
    var13 = module0.remove_extras(var12)
    assert var13 is not None
    var14 = "'Pc@?.*y_TSb"
    var15 = module0.remove_extras(var14)
    assert var15 is not None
    var16 = "9(\x0c~V4'U[9^_$Dn<8Srt"
    var17 = module0.remove_extras(var16)
    assert var17 is not None
    var18 = 'l\n'
    var19 = module0.remove_extras(var18)
    assert var19 is not None
    var20 = "'Pc@?.*y_TSb"
    var21 = module0.remove_extras(var20)
    assert var21 is not None
    var22 = ']ifhpZdYeE*m'
    var23 = module0.remove_extras(var22)
    assert var23 is not None
    var24 = 'slU{'
    var25 = module0.remove_extras(var24)
    assert var25 is not None
    var26 = module0.remove_extras(var24)
    assert var26 is not None
    var27 = "'Pc@?.*y_TSb"
    var28 = module0.remove_extras(var27)
    assert var28 is not None
    var29 = 'slU{'
    var30 = module0.remove_extras(var29)
    assert var30 is not None
    var31 = 'l\n'
    var32 = module0.remove_extras(var31)
    assert var32 is not None
    var33 = 'us'
    var34 = module0.remove_extras(var33)
    assert var34 is not None
    var35 = 'C\x0cU1XEYcxpk1,.rSKkH`'
    var36 = module0.remove_extras(var35)
    assert var36 is not None


def test_case_22():
    var0 = 'slU{'
    var1 = module0.remove_extras(var0)
    assert var1 is not None
    var2 = module0.remove_extras(var0)
    assert var2 is not None
    var3 = "'Pc@?.*y_TSb"
    var4 = module0.remove_extras(var3)
    assert var4 is not None
    var5 = 'h]MX9d\x0cBUfOl4w>'
    var6 = module0.remove_extras(var5)
    assert var6 is not None
    var7 = "'Pc@?.*y_TSb"
    var8 = module0.remove_extras(var7)
    assert var8 is not None
    var9 = 'slU{'
    var10 = module0.remove_extras(var9)
    assert var10 is not None
    var11 = "'Pc@?.*y_TSb"
    var12 = module0.remove_extras(var11)
    assert var12 is not None
    var13 = "9(\x0c~V4'U[9^_$Dn<8Srt"
    var14 = module0.remove_extras(var13)
    assert var14 is not None
    var15 = 'KY|]M\x0bdR1lErK*ra'
    var16 = module0.remove_extras(var15)
    assert var16 is not None
    var17 = 'slU{'
    var18 = module0.remove_extras(var17)
    assert var18 is not None
    var19 = ']~'
    var20 = module0.remove_extras(var19)
    assert var20 is not None


def test_case_23():
    var0 = 'l\n'
    var1 = module0.remove_extras(var0)
    assert var1 is not None
    var2 = "'Pc@?.*y_TSb"
    var3 = module0.remove_extras(var2)
    assert var3 is not None
    var4 = ']ifhpZdYeE*m'
    var5 = module0.remove_extras(var4)
    assert var5 is not None
    var6 = "'Pc@?.*y_TSb"
    var7 = module0.remove_extras(var6)
    assert var7 is not None
    var8 = "'Pc@?.*y_TSb"
    var9 = module0.remove_extras(var8)
    assert var9 is not None
    var10 = 'slU{'
    var11 = module0.remove_extras(var10)
    assert var11 is not None
    var12 = module0.remove_extras(var10)
    assert var12 is not None
    var13 = 'G1\'vwZ\n2"0&~`'
    var14 = module0.remove_extras(var13)
    assert var14 is not None
    var15 = "'Pc@?.*y_TSb"
    var16 = module0.remove_extras(var15)
    assert var16 is not None
    var17 = 'h]MX9d\x0cBUfOl4w>'
    var18 = module0.remove_extras(var17)
    assert var18 is not None
    var19 = 'slU{'
    var20 = module0.remove_extras(var19)
    assert var20 is not None
    var21 = "'Pc@?.*y_TSb"
    var22 = module0.remove_extras(var21)
    assert var22 is not None
    var23 = "9(\x0c~V4'U[9^_$Dn<8Srt"
    var24 = module0.remove_extras(var23)
    assert var24 is not None
    var25 = 'l\n'
    var26 = module0.remove_extras(var25)
    assert var26 is not None
    var27 = 'slU{'
    var28 = module0.remove_extras(var27)
    assert var28 is not None
    var29 = "'Pc@?.*y_TSb"
    var30 = module0.remove_extras(var29)
    assert var30 is not None
    var31 = "9(\x0c~V4'U[9^_$Dn<8Srt"
    var32 = module0.remove_extras(var31)
    assert var32 is not None
    var33 = 'KY|]M\x0bdR1lErK*ra'
    var34 = module0.remove_extras(var33)
    assert var34 is not None
    var35 = 'slU{'
    var36 = module0.remove_extras(var35)
    assert var36 is not None
    var37 = 'us'
    var38 = module0.remove_extras(var37)
    assert var38 is not None
    var39 = 'slU{'
    var40 = module0.remove_extras(var39)
    assert var40 is not None
    var41 = module0.remove_extras(var39)
    assert var41 is not None
    var42 = ',=rF}'
    var43 = module0.remove_extras(var42)
    assert var43 is not None


def test_case_24():
    var0 = 'l\n'
    var1 = module0.remove_extras(var0)
    assert var1 is not None
    var2 = 'slU{'
    var3 = module0.remove_extras(var2)
    assert var3 is not None
    var4 = "'Pc@?.*y_TSb"
    var5 = module0.remove_extras(var4)
    assert var5 is not None
    var6 = "9(\x0c~V4'U[9^_$Dn<8Srt"
    var7 = module0.remove_extras(var6)
    assert var7 is not None
    var8 = 'slU{'
    var9 = module0.remove_extras(var8)
    assert var9 is not None
    var10 = module0.remove_extras(var8)
    assert var10 is not None
    var11 = 'slU{'
    var12 = module0.remove_extras(var11)
    assert var12 is not None
    var13 = module0.remove_extras(var8)
    assert var13 is not None


def test_case_25():
    var0 = 'slU{'
    var1 = module0.remove_extras(var0)
    assert var1 is not None
    var2 = "'Pc@?.*y_TSb"
    var3 = module0.remove_extras(var2)
    assert var3 is not None
    var4 = "9(\x0c~V4'U[9^_$Dn<8Srt"
    var5 = module0.remove_extras(var4)
    assert var5 is not None
    var6 = 'KY|]M\x0bdR1lErK*ra'
    var7 = module0.remove_extras(var6)
    assert var7 is not None
    var8 = 'l\n'
    var9 = module0.remove_extras(var8)
    assert var9 is not None
    var10 = "'Pc@?.*y_TSb"
    var11 = module0.remove_extras(var10)
    assert var11 is not None
    var12 = 'slU{'
    var13 = module0.remove_extras(var12)
    assert var13 is not None
    var14 = module0.remove_extras(var12)
    assert var14 is not None
    var15 = 'G1\'vwZ\n2"0&~`'
    var16 = module0.remove_extras(var15)
    assert var16 is not None
    var17 = 'us'
    var18 = module0.remove_extras(var17)
    assert var18 is not None
    var19 = 'slU{'
    var20 = module0.remove_extras(var19)
    assert var20 is not None
    var21 = "'Pc@?.*y_TSb"
    var22 = module0.remove_extras(var21)
    assert var22 is not None
    var23 = "9(\x0c~V4'U[9^_$Dn<8Srt"
    var24 = module0.remove_extras(var23)
    assert var24 is not None
    var25 = "'Pc@?.*y_TSb"
    var26 = module0.remove_extras(var25)
    assert var26 is not None
    var27 = ']o'
    var28 = module0.remove_extras(var27)
    assert var28 is not None


def test_case_26():
    var0 = 'slU{'
    var1 = module0.remove_extras(var0)
    assert var1 is not None
    var2 = "'Pc@?.*y_TSb"
    var3 = module0.remove_extras(var2)
    assert var3 is not None
    var4 = 'slU{'
    var5 = module0.remove_extras(var4)
    assert var5 is not None
    var6 = module0.remove_extras(var4)
    assert var6 is not None
    var7 = 'G1\'vwZ\n2"0&~`'
    var8 = module0.remove_extras(var7)
    assert var8 is not None
    var9 = "'Pc@?.*y_TSb"
    var10 = module0.remove_extras(var9)
    assert var10 is not None
    var11 = 'h]MX9d\x0cBUfOl4w>'
    var12 = module0.remove_extras(var11)
    assert var12 is not None
    var13 = 'us'
    var14 = module0.remove_extras(var13)
    assert var14 is not None
    var15 = 'slU{'
    var16 = module0.remove_extras(var15)
    assert var16 is not None
    var17 = "'Pc@?.*y_TSb"
    var18 = module0.remove_extras(var17)
    assert var18 is not None
    var19 = "9(\x0c~V4'U[9^_$Dn<8Srt"
    var20 = module0.remove_extras(var19)
    assert var20 is not None
    var21 = 'l\n'
    var22 = module0.remove_extras(var21)
    assert var22 is not None
    var23 = 'slU{'
    var24 = module0.remove_extras(var23)
    assert var24 is not None
    var25 = module0.remove_extras(var23)
    assert var25 is not None
    var26 = 'l\n'
    var27 = module0.remove_extras(var26)
    assert var27 is not None
    var28 = "'Pc@?.*y_TSb"
    var29 = module0.remove_extras(var28)
    assert var29 is not None
    var30 = ']ifhpZdYeE*m'
    var31 = module0.remove_extras(var30)
    assert var31 is not None
    var32 = '$nO5R/mJ]eV\rxj[Qbn'
    var33 = module0.remove_extras(var32)
    assert var33 is not None


def test_case_27():
    var0 = "'Pc@?.*y_TSb"
    var1 = module0.remove_extras(var0)
    assert var1 is not None
    var2 = 'us'
    var3 = module0.remove_extras(var2)
    assert var3 is not None
    var4 = 'l\n'
    var5 = module0.remove_extras(var4)
    assert var5 is not None
    var6 = "'Pc@?.*y_TSb"
    var7 = module0.remove_extras(var6)
    assert var7 is not None
    var8 = ']ifhpZdYeE*m'
    var9 = module0.remove_extras(var8)
    assert var9 is not None
    var10 = "'Pc@?.*y_TSb"
    var11 = module0.remove_extras(var10)
    assert var11 is not None
    var12 = 'h]MX9d\x0cBUfOl4w>'
    var13 = module0.remove_extras(var12)
    assert var13 is not None
    var14 = "'Pc@?.*y_TSb"
    var15 = module0.remove_extras(var14)
    assert var15 is not None
    var16 = 'slU{'
    var17 = module0.remove_extras(var16)
    assert var17 is not None
    var18 = module0.remove_extras(var16)
    assert var18 is not None
    var19 = 'G1\'vwZ\n2"0&~`'
    var20 = module0.remove_extras(var19)
    assert var20 is not None
    var21 = 'l\n'
    var22 = module0.remove_extras(var21)
    assert var22 is not None
    var23 = '\x0b'
    var24 = module0.remove_extras(var23)
    assert var24 is not None


def test_case_28():
    var0 = '1 '
    var1 = module0.remove_extras(var0)
    assert var1 is not None


def test_case_29():
    var0 = 'l\n'
    var1 = module0.remove_extras(var0)
    assert var1 is not None
    var2 = "'Pc@?.*y_TSb"
    var3 = module0.remove_extras(var2)
    assert var3 is not None
    var4 = ']ifhpZdYeE*m'
    var5 = module0.remove_extras(var4)
    assert var5 is not None
    var6 = 'slU{'
    var7 = module0.remove_extras(var6)
    assert var7 is not None
    var8 = '1 '
    var9 = module0.remove_extras(var8)
    assert var9 is not None
    var10 = 'us'
    var11 = module0.remove_extras(var10)
    assert var11 is not None
    var12 = "'Pc@?.*y_TSb"
    var13 = module0.remove_extras(var12)
    assert var13 is not None
    var14 = 'h]MX9d\x0cBUfOl4w>'
    var15 = module0.remove_extras(var14)
    assert var15 is not None
    var16 = "FZk'}P`7"
    var17 = module0.remove_extras(var16)
    assert var17 is not None


def test_case_30():
    var0 = 'l\n'
    var1 = module0.remove_extras(var0)
    assert var1 is not None
    var2 = "'Pc@?.*y_TSb"
    var3 = module0.remove_extras(var2)
    assert var3 is not None
    var4 = 'h]MX9d\x0cBUfOl4w>'
    var5 = module0.remove_extras(var4)
    assert var5 is not None
    var6 = "'Pc@?.*y_TSb"
    var7 = module0.remove_extras(var6)
    assert var7 is not None
    var8 = 'slU{'
    var9 = module0.remove_extras(var8)
    assert var9 is not None
    var10 = module0.remove_extras(var8)
    assert var10 is not None
    var11 = 'G1\'vwZ\n2"0&~`'
    var12 = module0.remove_extras(var11)
    assert var12 is not None
    var13 = 'slU{'
    var14 = module0.remove_extras(var13)
    assert var14 is not None
    var15 = "'Pc@?.*y_TSb"
    var16 = module0.remove_extras(var15)
    assert var16 is not None
    var17 = "9(\x0c~V4'U[9^_$Dn<8Srt"
    var18 = module0.remove_extras(var17)
    assert var18 is not None
    var19 = "'Pc@?.*y_TSb"
    var20 = module0.remove_extras(var19)
    assert var20 is not None
    var21 = 'slU{'
    var22 = module0.remove_extras(var21)
    assert var22 is not None
    var23 = module0.remove_extras(var21)
    assert var23 is not None
    var24 = 'slU{'
    var25 = module0.remove_extras(var24)
    assert var25 is not None
    var26 = "'Pc@?.*y_TSb"
    var27 = module0.remove_extras(var26)
    assert var27 is not None
    var28 = "9(\x0c~V4'U[9^_$Dn<8Srt"
    var29 = module0.remove_extras(var28)
    assert var29 is not None
    var30 = 'KY|]M\x0bdR1lErK*ra'
    var31 = module0.remove_extras(var30)
    assert var31 is not None
    var32 = 't\r'
    var33 = module0.remove_extras(var32)
    assert var33 is not None


def test_case_31():
    var0 = 'slU{'
    var1 = module0.remove_extras(var0)
    assert var1 is not None
    var2 = "'Pc@?.*y_TSb"
    var3 = module0.remove_extras(var2)
    assert var3 is not None
    var4 = "9(\x0c~V4'U[9^_$Dn<8Srt"
    var5 = module0.remove_extras(var4)
    assert var5 is not None
    var6 = 'KY|]M\x0bdR1lErK*ra'
    var7 = module0.remove_extras(var6)
    assert var7 is not None
    var8 = "'Pc@?.*y_TSb"
    var9 = module0.remove_extras(var8)
    assert var9 is not None
    var10 = 'slU{'
    var11 = module0.remove_extras(var10)
    assert var11 is not None
    var12 = module0.remove_extras(var10)
    assert var12 is not None
    var13 = 'G1\'vwZ\n2"0&~`'
    var14 = module0.remove_extras(var13)
    assert var14 is not None
    var15 = "'Pc@?.*y_TSb"
    var16 = module0.remove_extras(var15)
    assert var16 is not None
    var17 = 'slU{'
    var18 = module0.remove_extras(var17)
    assert var18 is not None
    var19 = "'Pc@?.*y_TSb"
    var20 = module0.remove_extras(var19)
    assert var20 is not None
    var21 = "9(\x0c~V4'U[9^_$Dn<8Srt"
    var22 = module0.remove_extras(var21)
    assert var22 is not None
    var23 = 'slU{'
    var24 = module0.remove_extras(var23)
    assert var24 is not None
    var25 = ''
    var26 = module0.remove_extras(var25)
    assert var26 is not None
