# Automatically generated by Pynguin.
import correct_1_001 as module0


def test_case_0():
    try:
        var0 = 2449
        var1 = "wvIF\x0ca*pCee+'(P"
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_1():
    try:
        var0 = -680.0
        var1 = 'J:'
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_2():
    try:
        var0 = True
        var1 = None
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_3():
    try:
        var0 = 2398
        var1 = '%9br*3\x0b+|^0jh#u'
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_4():
    try:
        var0 = True
        var1 = module0.search(var0, var0)
    except BaseException:
        pass


def test_case_5():
    try:
        var0 = '$`\t{8'
        var1 = -2007
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_6():
    try:
        var0 = -2519.612158
        var1 = 1501.93
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_7():
    try:
        var0 = 3098.85
        var1 = None
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_8():
    try:
        var0 = None
        var1 = None
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_9():
    try:
        var0 = ';SH~`\nAv#r65LD m!9'
        var1 = -1781
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_10():
    try:
        var0 = 200.1
        var1 = -1617
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_11():
    try:
        var0 = True
        var1 = None
        var2 = module0.search(var0, var1)
    except BaseException:
        pass
