# Automatically generated by Pynguin.
import caso_covertura_008 as module0


def test_case_0():
    try:
        var0 = 833
        var1 = "(}m'hc|Gp|\x0b-#DW"
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_1():
    try:
        var0 = 'k=r`-h)%I'
        var1 = '>*b&B8ZqC'
        var2 = module0.search(var0, var1)
        assert var2 == 7
        var3 = '@tp4CQwMbMzb`s'
        var4 = 1485
        var5 = module0.search(var3, var4)
    except BaseException:
        pass


def test_case_2():
    try:
        var0 = -1209
        var1 = False
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_3():
    try:
        var0 = 'k=r`-h)%I'
        var1 = '>*b&B8ZqC'
        var2 = module0.search(var0, var1)
        assert var2 == 7
        var3 = 'K|Af8T ?&6XJ B'
        var4 = 'boYNF&dRL*>Y'
        var5 = module0.search(var3, var4)
        assert var5 == 0
        var6 = 'k=r`-h)%I'
        var7 = '>*b&B8ZqC'
        var8 = module0.search(var6, var7)
        assert var8 == 7
        var9 = None
        var10 = module0.search(var9, var6)
    except BaseException:
        pass


def test_case_4():
    try:
        var0 = 'k=r`-h)%I'
        var1 = '>*b&B8ZqC'
        var2 = module0.search(var0, var1)
        assert var2 == 7
        var3 = 'K|Af8T ?&6XJ B'
        var4 = 'boYNF&dRL*>Y'
        var5 = module0.search(var3, var4)
        assert var5 == 0
        var6 = 'y2.fK\x0cUb'
        var7 = True
        var8 = module0.search(var6, var7)
    except BaseException:
        pass


def test_case_5():
    try:
        var0 = 'k=r`-h)%I'
        var1 = '>*b&B8ZqC'
        var2 = module0.search(var0, var1)
        assert var2 == 7
        var3 = False
        var4 = -1123.2728
        var5 = module0.search(var3, var4)
    except BaseException:
        pass


def test_case_6():
    try:
        var0 = 'k=r`-h)%I'
        var1 = '>*b&B8ZqC'
        var2 = module0.search(var0, var1)
        assert var2 == 7
        var3 = 'K|Af8T ?&6XJ B'
        var4 = 'boYNF&dRL*>Y'
        var5 = module0.search(var3, var4)
        assert var5 == 0
        var6 = 'k=r`-h)%I'
        var7 = '>*b&B8ZqC'
        var8 = module0.search(var6, var7)
        assert var8 == 7
        var9 = -1635.64
        var10 = module0.search(var9, var6)
    except BaseException:
        pass


def test_case_7():
    try:
        var0 = 1224
        var1 = 'H*\nh$MH&:\n>'
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_8():
    try:
        var0 = 'k=r`-h)%I'
        var1 = '>*b&B8ZqC'
        var2 = module0.search(var0, var1)
        assert var2 == 7
        var3 = 'K|Af8T ?&6XJ B'
        var4 = 'boYNF&dRL*>Y'
        var5 = module0.search(var3, var4)
        assert var5 == 0
        var6 = None
        var7 = -140.88
        var8 = module0.search(var6, var7)
    except BaseException:
        pass
