# Automatically generated by Pynguin.
import caso_covertura_068 as module0


def test_case_0():
    var0 = '@V;F='
    var1 = module0.remove_extras(var0)
    assert var1 is not None


def test_case_1():
    var0 = '@V;F='
    var1 = module0.remove_extras(var0)
    assert var1 is not None
    var2 = 'YofZ7'
    var3 = module0.remove_extras(var2)
    assert var3 is not None


def test_case_2():
    var0 = '@V;F='
    var1 = module0.remove_extras(var0)
    assert var1 is not None
    var2 = 'YofZ7'
    var3 = module0.remove_extras(var2)
    assert var3 is not None
    var4 = '@V;F='
    var5 = module0.remove_extras(var4)
    assert var5 is not None
    var6 = 'Yppa'
    var7 = module0.remove_extras(var6)
    assert var7 is not None


def test_case_3():
    var0 = '@V;F='
    var1 = module0.remove_extras(var0)
    assert var1 is not None
    var2 = 'YofZ7'
    var3 = module0.remove_extras(var2)
    assert var3 is not None
    var4 = '@V;F='
    var5 = module0.remove_extras(var4)
    assert var5 is not None
    var6 = 'Yppa'
    var7 = module0.remove_extras(var6)
    assert var7 is not None
    var8 = '.Z[|'
    var9 = module0.remove_extras(var8)
    assert var9 is not None


def test_case_4():
    var0 = '@V;F='
    var1 = module0.remove_extras(var0)
    assert var1 is not None
    var2 = 'YofZ7'
    var3 = module0.remove_extras(var2)
    assert var3 is not None
    var4 = '@V;F='
    var5 = module0.remove_extras(var4)
    assert var5 is not None
    var6 = '@V;F='
    var7 = module0.remove_extras(var6)
    assert var7 is not None
    var8 = 'YofZ7'
    var9 = module0.remove_extras(var8)
    assert var9 is not None
    var10 = '@V;F='
    var11 = module0.remove_extras(var10)
    assert var11 is not None
    var12 = 'Yppa'
    var13 = module0.remove_extras(var12)
    assert var13 is not None
    var14 = 'r\tfhy,-\\o'
    var15 = module0.remove_extras(var14)
    assert var15 is not None


def test_case_5():
    var0 = '@V;F='
    var1 = module0.remove_extras(var0)
    assert var1 is not None
    var2 = '@V;F='
    var3 = module0.remove_extras(var2)
    assert var3 is not None
    var4 = 'YofZ7'
    var5 = module0.remove_extras(var4)
    assert var5 is not None
    var6 = '@V;F='
    var7 = module0.remove_extras(var6)
    assert var7 is not None
    var8 = 'Yppa'
    var9 = module0.remove_extras(var8)
    assert var9 is not None
    var10 = module0.remove_extras(var4)
    assert var10 is not None


def test_case_6():
    var0 = '@V;F='
    var1 = module0.remove_extras(var0)
    assert var1 is not None
    var2 = 'YofZ7'
    var3 = module0.remove_extras(var2)
    assert var3 is not None
    var4 = '@V;F='
    var5 = module0.remove_extras(var4)
    assert var5 is not None
    var6 = '@V;F='
    var7 = module0.remove_extras(var6)
    assert var7 is not None
    var8 = 'YofZ7'
    var9 = module0.remove_extras(var8)
    assert var9 is not None
    var10 = '@V;F='
    var11 = module0.remove_extras(var10)
    assert var11 is not None
    var12 = 'Yppa'
    var13 = module0.remove_extras(var12)
    assert var13 is not None
    var14 = 'CL^V=t3_.ydh'
    var15 = module0.remove_extras(var14)
    assert var15 is not None


def test_case_7():
    var0 = '@V;F='
    var1 = module0.remove_extras(var0)
    assert var1 is not None
    var2 = 'YofZ7'
    var3 = module0.remove_extras(var2)
    assert var3 is not None
    var4 = '@V;F='
    var5 = module0.remove_extras(var4)
    assert var5 is not None
    var6 = 'Yppa'
    var7 = module0.remove_extras(var6)
    assert var7 is not None
    var8 = ';|;inIk\x0b"$iJU'
    var9 = module0.remove_extras(var8)
    assert var9 is not None


def test_case_8():
    var0 = '@V;F='
    var1 = module0.remove_extras(var0)
    assert var1 is not None
    var2 = 'b)g(2xbi.]*k.YBYl\rf'
    var3 = module0.remove_extras(var2)
    assert var3 is not None


def test_case_9():
    var0 = '@V;F='
    var1 = module0.remove_extras(var0)
    assert var1 is not None
    var2 = 'YofZ7'
    var3 = module0.remove_extras(var2)
    assert var3 is not None
    var4 = '@V;F='
    var5 = module0.remove_extras(var4)
    assert var5 is not None
    var6 = '@V;F='
    var7 = module0.remove_extras(var6)
    assert var7 is not None
    var8 = 'YofZ7'
    var9 = module0.remove_extras(var8)
    assert var9 is not None
    var10 = '@V;F='
    var11 = module0.remove_extras(var10)
    assert var11 is not None
    var12 = 'Yppa'
    var13 = module0.remove_extras(var12)
    assert var13 is not None
    var14 = ''
    var15 = module0.remove_extras(var14)
    assert var15 is not None
