# Automatically generated by Pynguin.
import caso_covertura_006 as module0


def test_case_0():
    var0 = -2622
    var1 = ''
    var2 = module0.search(var0, var1)
    assert var2 == 0


def test_case_1():
    var0 = '%UIV>\\)-,lVLAh#Ep'
    var1 = module0.search(var0, var0)
    assert var1 == 1
