# Automatically generated by Pynguin.
import caso_covertura_010 as module0


def test_case_0():
    var0 = 'faB7'
    var1 = '?'
    var2 = module0.search(var0, var1)
    assert var2 == 1


def test_case_1():
    var0 = 'faB7'
    var1 = '?'
    var2 = module0.search(var0, var1)
    assert var2 == 1
    var3 = '!f)PB["tH_z'
    var4 = module0.search(var3, var3)
    assert var4 == 1


def test_case_2():
    var0 = 'faB7'
    var1 = '?'
    var2 = module0.search(var0, var1)
    assert var2 == 1
    var3 = module0.search(var1, var1)
    assert var3 == 0


def test_case_3():
    var0 = ')7xBgxTuh%;^,8*Je\\c8'
    var1 = module0.search(var0, var0)
    assert var1 == 1


def test_case_4():
    var0 = 'faB7'
    var1 = '?'
    var2 = module0.search(var0, var1)
    assert var2 == 1
    var3 = '!f)PB["tH_z'
    var4 = module0.search(var3, var3)
    assert var4 == 1
    var5 = "7\x0c0>\t9?Nd64V?=`3VB'"
    var6 = module0.search(var0, var5)
    assert var6 == 19


def test_case_5():
    var0 = 'o:'
    var1 = module0.search(var0, var0)
    assert var1 == 2


def test_case_6():
    var0 = 'faB7'
    var1 = '?'
    var2 = module0.search(var0, var1)
    assert var2 == 1
    var3 = module0.search(var1, var1)
    assert var3 == 0
    var4 = 'Y_7'
    var5 = module0.search(var0, var4)
    assert var5 == 3


def test_case_7():
    var0 = 'faB7'
    var1 = '?'
    var2 = module0.search(var0, var1)
    assert var2 == 1
    var3 = ')7xBgxTuh%;^,8*Je\\c8'
    var4 = module0.search(var3, var3)
    assert var4 == 1
    var5 = 'xa40v+bG*a)mM5\x0cc'
    var6 = module0.search(var0, var5)
    assert var6 == 0


def test_case_8():
    var0 = 'faB7'
    var1 = '?'
    var2 = module0.search(var0, var1)
    assert var2 == 1
    var3 = ')7xBgxTuh%;^,8*Je\\c8'
    var4 = module0.search(var3, var3)
    assert var4 == 1
    var5 = 'faB7'
    var6 = '?'
    var7 = module0.search(var5, var6)
    assert var7 == 1
    var8 = module0.search(var6, var6)
    assert var8 == 0
    var9 = 'faB7'
    var10 = '?'
    var11 = module0.search(var9, var10)
    assert var11 == 1
    var12 = '!f)PB["tH_z'
    var13 = module0.search(var12, var12)
    assert var13 == 1
    var14 = "7\x0c0>\t9?Nd64V?=`3VB'"
    var15 = module0.search(var9, var14)
    assert var15 == 19
    var16 = 'faB7'
    var17 = '?'
    var18 = module0.search(var16, var17)
    assert var18 == 1
    var19 = ')7xBgxTuh%;^,8*Je\\c8'
    var20 = module0.search(var19, var19)
    assert var20 == 1
    var21 = 'xa40v+bG*a)mM5\x0cc'
    var22 = module0.search(var16, var21)
    assert var22 == 0
    var23 = 'o:'
    var24 = module0.search(var23, var23)
    assert var24 == 2
    var25 = 'faB7'
    var26 = '?'
    var27 = module0.search(var25, var26)
    assert var27 == 1
    var28 = module0.search(var26, var26)
    assert var28 == 0
    var29 = 'Y_7'
    var30 = module0.search(var25, var29)
    assert var30 == 3
    var31 = 'faB7'
    var32 = '?'
    var33 = module0.search(var31, var32)
    assert var33 == 1
    var34 = '!f)PB["tH_z'
    var35 = module0.search(var34, var34)
    assert var35 == 1
    var36 = '\\^Us|e/UA!M*K&?'
    var37 = 'P<i'
    var38 = module0.search(var36, var37)
    assert var38 == 2


def test_case_9():
    var0 = 'faB7'
    var1 = '?'
    var2 = module0.search(var0, var1)
    assert var2 == 1
    var3 = module0.search(var1, var1)
    assert var3 == 0
    var4 = 'Y_7'
    var5 = module0.search(var0, var4)
    assert var5 == 3
    var6 = 'faB7'
    var7 = '?'
    var8 = module0.search(var6, var7)
    assert var8 == 1
    var9 = '!f)PB["tH_z'
    var10 = module0.search(var9, var9)
    assert var10 == 1
    var11 = ')7xBgxTuh%;^,8*Je\\c8'
    var12 = module0.search(var11, var11)
    assert var12 == 1
    var13 = 'faB7'
    var14 = '?'
    var15 = module0.search(var13, var14)
    assert var15 == 1
    var16 = ')7xBgxTuh%;^,8*Je\\c8'
    var17 = module0.search(var16, var16)
    assert var17 == 1
    var18 = 'xa40v+bG*a)mM5\x0cc'
    var19 = module0.search(var13, var18)
    assert var19 == 0
    var20 = 'faB7'
    var21 = '?'
    var22 = module0.search(var20, var21)
    assert var22 == 1
    var23 = module0.search(var21, var21)
    assert var23 == 0
    var24 = '\tC=TThG&wbmE]FN.'
    var25 = '|=0>wX<F'
    var26 = module0.search(var24, var25)
    assert var26 == 0


def test_case_10():
    var0 = 'faB7'
    var1 = '?'
    var2 = module0.search(var0, var1)
    assert var2 == 1
    var3 = '!f)PB["tH_z'
    var4 = module0.search(var3, var3)
    assert var4 == 1
    var5 = 'o:'
    var6 = module0.search(var5, var5)
    assert var6 == 2
    var7 = 'faB7'
    var8 = '?'
    var9 = module0.search(var7, var8)
    assert var9 == 1
    var10 = ')7xBgxTuh%;^,8*Je\\c8'
    var11 = module0.search(var10, var10)
    assert var11 == 1
    var12 = 'xa40v+bG*a)mM5\x0cc'
    var13 = module0.search(var7, var12)
    assert var13 == 0
    var14 = ')7xBgxTuh%;^,8*Je\\c8'
    var15 = module0.search(var14, var14)
    assert var15 == 1
    var16 = 'faB7'
    var17 = '?'
    var18 = module0.search(var16, var17)
    assert var18 == 1
    var19 = module0.search(var17, var17)
    assert var19 == 0
    var20 = 'Y_7'
    var21 = module0.search(var16, var20)
    assert var21 == 3
    var22 = 'faB7'
    var23 = '?'
    var24 = module0.search(var22, var23)
    assert var24 == 1
    var25 = module0.search(var23, var23)
    assert var25 == 0
    var26 = 'wI n;Z=m%q\r#NWk='
    var27 = module0.search(var26, var16)
    assert var27 == 4


def test_case_11():
    var0 = 'faB7'
    var1 = '?'
    var2 = module0.search(var0, var1)
    assert var2 == 1
    var3 = module0.search(var1, var1)
    assert var3 == 0
    var4 = 'faB7'
    var5 = '?'
    var6 = module0.search(var4, var5)
    assert var6 == 1
    var7 = '!f)PB["tH_z'
    var8 = module0.search(var7, var7)
    assert var8 == 1
    var9 = 'faB7'
    var10 = '?'
    var11 = module0.search(var9, var10)
    assert var11 == 1
    var12 = ')7xBgxTuh%;^,8*Je\\c8'
    var13 = module0.search(var12, var12)
    assert var13 == 1
    var14 = 'xa40v+bG*a)mM5\x0cc'
    var15 = module0.search(var9, var14)
    assert var15 == 0
    var16 = 'faB7'
    var17 = '?'
    var18 = module0.search(var16, var17)
    assert var18 == 1
    var19 = '!f)PB["tH_z'
    var20 = module0.search(var19, var19)
    assert var20 == 1
    var21 = "7\x0c0>\t9?Nd64V?=`3VB'"
    var22 = module0.search(var16, var21)
    assert var22 == 19
    var23 = 'faB7'
    var24 = '?'
    var25 = module0.search(var23, var24)
    assert var25 == 1
    var26 = module0.search(var24, var24)
    assert var26 == 0
    var27 = 'Y_7'
    var28 = module0.search(var23, var27)
    assert var28 == 3
    var29 = ')7xBgxTuh%;^,8*Je\\c8'
    var30 = module0.search(var29, var29)
    assert var30 == 1
    var31 = ''
    var32 = '$WAZr'
    var33 = module0.search(var31, var32)
    assert var33 == 0


def test_case_12():
    var0 = 'faB7'
    var1 = '?'
    var2 = module0.search(var0, var1)
    assert var2 == 1
    var3 = '!f)PB["tH_z'
    var4 = module0.search(var3, var3)
    assert var4 == 1
    var5 = "7\x0c0>\t9?Nd64V?=`3VB'"
    var6 = module0.search(var0, var5)
    assert var6 == 19
    var7 = 'faB7'
    var8 = '?'
    var9 = module0.search(var7, var8)
    assert var9 == 1
    var10 = ')7xBgxTuh%;^,8*Je\\c8'
    var11 = module0.search(var10, var10)
    assert var11 == 1
    var12 = 'nRJ81l^Q}'
    var13 = 'l3'
    var14 = module0.search(var12, var13)
    assert var14 == 2


def test_case_13():
    var0 = 'faB7'
    var1 = '?'
    var2 = module0.search(var0, var1)
    assert var2 == 1
    var3 = module0.search(var1, var1)
    assert var3 == 0
    var4 = 'o:'
    var5 = module0.search(var4, var4)
    assert var5 == 2
    var6 = 'faB7'
    var7 = '?'
    var8 = module0.search(var6, var7)
    assert var8 == 1
    var9 = 'faB7'
    var10 = '?'
    var11 = module0.search(var9, var10)
    assert var11 == 1
    var12 = '!f)PB["tH_z'
    var13 = module0.search(var12, var12)
    assert var13 == 1
    var14 = "7\x0c0>\t9?Nd64V?=`3VB'"
    var15 = module0.search(var9, var14)
    assert var15 == 19
    var16 = 'faB7'
    var17 = '?'
    var18 = module0.search(var16, var17)
    assert var18 == 1
    var19 = '!f)PB["tH_z'
    var20 = module0.search(var19, var19)
    assert var20 == 1
    var21 = 'faB7'
    var22 = '?'
    var23 = module0.search(var21, var22)
    assert var23 == 1
    var24 = module0.search(var22, var22)
    assert var24 == 0
    var25 = 'Y_7'
    var26 = module0.search(var21, var25)
    assert var26 == 3
    var27 = 'faB7'
    var28 = '?'
    var29 = module0.search(var27, var28)
    assert var29 == 1
    var30 = ')7xBgxTuh%;^,8*Je\\c8'
    var31 = module0.search(var30, var30)
    assert var31 == 1
    var32 = 'xa40v+bG*a)mM5\x0cc'
    var33 = module0.search(var27, var32)
    assert var33 == 0
    var34 = module0.search(var32, var9)
    assert var34 == 4


def test_case_14():
    var0 = 'faB7'
    var1 = '?'
    var2 = module0.search(var0, var1)
    assert var2 == 1
    var3 = 'faB7'
    var4 = '?'
    var5 = module0.search(var3, var4)
    assert var5 == 1
    var6 = ')7xBgxTuh%;^,8*Je\\c8'
    var7 = module0.search(var6, var6)
    assert var7 == 1
    var8 = 'xa40v+bG*a)mM5\x0cc'
    var9 = module0.search(var3, var8)
    assert var9 == 0
    var10 = module0.search(var1, var6)
    assert var10 == 2


def test_case_15():
    var0 = 'faB7'
    var1 = '?'
    var2 = module0.search(var0, var1)
    assert var2 == 1
    var3 = module0.search(var1, var1)
    assert var3 == 0
    var4 = 'Y_7'
    var5 = module0.search(var0, var4)
    assert var5 == 3
    var6 = 'o:'
    var7 = module0.search(var6, var6)
    assert var7 == 2
    var8 = 'faB7'
    var9 = '?'
    var10 = module0.search(var8, var9)
    assert var10 == 1
    var11 = module0.search(var9, var9)
    assert var11 == 0
    var12 = 'faB7'
    var13 = '?'
    var14 = module0.search(var12, var13)
    assert var14 == 1
    var15 = '!f)PB["tH_z'
    var16 = module0.search(var15, var15)
    assert var16 == 1
    var17 = 'faB7'
    var18 = '?'
    var19 = module0.search(var17, var18)
    assert var19 == 1
    var20 = '!f)PB["tH_z'
    var21 = module0.search(var20, var20)
    assert var21 == 1
    var22 = "7\x0c0>\t9?Nd64V?=`3VB'"
    var23 = module0.search(var17, var22)
    assert var23 == 19
    var24 = 'i]'
    var25 = 'E (^@4Erz'
    var26 = module0.search(var24, var25)
    assert var26 == 7


def test_case_16():
    var0 = 'faB7'
    var1 = '?'
    var2 = module0.search(var0, var1)
    assert var2 == 1
    var3 = ')7xBgxTuh%;^,8*Je\\c8'
    var4 = module0.search(var3, var3)
    assert var4 == 1
    var5 = 'xa40v+bG*a)mM5\x0cc'
    var6 = module0.search(var0, var5)
    assert var6 == 0
    var7 = 'faB7'
    var8 = '?'
    var9 = module0.search(var7, var8)
    assert var9 == 1
    var10 = module0.search(var8, var8)
    assert var10 == 0
    var11 = 'Y_7'
    var12 = module0.search(var7, var11)
    assert var12 == 3
    var13 = 'faB7'
    var14 = '?'
    var15 = module0.search(var13, var14)
    assert var15 == 1
    var16 = '!f)PB["tH_z'
    var17 = module0.search(var16, var16)
    assert var17 == 1
    var18 = 'faB7'
    var19 = '?'
    var20 = module0.search(var18, var19)
    assert var20 == 1
    var21 = '!f)PB["tH_z'
    var22 = module0.search(var21, var21)
    assert var22 == 1
    var23 = "7\x0c0>\t9?Nd64V?=`3VB'"
    var24 = module0.search(var18, var23)
    assert var24 == 19
    var25 = ')7xBgxTuh%;^,8*Je\\c8'
    var26 = module0.search(var25, var25)
    assert var26 == 1
    var27 = '9\nx'
    var28 = 'H*(ynMF03I3^^F}'
    var29 = module0.search(var27, var28)
    assert var29 == 0


def test_case_17():
    var0 = 'faB7'
    var1 = '?'
    var2 = module0.search(var0, var1)
    assert var2 == 1
    var3 = 'o:'
    var4 = module0.search(var3, var3)
    assert var4 == 2
    var5 = 'faB7'
    var6 = '?'
    var7 = module0.search(var5, var6)
    assert var7 == 1
    var8 = '!f)PB["tH_z'
    var9 = module0.search(var8, var8)
    assert var9 == 1
    var10 = 'faB7'
    var11 = '?'
    var12 = module0.search(var10, var11)
    assert var12 == 1
    var13 = module0.search(var11, var11)
    assert var13 == 0
    var14 = 'faB7'
    var15 = '?'
    var16 = module0.search(var14, var15)
    assert var16 == 1
    var17 = ')7xBgxTuh%;^,8*Je\\c8'
    var18 = module0.search(var17, var17)
    assert var18 == 1
    var19 = 'xa40v+bG*a)mM5\x0cc'
    var20 = module0.search(var14, var19)
    assert var20 == 0
    var21 = '6*}L+5'
    var22 = module0.search(var21, var17)
    assert var22 == 1


def test_case_18():
    var0 = '|'
    var1 = module0.search(var0, var0)
    assert var1 == 0


def test_case_19():
    var0 = ')7xBgxTuh%;^,8*Je\\c8'
    var1 = module0.search(var0, var0)
    assert var1 == 1
    var2 = 'o:'
    var3 = module0.search(var2, var2)
    assert var3 == 2
    var4 = '|'
    var5 = module0.search(var4, var4)
    assert var5 == 0
    var6 = 'faB7'
    var7 = '?'
    var8 = module0.search(var6, var7)
    assert var8 == 1
    var9 = '!f)PB["tH_z'
    var10 = module0.search(var9, var9)
    assert var10 == 1
    var11 = 'faB7'
    var12 = '?'
    var13 = module0.search(var11, var12)
    assert var13 == 1
    var14 = module0.search(var12, var12)
    assert var14 == 0
    var15 = 'Y_7'
    var16 = module0.search(var11, var15)
    assert var16 == 3
    var17 = 'faB7'
    var18 = '?'
    var19 = module0.search(var17, var18)
    assert var19 == 1
    var20 = module0.search(var18, var18)
    assert var20 == 0
    var21 = 'N\\B@`y'
    var22 = 'o-60R53'
    var23 = module0.search(var21, var22)
    assert var23 == 0


def test_case_20():
    var0 = 'faB7'
    var1 = '?'
    var2 = module0.search(var0, var1)
    assert var2 == 1
    var3 = module0.search(var1, var1)
    assert var3 == 0
    var4 = 'Y_7'
    var5 = module0.search(var0, var4)
    assert var5 == 3
    var6 = 'faB7'
    var7 = '?'
    var8 = module0.search(var6, var7)
    assert var8 == 1
    var9 = module0.search(var7, var7)
    assert var9 == 0
    var10 = 'o:'
    var11 = module0.search(var10, var10)
    assert var11 == 2
    var12 = 'faB7'
    var13 = '?'
    var14 = module0.search(var12, var13)
    assert var14 == 1
    var15 = 'faB7'
    var16 = '?'
    var17 = module0.search(var15, var16)
    assert var17 == 1
    var18 = '!f)PB["tH_z'
    var19 = module0.search(var18, var18)
    assert var19 == 1
    var20 = 'faB7'
    var21 = '?'
    var22 = module0.search(var20, var21)
    assert var22 == 1
    var23 = '!f)PB["tH_z'
    var24 = module0.search(var23, var23)
    assert var24 == 1
    var25 = "7\x0c0>\t9?Nd64V?=`3VB'"
    var26 = module0.search(var20, var25)
    assert var26 == 19
    var27 = 'faB7'
    var28 = '?'
    var29 = module0.search(var27, var28)
    assert var29 == 1
    var30 = ')7xBgxTuh%;^,8*Je\\c8'
    var31 = module0.search(var30, var30)
    assert var31 == 1
    var32 = 'xa40v+bG*a)mM5\x0cc'
    var33 = module0.search(var27, var32)
    assert var33 == 0
    var34 = ')7xBgxTuh%;^,8*Je\\c8'
    var35 = module0.search(var34, var34)
    assert var35 == 1
    var36 = '|\r\x0co%u)@<pT\n4Bc[%x'
    var37 = '#gf0NyF)t4eD'
    var38 = module0.search(var36, var37)
    assert var38 == 12


def test_case_21():
    var0 = 'Hz2Y8'
    var1 = 'i]_"&('
    var2 = module0.search(var0, var1)
    assert var2 == 0


def test_case_22():
    var0 = 'faB7'
    var1 = '?'
    var2 = module0.search(var0, var1)
    assert var2 == 1
    var3 = '|'
    var4 = module0.search(var3, var3)
    assert var4 == 0
    var5 = 'faB7'
    var6 = '?'
    var7 = module0.search(var5, var6)
    assert var7 == 1
    var8 = module0.search(var6, var6)
    assert var8 == 0
    var9 = 'faB7'
    var10 = '?'
    var11 = module0.search(var9, var10)
    assert var11 == 1
    var12 = '!f)PB["tH_z'
    var13 = module0.search(var12, var12)
    assert var13 == 1
    var14 = 'faB7'
    var15 = '?'
    var16 = module0.search(var14, var15)
    assert var16 == 1
    var17 = '!f)PB["tH_z'
    var18 = module0.search(var17, var17)
    assert var18 == 1
    var19 = "7\x0c0>\t9?Nd64V?=`3VB'"
    var20 = module0.search(var14, var19)
    assert var20 == 19
    var21 = ')7xBgxTuh%;^,8*Je\\c8'
    var22 = module0.search(var21, var21)
    assert var22 == 1
    var23 = 'faB7'
    var24 = '?'
    var25 = module0.search(var23, var24)
    assert var25 == 1
    var26 = ')7xBgxTuh%;^,8*Je\\c8'
    var27 = module0.search(var26, var26)
    assert var27 == 1
    var28 = 'xa40v+bG*a)mM5\x0cc'
    var29 = module0.search(var23, var28)
    assert var29 == 0
    var30 = 'Hz2Y8'
    var31 = 'i]_"&('
    var32 = module0.search(var30, var31)
    assert var32 == 0
    var33 = 'o:'
    var34 = module0.search(var33, var33)
    assert var34 == 2
    var35 = 'P#'
    var36 = 'g<2'
    var37 = module0.search(var35, var36)
    assert var37 == 0


def test_case_23():
    var0 = 'o:'
    var1 = module0.search(var0, var0)
    assert var1 == 2
    var2 = 'faB7'
    var3 = '?'
    var4 = module0.search(var2, var3)
    assert var4 == 1
    var5 = module0.search(var3, var3)
    assert var5 == 0
    var6 = 'Y_7'
    var7 = module0.search(var2, var6)
    assert var7 == 3
    var8 = 'faB7'
    var9 = '?'
    var10 = module0.search(var8, var9)
    assert var10 == 1
    var11 = 'Hz2Y8'
    var12 = 'i]_"&('
    var13 = module0.search(var11, var12)
    assert var13 == 0
    var14 = ')7xBgxTuh%;^,8*Je\\c8'
    var15 = module0.search(var14, var14)
    assert var15 == 1
    var16 = 'faB7'
    var17 = '?'
    var18 = module0.search(var16, var17)
    assert var18 == 1
    var19 = '!f)PB["tH_z'
    var20 = module0.search(var19, var19)
    assert var20 == 1
    var21 = "7\x0c0>\t9?Nd64V?=`3VB'"
    var22 = module0.search(var16, var21)
    assert var22 == 19
    var23 = 'faB7'
    var24 = '?'
    var25 = module0.search(var23, var24)
    assert var25 == 1
    var26 = module0.search(var24, var24)
    assert var26 == 0
    var27 = '3kUc@n\tQ\rn2O %p~+;'
    var28 = module0.search(var27, var16)
    assert var28 == 0


def test_case_24():
    var0 = 'faB7'
    var1 = '?'
    var2 = module0.search(var0, var1)
    assert var2 == 1
    var3 = ')7xBgxTuh%;^,8*Je\\c8'
    var4 = module0.search(var3, var3)
    assert var4 == 1
    var5 = 'xa40v+bG*a)mM5\x0cc'
    var6 = module0.search(var0, var5)
    assert var6 == 0
    var7 = 'faB7'
    var8 = '?'
    var9 = module0.search(var7, var8)
    assert var9 == 1
    var10 = '!f)PB["tH_z'
    var11 = module0.search(var10, var10)
    assert var11 == 1
    var12 = 'faB7'
    var13 = '?'
    var14 = module0.search(var12, var13)
    assert var14 == 1
    var15 = module0.search(var13, var13)
    assert var15 == 0
    var16 = 'faB7'
    var17 = '?'
    var18 = module0.search(var16, var17)
    assert var18 == 1
    var19 = ')7xBgxTuh%;^,8*Je\\c8'
    var20 = module0.search(var19, var19)
    assert var20 == 1
    var21 = 'faB7'
    var22 = '?'
    var23 = module0.search(var21, var22)
    assert var23 == 1
    var24 = module0.search(var22, var22)
    assert var24 == 0
    var25 = 'Y_7'
    var26 = module0.search(var21, var25)
    assert var26 == 3
    var27 = '|d!G<f4NOuYQBaW+NV'
    var28 = "/1|u+.?l*fw'jQh"
    var29 = module0.search(var27, var28)
    assert var29 == 15


def test_case_25():
    var0 = 'faB7'
    var1 = '?'
    var2 = module0.search(var0, var1)
    assert var2 == 1
    var3 = '!f)PB["tH_z'
    var4 = module0.search(var3, var3)
    assert var4 == 1
    var5 = 'Hz2Y8'
    var6 = 'i]_"&('
    var7 = module0.search(var5, var6)
    assert var7 == 0
    var8 = module0.search(var3, var1)
    assert var8 == 0


def test_case_26():
    var0 = 'o:'
    var1 = module0.search(var0, var0)
    assert var1 == 2
    var2 = 'faB7'
    var3 = '?'
    var4 = module0.search(var2, var3)
    assert var4 == 1
    var5 = module0.search(var3, var3)
    assert var5 == 0
    var6 = 'faB7'
    var7 = '?'
    var8 = module0.search(var6, var7)
    assert var8 == 1
    var9 = ')7xBgxTuh%;^,8*Je\\c8'
    var10 = module0.search(var9, var9)
    assert var10 == 1
    var11 = 'xa40v+bG*a)mM5\x0cc'
    var12 = module0.search(var6, var11)
    assert var12 == 0
    var13 = 'faB7'
    var14 = '?'
    var15 = module0.search(var13, var14)
    assert var15 == 1
    var16 = '!f)PB["tH_z'
    var17 = module0.search(var16, var16)
    assert var17 == 1
    var18 = "7\x0c0>\t9?Nd64V?=`3VB'"
    var19 = module0.search(var13, var18)
    assert var19 == 19
    var20 = 'Hz2Y8'
    var21 = 'i]_"&('
    var22 = module0.search(var20, var21)
    assert var22 == 0
    var23 = "5L%&eI.Mg'C"
    var24 = module0.search(var7, var23)
    assert var24 == 1


def test_case_27():
    var0 = 'faB7'
    var1 = '?'
    var2 = module0.search(var0, var1)
    assert var2 == 1
    var3 = 'faB7'
    var4 = '?'
    var5 = module0.search(var3, var4)
    assert var5 == 1
    var6 = '!f)PB["tH_z'
    var7 = module0.search(var6, var6)
    assert var7 == 1
    var8 = 'Hz2Y8'
    var9 = 'i]_"&('
    var10 = module0.search(var8, var9)
    assert var10 == 0
    var11 = module0.search(var6, var4)
    assert var11 == 0
    var12 = 'faB7'
    var13 = '?'
    var14 = module0.search(var12, var13)
    assert var14 == 1
    var15 = module0.search(var13, var13)
    assert var15 == 0
    var16 = 'Hz2Y8'
    var17 = 'i]_"&('
    var18 = module0.search(var16, var17)
    assert var18 == 0
    var19 = 'faB7'
    var20 = '?'
    var21 = module0.search(var19, var20)
    assert var21 == 1
    var22 = module0.search(var20, var20)
    assert var22 == 0
    var23 = 'Y_7'
    var24 = module0.search(var19, var23)
    assert var24 == 3
    var25 = 'faB7'
    var26 = '?'
    var27 = module0.search(var25, var26)
    assert var27 == 1
    var28 = '!f)PB["tH_z'
    var29 = module0.search(var28, var28)
    assert var29 == 1
    var30 = "7\x0c0>\t9?Nd64V?=`3VB'"
    var31 = module0.search(var25, var30)
    assert var31 == 19
    var32 = '),|S*|vEFo-}s>Z+o.'
    var33 = module0.search(var32, var30)
    assert var33 == 0


def test_case_28():
    var0 = 'faB7'
    var1 = '?'
    var2 = module0.search(var0, var1)
    assert var2 == 1
    var3 = '!f)PB["tH_z'
    var4 = module0.search(var3, var3)
    assert var4 == 1
    var5 = 'faB7'
    var6 = '?'
    var7 = module0.search(var5, var6)
    assert var7 == 1
    var8 = ')7xBgxTuh%;^,8*Je\\c8'
    var9 = module0.search(var8, var8)
    assert var9 == 1
    var10 = 'xa40v+bG*a)mM5\x0cc'
    var11 = module0.search(var5, var10)
    assert var11 == 0
    var12 = 'o:'
    var13 = module0.search(var12, var12)
    assert var13 == 2
    var14 = 'faB7'
    var15 = '?'
    var16 = module0.search(var14, var15)
    assert var16 == 1
    var17 = '!f)PB["tH_z'
    var18 = module0.search(var17, var17)
    assert var18 == 1
    var19 = 'Hz2Y8'
    var20 = 'i]_"&('
    var21 = module0.search(var19, var20)
    assert var21 == 0
    var22 = module0.search(var17, var15)
    assert var22 == 0
    var23 = '|'
    var24 = module0.search(var23, var23)
    assert var24 == 0
    var25 = 'faB7'
    var26 = '?'
    var27 = module0.search(var25, var26)
    assert var27 == 1
    var28 = module0.search(var26, var26)
    assert var28 == 0
    var29 = 'Y_7'
    var30 = module0.search(var25, var29)
    assert var30 == 3
    var31 = 'faB7'
    var32 = '?'
    var33 = module0.search(var31, var32)
    assert var33 == 1
    var34 = '!f)PB["tH_z'
    var35 = module0.search(var34, var34)
    assert var35 == 1
    var36 = "7\x0c0>\t9?Nd64V?=`3VB'"
    var37 = module0.search(var31, var36)
    assert var37 == 19
    var38 = ')7xBgxTuh%;^,8*Je\\c8'
    var39 = module0.search(var38, var38)
    assert var39 == 1
    var40 = 'P)#7x`8J=A?bQ%9\x0ctr'
    var41 = module0.search(var40, var14)
    assert var41 == 0


def test_case_29():
    var0 = '|'
    var1 = module0.search(var0, var0)
    assert var1 == 0
    var2 = 'o:'
    var3 = module0.search(var2, var2)
    assert var3 == 2
    var4 = 'faB7'
    var5 = '?'
    var6 = module0.search(var4, var5)
    assert var6 == 1
    var7 = ')7xBgxTuh%;^,8*Je\\c8'
    var8 = module0.search(var7, var7)
    assert var8 == 1
    var9 = 'xa40v+bG*a)mM5\x0cc'
    var10 = module0.search(var4, var9)
    assert var10 == 0
    var11 = 'Hz2Y8'
    var12 = 'i]_"&('
    var13 = module0.search(var11, var12)
    assert var13 == 0
    var14 = ')7xBgxTuh%;^,8*Je\\c8'
    var15 = module0.search(var14, var14)
    assert var15 == 1
    var16 = 'faB7'
    var17 = '?'
    var18 = module0.search(var16, var17)
    assert var18 == 1
    var19 = module0.search(var17, var17)
    assert var19 == 0
    var20 = 'faB7'
    var21 = '?'
    var22 = module0.search(var20, var21)
    assert var22 == 1
    var23 = 'faB7'
    var24 = '?'
    var25 = module0.search(var23, var24)
    assert var25 == 1
    var26 = '!f)PB["tH_z'
    var27 = module0.search(var26, var26)
    assert var27 == 1
    var28 = "7\x0c0>\t9?Nd64V?=`3VB'"
    var29 = module0.search(var23, var28)
    assert var29 == 19
    var30 = 'faB7'
    var31 = '?'
    var32 = module0.search(var30, var31)
    assert var32 == 1
    var33 = '!f)PB["tH_z'
    var34 = module0.search(var33, var33)
    assert var34 == 1
    var35 = 'Hz2Y8'
    var36 = 'i]_"&('
    var37 = module0.search(var35, var36)
    assert var37 == 0
    var38 = module0.search(var33, var31)
    assert var38 == 0
    var39 = "}9'?"
    var40 = module0.search(var39, var39)
    assert var40 == 4


def test_case_30():
    var0 = 'faB7'
    var1 = '?'
    var2 = module0.search(var0, var1)
    assert var2 == 1
    var3 = '!f)PB["tH_z'
    var4 = module0.search(var3, var3)
    assert var4 == 1
    var5 = 'faB7'
    var6 = '?'
    var7 = module0.search(var5, var6)
    assert var7 == 1
    var8 = '!f)PB["tH_z'
    var9 = module0.search(var8, var8)
    assert var9 == 1
    var10 = "7\x0c0>\t9?Nd64V?=`3VB'"
    var11 = module0.search(var5, var10)
    assert var11 == 19
    var12 = 'faB7'
    var13 = '?'
    var14 = module0.search(var12, var13)
    assert var14 == 1
    var15 = '!f)PB["tH_z'
    var16 = module0.search(var15, var15)
    assert var16 == 1
    var17 = 'Hz2Y8'
    var18 = 'i]_"&('
    var19 = module0.search(var17, var18)
    assert var19 == 0
    var20 = module0.search(var15, var13)
    assert var20 == 0
    var21 = 'faB7'
    var22 = '?'
    var23 = module0.search(var21, var22)
    assert var23 == 1
    var24 = module0.search(var22, var22)
    assert var24 == 0
    var25 = 'Y_7'
    var26 = module0.search(var21, var25)
    assert var26 == 3
    var27 = 'Z+txr1C?b0m\x0b\r`ZLW'
    var28 = module0.search(var27, var17)
    assert var28 == 1


def test_case_31():
    var0 = ']J=HgdC_ogvZh'
    var1 = 'F-=&k:>?f,RFVyE\nw'
    var2 = module0.search(var0, var1)
    assert var2 == 4


def test_case_32():
    var0 = 'eF!\r{("\x0b]0Oz'
    var1 = 'cZ'
    var2 = module0.search(var0, var1)
    assert var2 == 2


def test_case_33():
    var0 = 'faB7'
    var1 = '?'
    var2 = module0.search(var0, var1)
    assert var2 == 1
    var3 = ')7xBgxTuh%;^,8*Je\\c8'
    var4 = module0.search(var3, var3)
    assert var4 == 1
    var5 = 'xa40v+bG*a)mM5\x0cc'
    var6 = module0.search(var0, var5)
    assert var6 == 0
    var7 = 'faB7'
    var8 = '?'
    var9 = module0.search(var7, var8)
    assert var9 == 1
    var10 = module0.search(var8, var8)
    assert var10 == 0
    var11 = 'Y_7'
    var12 = module0.search(var7, var11)
    assert var12 == 3
    var13 = 'o:'
    var14 = module0.search(var13, var13)
    assert var14 == 2
    var15 = 'd`*.0KQvZxt0~MP'
    var16 = '_l{hg#5!9ldEf6\n'
    var17 = module0.search(var15, var16)
    assert var17 == 1


def test_case_34():
    var0 = '$DY~\n,>'
    var1 = '?#RyN$JirD'
    var2 = module0.search(var0, var1)
    assert var2 == 0


def test_case_35():
    var0 = 'Hz2Y8'
    var1 = 'i]_"&('
    var2 = module0.search(var0, var1)
    assert var2 == 0
    var3 = '|'
    var4 = module0.search(var3, var3)
    assert var4 == 0
    var5 = '$DY~\n,>'
    var6 = '?#RyN$JirD'
    var7 = module0.search(var5, var6)
    assert var7 == 0
    var8 = ']J=HgdC_ogvZh'
    var9 = 'F-=&k:>?f,RFVyE\nw'
    var10 = module0.search(var8, var9)
    assert var10 == 4
    var11 = 'faB7'
    var12 = '?'
    var13 = module0.search(var11, var12)
    assert var13 == 1
    var14 = '!f)PB["tH_z'
    var15 = module0.search(var14, var14)
    assert var15 == 1
    var16 = 'Hz2Y8'
    var17 = 'i]_"&('
    var18 = module0.search(var16, var17)
    assert var18 == 0
    var19 = module0.search(var14, var12)
    assert var19 == 0
    var20 = ')7xBgxTuh%;^,8*Je\\c8'
    var21 = module0.search(var20, var20)
    assert var21 == 1
    var22 = 'faB7'
    var23 = '?'
    var24 = module0.search(var22, var23)
    assert var24 == 1
    var25 = 'faB7'
    var26 = '?'
    var27 = module0.search(var25, var26)
    assert var27 == 1
    var28 = ')7xBgxTuh%;^,8*Je\\c8'
    var29 = module0.search(var28, var28)
    assert var29 == 1
    var30 = 'xa40v+bG*a)mM5\x0cc'
    var31 = module0.search(var25, var30)
    assert var31 == 0
    var32 = 'o:'
    var33 = module0.search(var32, var32)
    assert var33 == 2
    var34 = 'iO|]z3])Nb{p.(y'
    var35 = '@ON%2Z%+2)O\x0bT7n)&'
    var36 = module0.search(var34, var35)
    assert var36 == 14


def test_case_36():
    var0 = 'Hz2Y8'
    var1 = 'i]_"&('
    var2 = module0.search(var0, var1)
    assert var2 == 0
    var3 = 'faB7'
    var4 = '?'
    var5 = module0.search(var3, var4)
    assert var5 == 1
    var6 = module0.search(var4, var4)
    assert var6 == 0
    var7 = 'Y_7'
    var8 = module0.search(var3, var7)
    assert var8 == 3
    var9 = 'faB7'
    var10 = '?'
    var11 = module0.search(var9, var10)
    assert var11 == 1
    var12 = module0.search(var10, var10)
    assert var12 == 0
    var13 = ';yQkoPF'
    var14 = module0.search(var13, var10)
    assert var14 == 0


def test_case_37():
    var0 = ')7xBgxTuh%;^,8*Je\\c8'
    var1 = module0.search(var0, var0)
    assert var1 == 1
    var2 = 'faB7'
    var3 = '?'
    var4 = module0.search(var2, var3)
    assert var4 == 1
    var5 = module0.search(var3, var3)
    assert var5 == 0
    var6 = 'Y_7'
    var7 = module0.search(var2, var6)
    assert var7 == 3
    var8 = 'o:'
    var9 = module0.search(var8, var8)
    assert var9 == 2
    var10 = '$DY~\n,>'
    var11 = '?#RyN$JirD'
    var12 = module0.search(var10, var11)
    assert var12 == 0
    var13 = 'faB7'
    var14 = '?'
    var15 = module0.search(var13, var14)
    assert var15 == 1
    var16 = '!f)PB["tH_z'
    var17 = module0.search(var16, var16)
    assert var17 == 1
    var18 = 'faB7'
    var19 = '?'
    var20 = module0.search(var18, var19)
    assert var20 == 1
    var21 = ')7xBgxTuh%;^,8*Je\\c8'
    var22 = module0.search(var21, var21)
    assert var22 == 1
    var23 = 'xa40v+bG*a)mM5\x0cc'
    var24 = module0.search(var18, var23)
    assert var24 == 0
    var25 = 'iQV3psZe)cAr-'
    var26 = 'lLvClf9Kk98y'
    var27 = module0.search(var25, var26)
    assert var27 == 0


def test_case_38():
    var0 = 'faB7'
    var1 = '?'
    var2 = module0.search(var0, var1)
    assert var2 == 1
    var3 = module0.search(var1, var1)
    assert var3 == 0
    var4 = 'faB7'
    var5 = '?'
    var6 = module0.search(var4, var5)
    assert var6 == 1
    var7 = module0.search(var5, var5)
    assert var7 == 0
    var8 = 'Y_7'
    var9 = module0.search(var4, var8)
    assert var9 == 3
    var10 = '$k!;.wX!i'
    var11 = 'zJa \t`X"zckKR:|QoM'
    var12 = module0.search(var10, var11)
    assert var12 == 0


def test_case_39():
    var0 = 'eF!\r{("\x0b]0Oz'
    var1 = 'cZ'
    var2 = module0.search(var0, var1)
    assert var2 == 2
    var3 = ']J=HgdC_ogvZh'
    var4 = 'F-=&k:>?f,RFVyE\nw'
    var5 = module0.search(var3, var4)
    assert var5 == 4
    var6 = 'faB7'
    var7 = '?'
    var8 = module0.search(var6, var7)
    assert var8 == 1
    var9 = module0.search(var7, var7)
    assert var9 == 0
    var10 = 'faB7'
    var11 = '?'
    var12 = module0.search(var10, var11)
    assert var12 == 1
    var13 = 'faB7'
    var14 = '?'
    var15 = module0.search(var13, var14)
    assert var15 == 1
    var16 = ')7xBgxTuh%;^,8*Je\\c8'
    var17 = module0.search(var16, var16)
    assert var17 == 1
    var18 = 'xa40v+bG*a)mM5\x0cc'
    var19 = module0.search(var13, var18)
    assert var19 == 0
    var20 = 'Hz2Y8'
    var21 = 'i]_"&('
    var22 = module0.search(var20, var21)
    assert var22 == 0
    var23 = "G2GHp@+';^uEp,m:u2T"
    var24 = 'u%9K\'"z }^5RX'
    var25 = module0.search(var23, var24)
    assert var25 == 0


def test_case_40():
    var0 = '$DY~\n,>'
    var1 = '?#RyN$JirD'
    var2 = module0.search(var0, var1)
    assert var2 == 0
    var3 = ';uyuN'
    var4 = module0.search(var3, var3)
    assert var4 == 1


def test_case_41():
    var0 = 'Hz2Y8'
    var1 = 'i]_"&('
    var2 = module0.search(var0, var1)
    assert var2 == 0
    var3 = 'faB7'
    var4 = '?'
    var5 = module0.search(var3, var4)
    assert var5 == 1
    var6 = module0.search(var4, var4)
    assert var6 == 0
    var7 = 'Y_7'
    var8 = module0.search(var3, var7)
    assert var8 == 3
    var9 = 'faB7'
    var10 = '?'
    var11 = module0.search(var9, var10)
    assert var11 == 1
    var12 = '!f)PB["tH_z'
    var13 = module0.search(var12, var12)
    assert var13 == 1
    var14 = 'faB7'
    var15 = '?'
    var16 = module0.search(var14, var15)
    assert var16 == 1
    var17 = 'o:'
    var18 = module0.search(var17, var17)
    assert var18 == 2
    var19 = '|'
    var20 = module0.search(var19, var19)
    assert var20 == 0
    var21 = 'faB7'
    var22 = '?'
    var23 = module0.search(var21, var22)
    assert var23 == 1
    var24 = ')7xBgxTuh%;^,8*Je\\c8'
    var25 = module0.search(var24, var24)
    assert var25 == 1
    var26 = 'xa40v+bG*a)mM5\x0cc'
    var27 = module0.search(var21, var26)
    assert var27 == 0
    var28 = '$DY~\n,>'
    var29 = '?#RyN$JirD'
    var30 = module0.search(var28, var29)
    assert var30 == 0
    var31 = ';uyuN'
    var32 = module0.search(var31, var31)
    assert var32 == 1
    var33 = '7+Xb\t'
    var34 = 'Us?H&q;n"ld@`CZ['
    var35 = module0.search(var33, var34)
    assert var35 == 0


def test_case_42():
    var0 = 'faB7'
    var1 = '?'
    var2 = module0.search(var0, var1)
    assert var2 == 1
    var3 = 'faB7'
    var4 = '?'
    var5 = module0.search(var3, var4)
    assert var5 == 1
    var6 = '!f)PB["tH_z'
    var7 = module0.search(var6, var6)
    assert var7 == 1
    var8 = 'Hz2Y8'
    var9 = 'i]_"&('
    var10 = module0.search(var8, var9)
    assert var10 == 0
    var11 = module0.search(var6, var4)
    assert var11 == 0
    var12 = '|'
    var13 = module0.search(var12, var12)
    assert var13 == 0
    var14 = 'faB7'
    var15 = '?'
    var16 = module0.search(var14, var15)
    assert var16 == 1
    var17 = ')7xBgxTuh%;^,8*Je\\c8'
    var18 = module0.search(var17, var17)
    assert var18 == 1
    var19 = 'xa40v+bG*a)mM5\x0cc'
    var20 = module0.search(var14, var19)
    assert var20 == 0
    var21 = 'faB7'
    var22 = '?'
    var23 = module0.search(var21, var22)
    assert var23 == 1
    var24 = '!f)PB["tH_z'
    var25 = module0.search(var24, var24)
    assert var25 == 1
    var26 = "7\x0c0>\t9?Nd64V?=`3VB'"
    var27 = module0.search(var21, var26)
    assert var27 == 19
    var28 = 'faB7'
    var29 = '?'
    var30 = module0.search(var28, var29)
    assert var30 == 1
    var31 = '!f)PB["tH_z'
    var32 = module0.search(var31, var31)
    assert var32 == 1
    var33 = 'faB7'
    var34 = '?'
    var35 = module0.search(var33, var34)
    assert var35 == 1
    var36 = module0.search(var34, var34)
    assert var36 == 0
    var37 = ']J=HgdC_ogvZh'
    var38 = 'F-=&k:>?f,RFVyE\nw'
    var39 = module0.search(var37, var38)
    assert var39 == 4
    var40 = "8b1u'L.x$o"
    var41 = 'U]1>R'
    var42 = module0.search(var40, var41)
    assert var42 == 0


def test_case_43():
    var0 = 'eF!\r{("\x0b]0Oz'
    var1 = 'cZ'
    var2 = module0.search(var0, var1)
    assert var2 == 2
    var3 = '|'
    var4 = module0.search(var3, var3)
    assert var4 == 0
    var5 = ')7xBgxTuh%;^,8*Je\\c8'
    var6 = module0.search(var5, var5)
    assert var6 == 1
    var7 = '}H2?q$JughO2R$a5bh@J'
    var8 = module0.search(var0, var7)
    assert var8 == 0


def test_case_44():
    var0 = 'eF!\r{("\x0b]0Oz'
    var1 = 'cZ'
    var2 = module0.search(var0, var1)
    assert var2 == 2
    var3 = 'eF!\r{("\x0b]0Oz'
    var4 = 'cZ'
    var5 = module0.search(var3, var4)
    assert var5 == 2
    var6 = '|'
    var7 = module0.search(var6, var6)
    assert var7 == 0
    var8 = ')7xBgxTuh%;^,8*Je\\c8'
    var9 = module0.search(var8, var8)
    assert var9 == 1
    var10 = '}H2?q$JughO2R$a5bh@J'
    var11 = module0.search(var3, var10)
    assert var11 == 0
    var12 = ']J=HgdC_ogvZh'
    var13 = 'F-=&k:>?f,RFVyE\nw'
    var14 = module0.search(var12, var13)
    assert var14 == 4
    var15 = '$DY~\n,>'
    var16 = '?#RyN$JirD'
    var17 = module0.search(var15, var16)
    assert var17 == 0
    var18 = 'o:'
    var19 = module0.search(var18, var18)
    assert var19 == 2
    var20 = 'faB7'
    var21 = '?'
    var22 = module0.search(var20, var21)
    assert var22 == 1
    var23 = module0.search(var21, var21)
    assert var23 == 0
    var24 = 'faB7'
    var25 = '?'
    var26 = module0.search(var24, var25)
    assert var26 == 1
    var27 = '!f)PB["tH_z'
    var28 = module0.search(var27, var27)
    assert var28 == 1
    var29 = 'faB7'
    var30 = '?'
    var31 = module0.search(var29, var30)
    assert var31 == 1
    var32 = module0.search(var30, var30)
    assert var32 == 0
    var33 = 'Y_7'
    var34 = module0.search(var29, var33)
    assert var34 == 3
    var35 = 'faB7'
    var36 = '?'
    var37 = module0.search(var35, var36)
    assert var37 == 1
    var38 = ')7xBgxTuh%;^,8*Je\\c8'
    var39 = module0.search(var38, var38)
    assert var39 == 1
    var40 = 'xa40v+bG*a)mM5\x0cc'
    var41 = module0.search(var35, var40)
    assert var41 == 0
    var42 = '0k9et-tknd'
    var43 = 'w-.W~!Xat_fA|>A^\x0bJ'
    var44 = module0.search(var42, var43)
    assert var44 == 0


def test_case_45():
    var0 = '~r.!CC!=n4\r'
    var1 = '%SD^9Q]4\x0cmJReJT?\x0c'
    var2 = module0.search(var0, var1)
    assert var2 == 17


def test_case_46():
    var0 = 'faB7'
    var1 = '?'
    var2 = module0.search(var0, var1)
    assert var2 == 1
    var3 = '!f)PB["tH_z'
    var4 = module0.search(var3, var3)
    assert var4 == 1
    var5 = "7\x0c0>\t9?Nd64V?=`3VB'"
    var6 = module0.search(var0, var5)
    assert var6 == 19
    var7 = '$DY~\n,>'
    var8 = '?#RyN$JirD'
    var9 = module0.search(var7, var8)
    assert var9 == 0
    var10 = ';uyuN'
    var11 = module0.search(var10, var10)
    assert var11 == 1
    var12 = ')7xBgxTuh%;^,8*Je\\c8'
    var13 = module0.search(var12, var12)
    assert var13 == 1
    var14 = 'o:'
    var15 = module0.search(var14, var14)
    assert var15 == 2
    var16 = 'eF!\r{("\x0b]0Oz'
    var17 = 'cZ'
    var18 = module0.search(var16, var17)
    assert var18 == 2
    var19 = ']J=HgdC_ogvZh'
    var20 = 'F-=&k:>?f,RFVyE\nw'
    var21 = module0.search(var19, var20)
    assert var21 == 4
    var22 = '|'
    var23 = module0.search(var22, var22)
    assert var23 == 0
    var24 = 'eF!\r{("\x0b]0Oz'
    var25 = 'cZ'
    var26 = module0.search(var24, var25)
    assert var26 == 2
    var27 = '|'
    var28 = module0.search(var27, var27)
    assert var28 == 0
    var29 = ')7xBgxTuh%;^,8*Je\\c8'
    var30 = module0.search(var29, var29)
    assert var30 == 1
    var31 = '}H2?q$JughO2R$a5bh@J'
    var32 = module0.search(var24, var31)
    assert var32 == 0
    var33 = 'faB7'
    var34 = '?'
    var35 = module0.search(var33, var34)
    assert var35 == 1
    var36 = '!f)PB["tH_z'
    var37 = module0.search(var36, var36)
    assert var37 == 1
    var38 = 'Hz2Y8'
    var39 = 'i]_"&('
    var40 = module0.search(var38, var39)
    assert var40 == 0
    var41 = module0.search(var36, var34)
    assert var41 == 0
    var42 = "K'<s1\x0by<%"
    var43 = '(j8O:Srn{<'
    var44 = module0.search(var42, var43)
    assert var44 == 1


def test_case_47():
    var0 = '$DY~\n,>'
    var1 = '?#RyN$JirD'
    var2 = module0.search(var0, var1)
    assert var2 == 0
    var3 = '$DY~\n,>'
    var4 = '?#RyN$JirD'
    var5 = module0.search(var3, var4)
    assert var5 == 0
    var6 = ';uyuN'
    var7 = module0.search(var6, var6)
    assert var7 == 1
    var8 = '~r.!CC!=n4\r'
    var9 = '%SD^9Q]4\x0cmJReJT?\x0c'
    var10 = module0.search(var8, var9)
    assert var10 == 17
    var11 = ']J=HgdC_ogvZh'
    var12 = 'F-=&k:>?f,RFVyE\nw'
    var13 = module0.search(var11, var12)
    assert var13 == 4
    var14 = '|'
    var15 = module0.search(var14, var14)
    assert var15 == 0
    var16 = 'eF!\r{("\x0b]0Oz'
    var17 = 'cZ'
    var18 = module0.search(var16, var17)
    assert var18 == 2
    var19 = 'faB7'
    var20 = '?'
    var21 = module0.search(var19, var20)
    assert var21 == 1
    var22 = '!f)PB["tH_z'
    var23 = module0.search(var22, var22)
    assert var23 == 1
    var24 = "7\x0c0>\t9?Nd64V?=`3VB'"
    var25 = module0.search(var19, var24)
    assert var25 == 19
    var26 = '?=YvH[NpE'
    var27 = '=$&m|{\rfem`r\x0cIo'
    var28 = module0.search(var26, var27)
    assert var28 == 3


def test_case_48():
    var0 = ')7xBgxTuh%;^,8*Je\\c8'
    var1 = module0.search(var0, var0)
    assert var1 == 1
    var2 = 'N\x0br#x4f+](Sz|+zl}'
    var3 = ".=W'K"
    var4 = module0.search(var2, var3)
    assert var4 == 2


def test_case_49():
    var0 = '+:i:@} )sd'
    var1 = module0.search(var0, var0)
    assert var1 == 1


def test_case_50():
    var0 = ']J=HgdC_ogvZh'
    var1 = 'F-=&k:>?f,RFVyE\nw'
    var2 = module0.search(var0, var1)
    assert var2 == 4
    var3 = '+:i:@} )sd'
    var4 = module0.search(var3, var3)
    assert var4 == 1
    var5 = '|'
    var6 = module0.search(var5, var5)
    assert var6 == 0
    var7 = 'faB7'
    var8 = '?'
    var9 = module0.search(var7, var8)
    assert var9 == 1
    var10 = module0.search(var8, var8)
    assert var10 == 0
    var11 = '~r.!CC!=n4\r'
    var12 = '%SD^9Q]4\x0cmJReJT?\x0c'
    var13 = module0.search(var11, var12)
    assert var13 == 17
    var14 = 'o:'
    var15 = module0.search(var14, var14)
    assert var15 == 2
    var16 = 'faB7'
    var17 = '?'
    var18 = module0.search(var16, var17)
    assert var18 == 1
    var19 = '!f)PB["tH_z'
    var20 = module0.search(var19, var19)
    assert var20 == 1
    var21 = "7\x0c0>\t9?Nd64V?=`3VB'"
    var22 = module0.search(var16, var21)
    assert var22 == 19
    var23 = 'Hz2Y8'
    var24 = 'i]_"&('
    var25 = module0.search(var23, var24)
    assert var25 == 0
    var26 = 'eF!\r{("\x0b]0Oz'
    var27 = 'cZ'
    var28 = module0.search(var26, var27)
    assert var28 == 2
    var29 = '|'
    var30 = module0.search(var29, var29)
    assert var30 == 0
    var31 = ')7xBgxTuh%;^,8*Je\\c8'
    var32 = module0.search(var31, var31)
    assert var32 == 1
    var33 = '}H2?q$JughO2R$a5bh@J'
    var34 = module0.search(var26, var33)
    assert var34 == 0
    var35 = 'HDk.wB-\nwFY\x0ci9Xx'
    var36 = module0.search(var0, var35)
    assert var36 == 2


def test_case_51():
    var0 = ')7xBgxTuh%;^,8*Je\\c8'
    var1 = module0.search(var0, var0)
    assert var1 == 1
    var2 = 'l_YZi,CP}&/Q!:'
    var3 = "{Ui#F'%P(\nVbunt`*vCf"
    var4 = module0.search(var2, var3)
    assert var4 == 0


def test_case_52():
    var0 = 'eF!\r{("\x0b]0Oz'
    var1 = 'cZ'
    var2 = module0.search(var0, var1)
    assert var2 == 2
    var3 = '|'
    var4 = module0.search(var3, var3)
    assert var4 == 0
    var5 = ')7xBgxTuh%;^,8*Je\\c8'
    var6 = module0.search(var5, var5)
    assert var6 == 1
    var7 = '}H2?q$JughO2R$a5bh@J'
    var8 = module0.search(var0, var7)
    assert var8 == 0
    var9 = ')7xBgxTuh%;^,8*Je\\c8'
    var10 = module0.search(var9, var9)
    assert var10 == 1
    var11 = 'l_YZi,CP}&/Q!:'
    var12 = "{Ui#F'%P(\nVbunt`*vCf"
    var13 = module0.search(var11, var12)
    assert var13 == 0
    var14 = '|'
    var15 = module0.search(var14, var14)
    assert var15 == 0
    var16 = -538
    var17 = ''
    var18 = module0.search(var16, var17)
    assert var18 == 0
