# Automatically generated by Pynguin.
import caso_covertura_002 as module0


def test_case_0():
    try:
        var0 = 50
        var1 = '_*HmE=g;P`l ,kcWAbh'
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_1():
    try:
        var0 = -686
        var1 = 968
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_2():
    try:
        var0 = '\n3XNc9BbW]\x0c'
        var1 = True
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_3():
    try:
        var0 = True
        var1 = -1703.93
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_4():
    try:
        var0 = 'k>w1\x0cnyv<\r@'
        var1 = '?U'
        var2 = module0.search(var0, var1)
        assert var2 == 2
        var3 = '\rzAnX1Q'
        var4 = -788
        var5 = module0.search(var3, var4)
    except BaseException:
        pass


def test_case_5():
    try:
        var0 = 1409
        var1 = 1676
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_6():
    try:
        var0 = 'k>w1\x0cnyv<\r@'
        var1 = '?U'
        var2 = module0.search(var0, var1)
        assert var2 == 2
        var3 = 1694.9
        var4 = 'h^%'
        var5 = module0.search(var3, var4)
    except BaseException:
        pass
