# Automatically generated by Pynguin.
import caso_covertura_006 as module0


def test_case_0():
    try:
        var0 = 3265.374132
        var1 = 3146
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_1():
    try:
        var0 = '\t&d?'
        var1 = True
        var2 = module0.search(var0, var1)
    except BaseException:
        pass
