# Automatically generated by Pynguin.
import caso_covertura_004 as module0


def test_case_0():
    var0 = 'P1c'
    var1 = '=a1V0,-=IpP\tYI6yF{'
    var2 = module0.search(var0, var1)
    assert var2 == 17


def test_case_1():
    var0 = '5*:Z{/wY]iy`V_#,.'
    var1 = "|wCIymb'HiL^\\qQ4|L~"
    var2 = module0.search(var0, var1)
    assert var2 == 16


def test_case_2():
    var0 = 'S1;F]pfj\r[CIgHpP.\t>x'
    var1 = module0.search(var0, var0)
    assert var1 == 19


def test_case_3():
    var0 = 'P1c'
    var1 = '=a1V0,-=IpP\tYI6yF{'
    var2 = module0.search(var0, var1)
    assert var2 == 17
    var3 = '5*:Z{/wY]iy`V_#,.'
    var4 = "|wCIymb'HiL^\\qQ4|L~"
    var5 = module0.search(var3, var4)
    assert var5 == 16
    var6 = '|wdcKu\x0bL%xB ~I'
    var7 = 'z}DPJwn'
    var8 = module0.search(var6, var7)
    assert var8 == 7


def test_case_4():
    var0 = 'S1;F]pfj\r[CIgHpP.\t>x'
    var1 = module0.search(var0, var0)
    assert var1 == 19
    var2 = 'Y\r/'
    var3 = module0.search(var2, var0)
    assert var3 == 19


def test_case_5():
    var0 = 'P1c'
    var1 = '=a1V0,-=IpP\tYI6yF{'
    var2 = module0.search(var0, var1)
    assert var2 == 17
    var3 = 'UL='
    var4 = '~/n\t\\*k!L'
    var5 = module0.search(var3, var4)
    assert var5 == 9


def test_case_6():
    var0 = 'S1;F]pfj\r[CIgHpP.\t>x'
    var1 = module0.search(var0, var0)
    assert var1 == 19
    var2 = 'Y\r/'
    var3 = module0.search(var2, var0)
    assert var3 == 19
    var4 = 'P1c'
    var5 = '=a1V0,-=IpP\tYI6yF{'
    var6 = module0.search(var4, var5)
    assert var6 == 17
    var7 = '5*:Z{/wY]iy`V_#,.'
    var8 = "|wCIymb'HiL^\\qQ4|L~"
    var9 = module0.search(var7, var8)
    assert var9 == 16
    var10 = '|wdcKu\x0bL%xB ~I'
    var11 = 'z}DPJwn'
    var12 = module0.search(var10, var11)
    assert var12 == 7
    var13 = 'P1c'
    var14 = '=a1V0,-=IpP\tYI6yF{'
    var15 = module0.search(var13, var14)
    assert var15 == 17
    var16 = ''
    var17 = "D'PN Q"
    var18 = module0.search(var16, var17)
    assert var18 == 0


def test_case_7():
    var0 = 'P1c'
    var1 = '=a1V0,-=IpP\tYI6yF{'
    var2 = module0.search(var0, var1)
    assert var2 == 17
    var3 = 'jrC,0)q%!Y'
    var4 = module0.search(var1, var3)
    assert var4 == 9


def test_case_8():
    var0 = 'P1c'
    var1 = '=a1V0,-=IpP\tYI6yF{'
    var2 = module0.search(var0, var1)
    assert var2 == 17
    var3 = 'A`cR|~hY.yY*\x0bq'
    var4 = module0.search(var3, var3)
    assert var4 == 13


def test_case_9():
    var0 = 'P1c'
    var1 = '=a1V0,-=IpP\tYI6yF{'
    var2 = module0.search(var0, var1)
    assert var2 == 17
    var3 = '5*:Z{/wY]iy`V_#,.'
    var4 = "|wCIymb'HiL^\\qQ4|L~"
    var5 = module0.search(var3, var4)
    assert var5 == 16
    var6 = '|wdcKu\x0bL%xB ~I'
    var7 = 'z}DPJwn'
    var8 = module0.search(var6, var7)
    assert var8 == 7
    var9 = '5*:Z{/wY]iy`V_#,.'
    var10 = "|wCIymb'HiL^\\qQ4|L~"
    var11 = module0.search(var9, var10)
    assert var11 == 16
    var12 = 'P1c'
    var13 = '=a1V0,-=IpP\tYI6yF{'
    var14 = module0.search(var12, var13)
    assert var14 == 17
    var15 = 'A`cR|~hY.yY*\x0bq'
    var16 = module0.search(var15, var15)
    assert var16 == 13
    var17 = 'P1c'
    var18 = '=a1V0,-=IpP\tYI6yF{'
    var19 = module0.search(var17, var18)
    assert var19 == 17
    var20 = 'P1c'
    var21 = '=a1V0,-=IpP\tYI6yF{'
    var22 = module0.search(var20, var21)
    assert var22 == 17
    var23 = 'jrC,0)q%!Y'
    var24 = module0.search(var21, var23)
    assert var24 == 9
    var25 = 'es'
    var26 = '-Y\rEGa'
    var27 = module0.search(var25, var26)
    assert var27 == 6


def test_case_10():
    var0 = 'S1;F]pfj\r[CIgHpP.\t>x'
    var1 = module0.search(var0, var0)
    assert var1 == 19
    var2 = 'S1;F]pfj\r[CIgHpP.\t>x'
    var3 = module0.search(var2, var2)
    assert var3 == 19
    var4 = 'Y\r/'
    var5 = module0.search(var4, var2)
    assert var5 == 19
    var6 = '5*:Z{/wY]iy`V_#,.'
    var7 = "|wCIymb'HiL^\\qQ4|L~"
    var8 = module0.search(var6, var7)
    assert var8 == 16
    var9 = 'P1c'
    var10 = '=a1V0,-=IpP\tYI6yF{'
    var11 = module0.search(var9, var10)
    assert var11 == 17
    var12 = 'A`cR|~hY.yY*\x0bq'
    var13 = module0.search(var12, var12)
    assert var13 == 13
    var14 = ''
    var15 = module0.search(var14, var2)
    assert var15 == 0


def test_case_11():
    var0 = '"bFZiI<w[#[mUz0=2_~'
    var1 = module0.search(var0, var0)
    assert var1 == 1


def test_case_12():
    var0 = '"bFZiI<w[#[mUz0=2_~'
    var1 = module0.search(var0, var0)
    assert var1 == 1
    var2 = 'S1;F]pfj\r[CIgHpP.\t>x'
    var3 = module0.search(var2, var2)
    assert var3 == 19
    var4 = 'P1c'
    var5 = '=a1V0,-=IpP\tYI6yF{'
    var6 = module0.search(var4, var5)
    assert var6 == 17
    var7 = 'jrC,0)q%!Y'
    var8 = module0.search(var5, var7)
    assert var8 == 9
    var9 = 'P1c'
    var10 = '=a1V0,-=IpP\tYI6yF{'
    var11 = module0.search(var9, var10)
    assert var11 == 17
    var12 = 'P1c'
    var13 = '=a1V0,-=IpP\tYI6yF{'
    var14 = module0.search(var12, var13)
    assert var14 == 17
    var15 = 'UL='
    var16 = '~/n\t\\*k!L'
    var17 = module0.search(var15, var16)
    assert var17 == 9
    var18 = 'P1c'
    var19 = '=a1V0,-=IpP\tYI6yF{'
    var20 = module0.search(var18, var19)
    assert var20 == 17
    var21 = '5*:Z{/wY]iy`V_#,.'
    var22 = "|wCIymb'HiL^\\qQ4|L~"
    var23 = module0.search(var21, var22)
    assert var23 == 16
    var24 = '|wdcKu\x0bL%xB ~I'
    var25 = 'z}DPJwn'
    var26 = module0.search(var24, var25)
    assert var26 == 7
    var27 = 'S1;F]pfj\r[CIgHpP.\t>x'
    var28 = module0.search(var27, var27)
    assert var28 == 19
    var29 = 'Y\r/'
    var30 = module0.search(var29, var27)
    assert var30 == 19
    var31 = 'P1c'
    var32 = '=a1V0,-=IpP\tYI6yF{'
    var33 = module0.search(var31, var32)
    assert var33 == 17
    var34 = 'A`cR|~hY.yY*\x0bq'
    var35 = module0.search(var34, var34)
    assert var35 == 13
    var36 = '"2F'
    var37 = module0.search(var12, var36)
    assert var37 == 3


def test_case_13():
    var0 = 'S1;F]pfj\r[CIgHpP.\t>x'
    var1 = module0.search(var0, var0)
    assert var1 == 19
    var2 = 'Y\r/'
    var3 = module0.search(var2, var0)
    assert var3 == 19
    var4 = 'P1c'
    var5 = '=a1V0,-=IpP\tYI6yF{'
    var6 = module0.search(var4, var5)
    assert var6 == 17
    var7 = 'jrC,0)q%!Y'
    var8 = module0.search(var5, var7)
    assert var8 == 9
    var9 = 'S1;F]pfj\r[CIgHpP.\t>x'
    var10 = module0.search(var9, var9)
    assert var10 == 19
    var11 = 'P1c'
    var12 = '=a1V0,-=IpP\tYI6yF{'
    var13 = module0.search(var11, var12)
    assert var13 == 17
    var14 = 'UL='
    var15 = '~/n\t\\*k!L'
    var16 = module0.search(var14, var15)
    assert var16 == 9
    var17 = 'P1c'
    var18 = '=a1V0,-=IpP\tYI6yF{'
    var19 = module0.search(var17, var18)
    assert var19 == 17
    var20 = 'P1c'
    var21 = '=a1V0,-=IpP\tYI6yF{'
    var22 = module0.search(var20, var21)
    assert var22 == 17
    var23 = '5*:Z{/wY]iy`V_#,.'
    var24 = "|wCIymb'HiL^\\qQ4|L~"
    var25 = module0.search(var23, var24)
    assert var25 == 16
    var26 = '|wdcKu\x0bL%xB ~I'
    var27 = 'z}DPJwn'
    var28 = module0.search(var26, var27)
    assert var28 == 7
    var29 = '5*:Z{/wY]iy`V_#,.'
    var30 = "|wCIymb'HiL^\\qQ4|L~"
    var31 = module0.search(var29, var30)
    assert var31 == 16
    var32 = '"bFZiI<w[#[mUz0=2_~'
    var33 = module0.search(var32, var32)
    assert var33 == 1
    var34 = 'P1c'
    var35 = '=a1V0,-=IpP\tYI6yF{'
    var36 = module0.search(var34, var35)
    assert var36 == 17
    var37 = 'A`cR|~hY.yY*\x0bq'
    var38 = module0.search(var37, var37)
    assert var38 == 13
    var39 = '\\\x0b3\\m}{ISwq457dE"+Ep'
    var40 = "'8%9\nyADNXluqbt!?X"
    var41 = module0.search(var39, var40)
    assert var41 == 18


def test_case_14():
    var0 = 'S1;F]pfj\r[CIgHpP.\t>x'
    var1 = module0.search(var0, var0)
    assert var1 == 19
    var2 = 'kwM3x(d47O$~#mplZk\\F'
    var3 = 'lY4GQ|J@&;7SL%'
    var4 = module0.search(var2, var3)
    assert var4 == 14


def test_case_15():
    var0 = '"bFZiI<w[#[mUz0=2_~'
    var1 = module0.search(var0, var0)
    assert var1 == 1
    var2 = 'P1c'
    var3 = '=a1V0,-=IpP\tYI6yF{'
    var4 = module0.search(var2, var3)
    assert var4 == 17
    var5 = '5*:Z{/wY]iy`V_#,.'
    var6 = "|wCIymb'HiL^\\qQ4|L~"
    var7 = module0.search(var5, var6)
    assert var7 == 16
    var8 = '|wdcKu\x0bL%xB ~I'
    var9 = 'z}DPJwn'
    var10 = module0.search(var8, var9)
    assert var10 == 7
    var11 = 'S1;F]pfj\r[CIgHpP.\t>x'
    var12 = module0.search(var11, var11)
    assert var12 == 19
    var13 = 'Y\r/'
    var14 = module0.search(var13, var11)
    assert var14 == 19
    var15 = '#q$Ms3'
    var16 = "XOcue;'Pr`?`Q%\n|RNj6"
    var17 = module0.search(var15, var16)
    assert var17 == 15


def test_case_16():
    var0 = 'S1;F]pfj\r[CIgHpP.\t>x'
    var1 = module0.search(var0, var0)
    assert var1 == 19
    var2 = 'kwM3x(d47O$~#mplZk\\F'
    var3 = 'lY4GQ|J@&;7SL%'
    var4 = module0.search(var2, var3)
    assert var4 == 14
    var5 = 'P1c'
    var6 = '=a1V0,-=IpP\tYI6yF{'
    var7 = module0.search(var5, var6)
    assert var7 == 17
    var8 = '5*:Z{/wY]iy`V_#,.'
    var9 = "|wCIymb'HiL^\\qQ4|L~"
    var10 = module0.search(var8, var9)
    assert var10 == 16
    var11 = '|wdcKu\x0bL%xB ~I'
    var12 = 'z}DPJwn'
    var13 = module0.search(var11, var12)
    assert var13 == 7
    var14 = 'P1c'
    var15 = '=a1V0,-=IpP\tYI6yF{'
    var16 = module0.search(var14, var15)
    assert var16 == 17
    var17 = 'jrC,0)q%!Y'
    var18 = module0.search(var15, var17)
    assert var18 == 9
    var19 = 'S1;F]pfj\r[CIgHpP.\t>x'
    var20 = module0.search(var19, var19)
    assert var20 == 19
    var21 = 'Y\r/'
    var22 = module0.search(var21, var19)
    assert var22 == 19
    var23 = 'P1c'
    var24 = '=a1V0,-=IpP\tYI6yF{'
    var25 = module0.search(var23, var24)
    assert var25 == 17
    var26 = 'UL='
    var27 = '~/n\t\\*k!L'
    var28 = module0.search(var26, var27)
    assert var28 == 9
    var29 = '5*:Z{/wY]iy`V_#,.'
    var30 = "|wCIymb'HiL^\\qQ4|L~"
    var31 = module0.search(var29, var30)
    assert var31 == 16
    var32 = 'P1c'
    var33 = '=a1V0,-=IpP\tYI6yF{'
    var34 = module0.search(var32, var33)
    assert var34 == 17
    var35 = 'A`cR|~hY.yY*\x0bq'
    var36 = module0.search(var35, var35)
    assert var36 == 13
    var37 = 'hX4-jR8,S'
    var38 = '+KGxWu/]k@'
    var39 = module0.search(var37, var38)
    assert var39 == 10


def test_case_17():
    var0 = 'P1c'
    var1 = '=a1V0,-=IpP\tYI6yF{'
    var2 = module0.search(var0, var1)
    assert var2 == 17
    var3 = 'A`cR|~hY.yY*\x0bq'
    var4 = module0.search(var3, var3)
    assert var4 == 13
    var5 = 'S1;F]pfj\r[CIgHpP.\t>x'
    var6 = module0.search(var5, var5)
    assert var6 == 19
    var7 = 'S1;F]pfj\r[CIgHpP.\t>x'
    var8 = module0.search(var7, var7)
    assert var8 == 19
    var9 = 'Y\r/'
    var10 = module0.search(var9, var7)
    assert var10 == 19
    var11 = 'P1c'
    var12 = '=a1V0,-=IpP\tYI6yF{'
    var13 = module0.search(var11, var12)
    assert var13 == 17
    var14 = 'jrC,0)q%!Y'
    var15 = module0.search(var12, var14)
    assert var15 == 9
    var16 = 'S1;F]pfj\r[CIgHpP.\t>x'
    var17 = module0.search(var16, var16)
    assert var17 == 19
    var18 = 'kwM3x(d47O$~#mplZk\\F'
    var19 = 'lY4GQ|J@&;7SL%'
    var20 = module0.search(var18, var19)
    assert var20 == 14
    var21 = '"bFZiI<w[#[mUz0=2_~'
    var22 = module0.search(var21, var21)
    assert var22 == 1
    var23 = 'P1c'
    var24 = '=a1V0,-=IpP\tYI6yF{'
    var25 = module0.search(var23, var24)
    assert var25 == 17
    var26 = 'UL='
    var27 = '~/n\t\\*k!L'
    var28 = module0.search(var26, var27)
    assert var28 == 9
    var29 = 'P1c'
    var30 = '=a1V0,-=IpP\tYI6yF{'
    var31 = module0.search(var29, var30)
    assert var31 == 17
    var32 = '5*:Z{/wY]iy`V_#,.'
    var33 = "|wCIymb'HiL^\\qQ4|L~"
    var34 = module0.search(var32, var33)
    assert var34 == 16
    var35 = '|wdcKu\x0bL%xB ~I'
    var36 = 'z}DPJwn'
    var37 = module0.search(var35, var36)
    assert var37 == 7
    var38 = 'O_*s|Z It>71;Y|'
    var39 = '[j`LoA&30Sq/{'
    var40 = module0.search(var38, var39)
    assert var40 == 12


def test_case_18():
    var0 = '5*:Z{/wY]iy`V_#,.'
    var1 = "|wCIymb'HiL^\\qQ4|L~"
    var2 = module0.search(var0, var1)
    assert var2 == 16
    var3 = 'P1c'
    var4 = '=a1V0,-=IpP\tYI6yF{'
    var5 = module0.search(var3, var4)
    assert var5 == 17
    var6 = 'S1;F]pfj\r[CIgHpP.\t>x'
    var7 = module0.search(var6, var6)
    assert var7 == 19
    var8 = 'kwM3x(d47O$~#mplZk\\F'
    var9 = 'lY4GQ|J@&;7SL%'
    var10 = module0.search(var8, var9)
    assert var10 == 14
    var11 = 'S1;F]pfj\r[CIgHpP.\t>x'
    var12 = module0.search(var11, var11)
    assert var12 == 19
    var13 = 'S1;F]pfj\r[CIgHpP.\t>x'
    var14 = module0.search(var13, var13)
    assert var14 == 19
    var15 = 'Y\r/'
    var16 = module0.search(var15, var13)
    assert var16 == 19
    var17 = 'P1c'
    var18 = '=a1V0,-=IpP\tYI6yF{'
    var19 = module0.search(var17, var18)
    assert var19 == 17
    var20 = 'jrC,0)q%!Y'
    var21 = module0.search(var18, var20)
    assert var21 == 9
    var22 = 'fC>?R:VI^v:/Vdlj,rn|'
    var23 = '2/~<nJ!s:QA4,'
    var24 = module0.search(var22, var23)
    assert var24 == 13


def test_case_19():
    var0 = 'P1c'
    var1 = '=a1V0,-=IpP\tYI6yF{'
    var2 = module0.search(var0, var1)
    assert var2 == 17
    var3 = 'A`cR|~hY.yY*\x0bq'
    var4 = module0.search(var3, var3)
    assert var4 == 13
    var5 = 'S1;F]pfj\r[CIgHpP.\t>x'
    var6 = module0.search(var5, var5)
    assert var6 == 19
    var7 = 'kwM3x(d47O$~#mplZk\\F'
    var8 = 'lY4GQ|J@&;7SL%'
    var9 = module0.search(var7, var8)
    assert var9 == 14
    var10 = 'P1c'
    var11 = '=a1V0,-=IpP\tYI6yF{'
    var12 = module0.search(var10, var11)
    assert var12 == 17
    var13 = 'P1c'
    var14 = '=a1V0,-=IpP\tYI6yF{'
    var15 = module0.search(var13, var14)
    assert var15 == 17
    var16 = 'UL='
    var17 = '~/n\t\\*k!L'
    var18 = module0.search(var16, var17)
    assert var18 == 9
    var19 = 'S1;F]pfj\r[CIgHpP.\t>x'
    var20 = module0.search(var19, var19)
    assert var20 == 19
    var21 = 'Y\r/'
    var22 = module0.search(var21, var19)
    assert var22 == 19
    var23 = 'm~@i%\rTl'
    var24 = module0.search(var23, var23)
    assert var24 == 8


def test_case_20():
    var0 = 'P1c'
    var1 = '=a1V0,-=IpP\tYI6yF{'
    var2 = module0.search(var0, var1)
    assert var2 == 17
    var3 = 'UL='
    var4 = '~/n\t\\*k!L'
    var5 = module0.search(var3, var4)
    assert var5 == 9
    var6 = '"bFZiI<w[#[mUz0=2_~'
    var7 = module0.search(var6, var6)
    assert var7 == 1
    var8 = '5*:Z{/wY]iy`V_#,.'
    var9 = "|wCIymb'HiL^\\qQ4|L~"
    var10 = module0.search(var8, var9)
    assert var10 == 16
    var11 = 'P1c'
    var12 = '=a1V0,-=IpP\tYI6yF{'
    var13 = module0.search(var11, var12)
    assert var13 == 17
    var14 = 'A`cR|~hY.yY*\x0bq'
    var15 = module0.search(var14, var14)
    assert var15 == 13
    var16 = 'S1;F]pfj\r[CIgHpP.\t>x'
    var17 = module0.search(var16, var16)
    assert var17 == 19
    var18 = 'Y\r/'
    var19 = module0.search(var18, var16)
    assert var19 == 19
    var20 = 'S1;F]pfj\r[CIgHpP.\t>x'
    var21 = module0.search(var20, var20)
    assert var21 == 19
    var22 = 'kwM3x(d47O$~#mplZk\\F'
    var23 = 'lY4GQ|J@&;7SL%'
    var24 = module0.search(var22, var23)
    assert var24 == 14
    var25 = 'P1c'
    var26 = '=a1V0,-=IpP\tYI6yF{'
    var27 = module0.search(var25, var26)
    assert var27 == 17
    var28 = '5*:Z{/wY]iy`V_#,.'
    var29 = "|wCIymb'HiL^\\qQ4|L~"
    var30 = module0.search(var28, var29)
    assert var30 == 16
    var31 = '|wdcKu\x0bL%xB ~I'
    var32 = 'z}DPJwn'
    var33 = module0.search(var31, var32)
    assert var33 == 7
    var34 = 'P1c'
    var35 = '=a1V0,-=IpP\tYI6yF{'
    var36 = module0.search(var34, var35)
    assert var36 == 17
    var37 = 'jrC,0)q%!Y'
    var38 = module0.search(var35, var37)
    assert var38 == 9
    var39 = 'S1;F]pfj\r[CIgHpP.\t>x'
    var40 = module0.search(var39, var39)
    assert var40 == 19
    var41 = 'Y:/n-NIX^'
    var42 = module0.search(var32, var41)
    assert var42 == 9


def test_case_21():
    var0 = 'P1c'
    var1 = '=a1V0,-=IpP\tYI6yF{'
    var2 = module0.search(var0, var1)
    assert var2 == 17
    var3 = 'jrC,0)q%!Y'
    var4 = module0.search(var1, var3)
    assert var4 == 9
    var5 = 'S1;F]pfj\r[CIgHpP.\t>x'
    var6 = module0.search(var5, var5)
    assert var6 == 19
    var7 = 'P1c'
    var8 = '=a1V0,-=IpP\tYI6yF{'
    var9 = module0.search(var7, var8)
    assert var9 == 17
    var10 = '5*:Z{/wY]iy`V_#,.'
    var11 = "|wCIymb'HiL^\\qQ4|L~"
    var12 = module0.search(var10, var11)
    assert var12 == 16
    var13 = '|wdcKu\x0bL%xB ~I'
    var14 = 'z}DPJwn'
    var15 = module0.search(var13, var14)
    assert var15 == 7
    var16 = '"bFZiI<w[#[mUz0=2_~'
    var17 = module0.search(var16, var16)
    assert var17 == 1
    var18 = 'S1;F]pfj\r[CIgHpP.\t>x'
    var19 = module0.search(var18, var18)
    assert var19 == 19
    var20 = 'kwM3x(d47O$~#mplZk\\F'
    var21 = 'lY4GQ|J@&;7SL%'
    var22 = module0.search(var20, var21)
    assert var22 == 14
    var23 = True
    var24 = ''
    var25 = module0.search(var23, var24)
    assert var25 == 0
