# Automatically generated by Pynguin.
import caso_covertura_190 as module0


def test_case_0():
    var0 = "9$<$(/_cZgeB'_i"
    var1 = module0.remove_extras(var0)
    assert var1 is not None


def test_case_1():
    var0 = 'Bn?Ysm`<;\\G "si30jE;'
    var1 = module0.remove_extras(var0)
    assert var1 is not None


def test_case_2():
    var0 = 'Bn?Ysm`<;\\G "si30jE;'
    var1 = module0.remove_extras(var0)
    assert var1 is not None
    var2 = "9$<$(/_cZgeB'_i"
    var3 = module0.remove_extras(var2)
    assert var3 is not None
    var4 = ''
    var5 = module0.remove_extras(var4)
    assert var5 is not None
