# Automatically generated by Pynguin.
import caso_covertura_007 as module0


def test_case_0():
    var0 = 'z`('
    var1 = ';q28/5rz_3'
    var2 = module0.search(var0, var1)
    assert var2 == 10


def test_case_1():
    var0 = -707
    var1 = ''
    var2 = module0.search(var0, var1)
    assert var2 == 0


def test_case_2():
    var0 = -707
    var1 = ''
    var2 = module0.search(var0, var1)
    assert var2 == 0
    var3 = '&(2'
    var4 = 'HUX'
    var5 = module0.search(var3, var4)
    assert var5 == 0
