# Automatically generated by Pynguin.
import unittest
import pytest
import caso_covertura_001 as module0

class PruebasFunciones(unittest.TestCase):
    def test_case_0(self):
        var0 = ''
        var1 = ''
        var2 = module0.search(var0, var1)
        assert var2 == 0


    def test_case_1(self):
        var0 = '|'
        var1 = "I!!+&L%\x0c*G}z.t'X1'te"
        var2 = module0.search(var0, var1)
        assert var2 == 10
if __name__ == '__main__':
    unittest.main()
