# Automatically generated by Pynguin.
import caso_covertura_002 as module0


def test_case_0():
    var0 = 'k>w1\x0cnyv<\r@'
    var1 = '?U'
    var2 = module0.search(var0, var1)
    assert var2 == 2


def test_case_1():
    var0 = 'k>w1\x0cnyv<\r@'
    var1 = '?U'
    var2 = module0.search(var0, var1)
    assert var2 == 2
    var3 = 'b9P\rABXkS[:H|qtyiJmN'
    var4 = module0.search(var3, var0)
    assert var4 == 0
