# Automatically generated by Pynguin.
import caso_covertura_001 as module0


def test_case_0():
    var0 = '*W-.3WR35F'
    var1 = 'n\n'
    var2 = module0.search(var0, var1)
    assert var2 == 0


def test_case_1():
    var0 = '*W-.3WR35F'
    var1 = 'n\n'
    var2 = module0.search(var0, var1)
    assert var2 == 0
    var3 = 'QWQ^o7u.Oth -o_'
    var4 = 'L'
    var5 = module0.search(var3, var4)
    assert var5 == 1


def test_case_2():
    var0 = '*W-.3WR35F'
    var1 = 'n\n'
    var2 = module0.search(var0, var1)
    assert var2 == 0
    var3 = 'QWQ^o7u.Oth -o_'
    var4 = 'L'
    var5 = module0.search(var3, var4)
    assert var5 == 1
    var6 = "b];2*5*'@Mu\x0bUZ.4L8R#"
    var7 = 'R\x0bZ/vMMlaE-Q&B'
    var8 = module0.search(var6, var7)
    assert var8 == 4


def test_case_3():
    var0 = '=)}|!@$y6BV{5jm;msNF'
    var1 = 'HWLE*'
    var2 = module0.search(var0, var1)
    assert var2 == 0


def test_case_4():
    var0 = '=)}|!@$y6BV{5jm;msNF'
    var1 = 'HWLE*'
    var2 = module0.search(var0, var1)
    assert var2 == 0
    var3 = '*W-.3WR35F'
    var4 = 'n\n'
    var5 = module0.search(var3, var4)
    assert var5 == 0
    var6 = 'QWQ^o7u.Oth -o_'
    var7 = 'L'
    var8 = module0.search(var6, var7)
    assert var8 == 1
    var9 = '*W-.3WR35F'
    var10 = 'n\n'
    var11 = module0.search(var9, var10)
    assert var11 == 0
    var12 = 'QWQ^o7u.Oth -o_'
    var13 = 'L'
    var14 = module0.search(var12, var13)
    assert var14 == 1
    var15 = "b];2*5*'@Mu\x0bUZ.4L8R#"
    var16 = 'R\x0bZ/vMMlaE-Q&B'
    var17 = module0.search(var15, var16)
    assert var17 == 4
    var18 = '*W-.3WR35F'
    var19 = 'n\n'
    var20 = module0.search(var18, var19)
    assert var20 == 0
    var21 = "?ar^(BfWllF`0Rs8k'{:"
    var22 = module0.search(var9, var21)
    assert var22 == 0


def test_case_5():
    var0 = '*W-.3WR35F'
    var1 = 'n\n'
    var2 = module0.search(var0, var1)
    assert var2 == 0
    var3 = 'QWQ^o7u.Oth -o_'
    var4 = 'L'
    var5 = module0.search(var3, var4)
    assert var5 == 1
    var6 = "b];2*5*'@Mu\x0bUZ.4L8R#"
    var7 = 'R\x0bZ/vMMlaE-Q&B'
    var8 = module0.search(var6, var7)
    assert var8 == 4
    var9 = '*W-.3WR35F'
    var10 = 'n\n'
    var11 = module0.search(var9, var10)
    assert var11 == 0
    var12 = 'QWQ^o7u.Oth -o_'
    var13 = 'L'
    var14 = module0.search(var12, var13)
    assert var14 == 1
    var15 = '*W-.3WR35F'
    var16 = 'n\n'
    var17 = module0.search(var15, var16)
    assert var17 == 0
    var18 = "41';'I{Be1\r"
    var19 = ''
    var20 = module0.search(var18, var19)
    assert var20 == 0
