# Automatically generated by Pynguin.
import caso_covertura_001 as module0


def test_case_0():
    try:
        var0 = 542.71
        var1 = False
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_1():
    try:
        var0 = True
        var1 = 'c@&E'
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_2():
    try:
        var0 = False
        var1 = 'fa+m!?*Jfdkvm@dg\x0bY_}'
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_3():
    try:
        var0 = "3U5r\r5F:8j'%&(HWy"
        var1 = False
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_4():
    try:
        var0 = 1443.798997
        var1 = module0.search(var0, var0)
    except BaseException:
        pass


def test_case_5():
    try:
        var0 = None
        var1 = -1172.39159
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_6():
    try:
        var0 = ''
        var1 = -2405
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_7():
    try:
        var0 = True
        var1 = 'e{}\n'
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_8():
    try:
        var0 = 941.0
        var1 = -1476
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_9():
    try:
        var0 = -3589.0
        var1 = 1134.657056
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_10():
    try:
        var0 = 368.73
        var1 = 'Cet=unbsF'
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_11():
    try:
        var0 = 1588.717633
        var1 = '*o`k3\\qf6>-r+RQ'
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_12():
    try:
        var0 = -919.408143
        var1 = module0.search(var0, var0)
    except BaseException:
        pass


def test_case_13():
    try:
        var0 = None
        var1 = None
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_14():
    try:
        var0 = -2283.327474
        var1 = False
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_15():
    try:
        var0 = None
        var1 = 744
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_16():
    try:
        var0 = None
        var1 = 2068.22
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_17():
    try:
        var0 = None
        var1 = module0.search(var0, var0)
    except BaseException:
        pass


def test_case_18():
    try:
        var0 = -1462.7192
        var1 = True
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_19():
    try:
        var0 = True
        var1 = 'Cs3?v'
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_20():
    try:
        var0 = False
        var1 = module0.search(var0, var0)
    except BaseException:
        pass


def test_case_21():
    try:
        var0 = '\x0cHg/a_'
        var1 = -2798.6358
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_22():
    try:
        var0 = None
        var1 = '(}`xAcE2Z6='
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_23():
    try:
        var0 = "4i'Nt%6}"
        var1 = None
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_24():
    try:
        var0 = 'B'
        var1 = 861.451
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_25():
    try:
        var0 = 91.15086
        var1 = "-%'7'8Rh0RHVO"
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_26():
    try:
        var0 = '*W-.3WR35F'
        var1 = 'n\n'
        var2 = module0.search(var0, var1)
        assert var2 == 0
        var3 = False
        var4 = module0.search(var3, var3)
    except BaseException:
        pass


def test_case_27():
    try:
        var0 = '*W-.3WR35F'
        var1 = 'n\n'
        var2 = module0.search(var0, var1)
        assert var2 == 0
        var3 = 3541.276
        var4 = True
        var5 = module0.search(var3, var4)
    except BaseException:
        pass


def test_case_28():
    try:
        var0 = '*W-.3WR35F'
        var1 = 'n\n'
        var2 = module0.search(var0, var1)
        assert var2 == 0
        var3 = '*W-.3WR35F'
        var4 = 'n\n'
        var5 = module0.search(var3, var4)
        assert var5 == 0
        var6 = 'QWQ^o7u.Oth -o_'
        var7 = 'L'
        var8 = module0.search(var6, var7)
        assert var8 == 1
        var9 = False
        var10 = ' L[V\\\x0cHw|&_PWfHmO?#D'
        var11 = module0.search(var9, var10)
    except BaseException:
        pass


def test_case_29():
    try:
        var0 = '*W-.3WR35F'
        var1 = 'n\n'
        var2 = module0.search(var0, var1)
        assert var2 == 0
        var3 = 'QWQ^o7u.Oth -o_'
        var4 = 'L'
        var5 = module0.search(var3, var4)
        assert var5 == 1
        var6 = '*W-.3WR35F'
        var7 = 'n\n'
        var8 = module0.search(var6, var7)
        assert var8 == 0
        var9 = -878.129
        var10 = module0.search(var9, var4)
    except BaseException:
        pass


def test_case_30():
    try:
        var0 = '*W-.3WR35F'
        var1 = 'n\n'
        var2 = module0.search(var0, var1)
        assert var2 == 0
        var3 = True
        var4 = "LI7@]';HF,\tdq[@=xJf"
        var5 = module0.search(var3, var4)
    except BaseException:
        pass


def test_case_31():
    try:
        var0 = None
        var1 = 'c\rLSw\t'
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_32():
    try:
        var0 = '*W-.3WR35F'
        var1 = 'n\n'
        var2 = module0.search(var0, var1)
        assert var2 == 0
        var3 = '*W-.3WR35F'
        var4 = 'n\n'
        var5 = module0.search(var3, var4)
        assert var5 == 0
        var6 = 'QWQ^o7u.Oth -o_'
        var7 = 'L'
        var8 = module0.search(var6, var7)
        assert var8 == 1
        var9 = "b];2*5*'@Mu\x0bUZ.4L8R#"
        var10 = 'R\x0bZ/vMMlaE-Q&B'
        var11 = module0.search(var9, var10)
        assert var11 == 4
        var12 = '*W-.3WR35F'
        var13 = 'n\n'
        var14 = module0.search(var12, var13)
        assert var14 == 0
        var15 = 'QWQ^o7u.Oth -o_'
        var16 = 'L'
        var17 = module0.search(var15, var16)
        assert var17 == 1
        var18 = -476.63021
        var19 = -2325
        var20 = module0.search(var18, var19)
    except BaseException:
        pass


def test_case_33():
    try:
        var0 = None
        var1 = "4(5B\x0cz!|g=3#mXt.7'"
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_34():
    try:
        var0 = "'<||-8IQ|AC$Kc\tx9s9"
        var1 = 2245.726186
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_35():
    try:
        var0 = '*W-.3WR35F'
        var1 = 'n\n'
        var2 = module0.search(var0, var1)
        assert var2 == 0
        var3 = 'QWQ^o7u.Oth -o_'
        var4 = 'L'
        var5 = module0.search(var3, var4)
        assert var5 == 1
        var6 = "b];2*5*'@Mu\x0bUZ.4L8R#"
        var7 = 'R\x0bZ/vMMlaE-Q&B'
        var8 = module0.search(var6, var7)
        assert var8 == 4
        var9 = True
        var10 = False
        var11 = module0.search(var9, var10)
    except BaseException:
        pass


def test_case_36():
    try:
        var0 = '*W-.3WR35F'
        var1 = 'n\n'
        var2 = module0.search(var0, var1)
        assert var2 == 0
        var3 = 'QWQ^o7u.Oth -o_'
        var4 = 'L'
        var5 = module0.search(var3, var4)
        assert var5 == 1
        var6 = '*W-.3WR35F'
        var7 = 'n\n'
        var8 = module0.search(var6, var7)
        assert var8 == 0
        var9 = 'QWQ^o7u.Oth -o_'
        var10 = 'L'
        var11 = module0.search(var9, var10)
        assert var11 == 1
        var12 = "b];2*5*'@Mu\x0bUZ.4L8R#"
        var13 = 'R\x0bZ/vMMlaE-Q&B'
        var14 = module0.search(var12, var13)
        assert var14 == 4
        var15 = 446
        var16 = 1371.68
        var17 = module0.search(var15, var16)
    except BaseException:
        pass


def test_case_37():
    try:
        var0 = '*W-.3WR35F'
        var1 = 'n\n'
        var2 = module0.search(var0, var1)
        assert var2 == 0
        var3 = 'QWQ^o7u.Oth -o_'
        var4 = 'L'
        var5 = module0.search(var3, var4)
        assert var5 == 1
        var6 = "b];2*5*'@Mu\x0bUZ.4L8R#"
        var7 = 'R\x0bZ/vMMlaE-Q&B'
        var8 = module0.search(var6, var7)
        assert var8 == 4
        var9 = '*W-.3WR35F'
        var10 = 'n\n'
        var11 = module0.search(var9, var10)
        assert var11 == 0
        var12 = 'QWQ^o7u.Oth -o_'
        var13 = 'L'
        var14 = module0.search(var12, var13)
        assert var14 == 1
        var15 = '*W-.3WR35F'
        var16 = 'n\n'
        var17 = module0.search(var15, var16)
        assert var17 == 0
        var18 = 'ZB+:j>(4&;a"#2wh[gs'
        var19 = True
        var20 = module0.search(var18, var19)
    except BaseException:
        pass


def test_case_38():
    try:
        var0 = '*W-.3WR35F'
        var1 = 'n\n'
        var2 = module0.search(var0, var1)
        assert var2 == 0
        var3 = -3295
        var4 = None
        var5 = module0.search(var3, var4)
    except BaseException:
        pass


def test_case_39():
    try:
        var0 = '*W-.3WR35F'
        var1 = 'n\n'
        var2 = module0.search(var0, var1)
        assert var2 == 0
        var3 = '*W-.3WR35F'
        var4 = 'n\n'
        var5 = module0.search(var3, var4)
        assert var5 == 0
        var6 = 'QWQ^o7u.Oth -o_'
        var7 = 'L'
        var8 = module0.search(var6, var7)
        assert var8 == 1
        var9 = "b];2*5*'@Mu\x0bUZ.4L8R#"
        var10 = 'R\x0bZ/vMMlaE-Q&B'
        var11 = module0.search(var9, var10)
        assert var11 == 4
        var12 = '=)}|!@$y6BV{5jm;msNF'
        var13 = 'HWLE*'
        var14 = module0.search(var12, var13)
        assert var14 == 0
        var15 = 1125.610933
        var16 = -1333
        var17 = module0.search(var15, var16)
    except BaseException:
        pass


def test_case_40():
    try:
        var0 = '=)}|!@$y6BV{5jm;msNF'
        var1 = 'HWLE*'
        var2 = module0.search(var0, var1)
        assert var2 == 0
        var3 = 297.21
        var4 = True
        var5 = module0.search(var3, var4)
    except BaseException:
        pass


def test_case_41():
    try:
        var0 = '=)}|!@$y6BV{5jm;msNF'
        var1 = 'HWLE*'
        var2 = module0.search(var0, var1)
        assert var2 == 0
        var3 = '*W-.3WR35F'
        var4 = 'n\n'
        var5 = module0.search(var3, var4)
        assert var5 == 0
        var6 = 'QWQ^o7u.Oth -o_'
        var7 = 'L'
        var8 = module0.search(var6, var7)
        assert var8 == 1
        var9 = 262.325
        var10 = '\n59v.a'
        var11 = module0.search(var9, var10)
    except BaseException:
        pass


def test_case_42():
    try:
        var0 = '*W-.3WR35F'
        var1 = 'n\n'
        var2 = module0.search(var0, var1)
        assert var2 == 0
        var3 = 'QWQ^o7u.Oth -o_'
        var4 = 'L'
        var5 = module0.search(var3, var4)
        assert var5 == 1
        var6 = False
        var7 = module0.search(var6, var6)
    except BaseException:
        pass


def test_case_43():
    try:
        var0 = '=)}|!@$y6BV{5jm;msNF'
        var1 = 'HWLE*'
        var2 = module0.search(var0, var1)
        assert var2 == 0
        var3 = '*W-.3WR35F'
        var4 = 'n\n'
        var5 = module0.search(var3, var4)
        assert var5 == 0
        var6 = 'QWQ^o7u.Oth -o_'
        var7 = 'L'
        var8 = module0.search(var6, var7)
        assert var8 == 1
        var9 = 2979.0
        var10 = module0.search(var7, var9)
    except BaseException:
        pass


def test_case_44():
    try:
        var0 = '*W-.3WR35F'
        var1 = 'n\n'
        var2 = module0.search(var0, var1)
        assert var2 == 0
        var3 = True
        var4 = module0.search(var0, var3)
    except BaseException:
        pass
