# Automatically generated by Pynguin.
import correct_1_010 as module0


def test_case_0():
    try:
        var0 = 'KqpE[\rlP'
        var1 = 1512.78837
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_1():
    try:
        var0 = 2953
        var1 = 1436.619
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_2():
    try:
        var0 = "IxK'-vzT1'omy\t"
        var1 = 150
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_3():
    try:
        var0 = True
        var1 = -1925.1125
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_4():
    try:
        var0 = -1909.0
        var1 = module0.search(var0, var0)
    except BaseException:
        pass


def test_case_5():
    try:
        var0 = -691.0
        var1 = True
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_6():
    try:
        var0 = '2KIH*\x0bk+1CcX%ySeh '
        var1 = -1142.0
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_7():
    try:
        var0 = 858
        var1 = 2695.35
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_8():
    try:
        var0 = 461
        var1 = None
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_9():
    try:
        var0 = '\x0b&V"6C'
        var1 = True
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_10():
    try:
        var0 = '3AXl=cxV4w'
        var1 = module0.search(var0, var0)
        assert var1 == 1
        var2 = 'l`$GH"F_>zG|#M`'
        var3 = 'K'
        var4 = module0.search(var2, var3)
        assert var4 == 1
        var5 = '3AXl=cxV4w'
        var6 = module0.search(var5, var5)
        assert var6 == 1
        var7 = 250.07
        var8 = True
        var9 = module0.search(var7, var8)
    except BaseException:
        pass


def test_case_11():
    try:
        var0 = '3AXl=cxV4w'
        var1 = module0.search(var0, var0)
        assert var1 == 1
        var2 = "\\V`(K=^FNmo)>'7W97Yo"
        var3 = 519.0
        var4 = module0.search(var2, var3)
    except BaseException:
        pass


def test_case_12():
    try:
        var0 = '3AXl=cxV4w'
        var1 = module0.search(var0, var0)
        assert var1 == 1
        var2 = 'l`$GH"F_>zG|#M`'
        var3 = 'K'
        var4 = module0.search(var2, var3)
        assert var4 == 1
        var5 = -1390
        var6 = '5|5:%{r[:A'
        var7 = module0.search(var5, var6)
    except BaseException:
        pass


def test_case_13():
    try:
        var0 = '3AXl=cxV4w'
        var1 = module0.search(var0, var0)
        assert var1 == 1
        var2 = '3AXl=cxV4w'
        var3 = module0.search(var2, var2)
        assert var3 == 1
        var4 = 'l`$GH"F_>zG|#M`'
        var5 = 'K'
        var6 = module0.search(var4, var5)
        assert var6 == 1
        var7 = '=*'
        var8 = '|Y$I'
        var9 = module0.search(var7, var8)
        assert var9 == 0
        var10 = 'mU^'
        var11 = False
        var12 = module0.search(var10, var11)
    except BaseException:
        pass


def test_case_14():
    try:
        var0 = '=*'
        var1 = '|Y$I'
        var2 = module0.search(var0, var1)
        assert var2 == 0
        var3 = None
        var4 = 4627
        var5 = module0.search(var3, var4)
    except BaseException:
        pass


def test_case_15():
    try:
        var0 = '=*'
        var1 = '|Y$I'
        var2 = module0.search(var0, var1)
        assert var2 == 0
        var3 = '3AXl=cxV4w'
        var4 = module0.search(var3, var3)
        assert var4 == 1
        var5 = 'l`$GH"F_>zG|#M`'
        var6 = 'K'
        var7 = module0.search(var5, var6)
        assert var7 == 1
        var8 = '3AXl=cxV4w'
        var9 = module0.search(var8, var8)
        assert var9 == 1
        var10 = 'j$cm:"|3Ezi;Egn'
        var11 = 'lB>=nYZ'
        var12 = module0.search(var10, var11)
        assert var12 == 0
        var13 = '3AXl=cxV4w'
        var14 = module0.search(var13, var13)
        assert var14 == 1
        var15 = None
        var16 = -1869.928
        var17 = module0.search(var15, var16)
    except BaseException:
        pass


def test_case_16():
    try:
        var0 = '3AXl=cxV4w'
        var1 = module0.search(var0, var0)
        assert var1 == 1
        var2 = 'j$cm:"|3Ezi;Egn'
        var3 = 'lB>=nYZ'
        var4 = module0.search(var2, var3)
        assert var4 == 0
        var5 = '3AXl=cxV4w'
        var6 = module0.search(var5, var5)
        assert var6 == 1
        var7 = '3AXl=cxV4w'
        var8 = module0.search(var7, var7)
        assert var8 == 1
        var9 = 'l`$GH"F_>zG|#M`'
        var10 = 'K'
        var11 = module0.search(var9, var10)
        assert var11 == 1
        var12 = 596
        var13 = '-TG"M9i\r6tm`<uD<]p"l'
        var14 = module0.search(var12, var13)
    except BaseException:
        pass


def test_case_17():
    try:
        var0 = '3AXl=cxV4w'
        var1 = module0.search(var0, var0)
        assert var1 == 1
        var2 = '3AXl=cxV4w'
        var3 = module0.search(var2, var2)
        assert var3 == 1
        var4 = 'l`$GH"F_>zG|#M`'
        var5 = 'K'
        var6 = module0.search(var4, var5)
        assert var6 == 1
        var7 = '3AXl=cxV4w'
        var8 = module0.search(var7, var7)
        assert var8 == 1
        var9 = 'j$cm:"|3Ezi;Egn'
        var10 = 'lB>=nYZ'
        var11 = module0.search(var9, var10)
        assert var11 == 0
        var12 = '=*'
        var13 = '|Y$I'
        var14 = module0.search(var12, var13)
        assert var14 == 0
        var15 = None
        var16 = 918.3
        var17 = module0.search(var15, var16)
    except BaseException:
        pass


def test_case_18():
    try:
        var0 = '3AXl=cxV4w'
        var1 = module0.search(var0, var0)
        assert var1 == 1
        var2 = '=*'
        var3 = '|Y$I'
        var4 = module0.search(var2, var3)
        assert var4 == 0
        var5 = '3AXl=cxV4w'
        var6 = module0.search(var5, var5)
        assert var6 == 1
        var7 = 'j$cm:"|3Ezi;Egn'
        var8 = 'lB>=nYZ'
        var9 = module0.search(var7, var8)
        assert var9 == 0
        var10 = '3AXl=cxV4w'
        var11 = module0.search(var10, var10)
        assert var11 == 1
        var12 = 'l`$GH"F_>zG|#M`'
        var13 = 'K'
        var14 = module0.search(var12, var13)
        assert var14 == 1
        var15 = 903
        var16 = 1529.0
        var17 = module0.search(var15, var16)
    except BaseException:
        pass


def test_case_19():
    try:
        var0 = '3AXl=cxV4w'
        var1 = module0.search(var0, var0)
        assert var1 == 1
        var2 = 'j$cm:"|3Ezi;Egn'
        var3 = 'lB>=nYZ'
        var4 = module0.search(var2, var3)
        assert var4 == 0
        var5 = '3AXl=cxV4w'
        var6 = module0.search(var5, var5)
        assert var6 == 1
        var7 = 'l`$GH"F_>zG|#M`'
        var8 = 'K'
        var9 = module0.search(var7, var8)
        assert var9 == 1
        var10 = '=*'
        var11 = '|Y$I'
        var12 = module0.search(var10, var11)
        assert var12 == 0
        var13 = 'Ga'
        var14 = None
        var15 = module0.search(var13, var14)
    except BaseException:
        pass


def test_case_20():
    try:
        var0 = '3AXl=cxV4w'
        var1 = module0.search(var0, var0)
        assert var1 == 1
        var2 = 'l`$GH"F_>zG|#M`'
        var3 = 'K'
        var4 = module0.search(var2, var3)
        assert var4 == 1
        var5 = '=*'
        var6 = '|Y$I'
        var7 = module0.search(var5, var6)
        assert var7 == 0
        var8 = '3AXl=cxV4w'
        var9 = module0.search(var8, var8)
        assert var9 == 1
        var10 = False
        var11 = module0.search(var2, var10)
    except BaseException:
        pass


def test_case_21():
    try:
        var0 = '3AXl=cxV4w'
        var1 = module0.search(var0, var0)
        assert var1 == 1
        var2 = 'l`$GH"F_>zG|#M`'
        var3 = 'K'
        var4 = module0.search(var2, var3)
        assert var4 == 1
        var5 = '3AXl=cxV4w'
        var6 = module0.search(var5, var5)
        assert var6 == 1
        var7 = 'j$cm:"|3Ezi;Egn'
        var8 = 'lB>=nYZ'
        var9 = module0.search(var7, var8)
        assert var9 == 0
        var10 = '=*'
        var11 = '|Y$I'
        var12 = module0.search(var10, var11)
        assert var12 == 0
        var13 = True
        var14 = 7.0
        var15 = module0.search(var13, var14)
    except BaseException:
        pass


def test_case_22():
    try:
        var0 = '=*'
        var1 = '|Y$I'
        var2 = module0.search(var0, var1)
        assert var2 == 0
        var3 = False
        var4 = 2263
        var5 = module0.search(var3, var4)
    except BaseException:
        pass


def test_case_23():
    try:
        var0 = '3AXl=cxV4w'
        var1 = module0.search(var0, var0)
        assert var1 == 1
        var2 = '=*'
        var3 = '|Y$I'
        var4 = module0.search(var2, var3)
        assert var4 == 0
        var5 = 2268.32
        var6 = 'qDR)y_Vh!%\r'
        var7 = module0.search(var5, var6)
    except BaseException:
        pass


def test_case_24():
    try:
        var0 = '3AXl=cxV4w'
        var1 = module0.search(var0, var0)
        assert var1 == 1
        var2 = 'l`$GH"F_>zG|#M`'
        var3 = 'K'
        var4 = module0.search(var2, var3)
        assert var4 == 1
        var5 = 2736
        var6 = 1922
        var7 = module0.search(var5, var6)
    except BaseException:
        pass


def test_case_25():
    try:
        var0 = '3AXl=cxV4w'
        var1 = module0.search(var0, var0)
        assert var1 == 1
        var2 = 'j$cm:"|3Ezi;Egn'
        var3 = 'lB>=nYZ'
        var4 = module0.search(var2, var3)
        assert var4 == 0
        var5 = '3AXl=cxV4w'
        var6 = module0.search(var5, var5)
        assert var6 == 1
        var7 = 'HN\x0crEzWI1(x{K0,9&? 2'
        var8 = True
        var9 = module0.search(var7, var8)
    except BaseException:
        pass


def test_case_26():
    try:
        var0 = '3AXl=cxV4w'
        var1 = module0.search(var0, var0)
        assert var1 == 1
        var2 = 'l`$GH"F_>zG|#M`'
        var3 = 'K'
        var4 = module0.search(var2, var3)
        assert var4 == 1
        var5 = '=*'
        var6 = '|Y$I'
        var7 = module0.search(var5, var6)
        assert var7 == 0
        var8 = True
        var9 = -2889.491945
        var10 = module0.search(var8, var9)
    except BaseException:
        pass


def test_case_27():
    try:
        var0 = '3AXl=cxV4w'
        var1 = module0.search(var0, var0)
        assert var1 == 1
        var2 = 'l`$GH"F_>zG|#M`'
        var3 = 'K'
        var4 = module0.search(var2, var3)
        assert var4 == 1
        var5 = '3AXl=cxV4w'
        var6 = module0.search(var5, var5)
        assert var6 == 1
        var7 = '=*'
        var8 = '|Y$I'
        var9 = module0.search(var7, var8)
        assert var9 == 0
        var10 = '3AXl=cxV4w'
        var11 = module0.search(var10, var10)
        assert var11 == 1
        var12 = 'j$cm:"|3Ezi;Egn'
        var13 = 'lB>=nYZ'
        var14 = module0.search(var12, var13)
        assert var14 == 0
        var15 = False
        var16 = None
        var17 = module0.search(var15, var16)
    except BaseException:
        pass


def test_case_28():
    try:
        var0 = '3AXl=cxV4w'
        var1 = module0.search(var0, var0)
        assert var1 == 1
        var2 = 'j$cm:"|3Ezi;Egn'
        var3 = 'lB>=nYZ'
        var4 = module0.search(var2, var3)
        assert var4 == 0
        var5 = '3AXl=cxV4w'
        var6 = module0.search(var5, var5)
        assert var6 == 1
        var7 = 'l`$GH"F_>zG|#M`'
        var8 = 'K'
        var9 = module0.search(var7, var8)
        assert var9 == 1
        var10 = '`P=LTc8On#-|p>a|}'
        var11 = 1364.9734
        var12 = module0.search(var10, var11)
    except BaseException:
        pass


def test_case_29():
    try:
        var0 = '3AXl=cxV4w'
        var1 = module0.search(var0, var0)
        assert var1 == 1
        var2 = 'l`$GH"F_>zG|#M`'
        var3 = 'K'
        var4 = module0.search(var2, var3)
        assert var4 == 1
        var5 = '3AXl=cxV4w'
        var6 = module0.search(var5, var5)
        assert var6 == 1
        var7 = 'AUl^K\nv\\_['
        var8 = 'JXKN'
        var9 = module0.search(var7, var8)
        assert var9 == 0
        var10 = '=*'
        var11 = '|Y$I'
        var12 = module0.search(var10, var11)
        assert var12 == 0
        var13 = True
        var14 = module0.search(var13, var8)
    except BaseException:
        pass


def test_case_30():
    try:
        var0 = '=*'
        var1 = '|Y$I'
        var2 = module0.search(var0, var1)
        assert var2 == 0
        var3 = '3AXl=cxV4w'
        var4 = module0.search(var3, var3)
        assert var4 == 1
        var5 = 'l`$GH"F_>zG|#M`'
        var6 = 'K'
        var7 = module0.search(var5, var6)
        assert var7 == 1
        var8 = '3AXl=cxV4w'
        var9 = module0.search(var8, var8)
        assert var9 == 1
        var10 = 'j$cm:"|3Ezi;Egn'
        var11 = 'lB>=nYZ'
        var12 = module0.search(var10, var11)
        assert var12 == 0
        var13 = 170.81405
        var14 = None
        var15 = module0.search(var13, var14)
    except BaseException:
        pass


def test_case_31():
    try:
        var0 = '3AXl=cxV4w'
        var1 = module0.search(var0, var0)
        assert var1 == 1
        var2 = 'l`$GH"F_>zG|#M`'
        var3 = 'K'
        var4 = module0.search(var2, var3)
        assert var4 == 1
        var5 = '3AXl=cxV4w'
        var6 = module0.search(var5, var5)
        assert var6 == 1
        var7 = 'j$cm:"|3Ezi;Egn'
        var8 = 'lB>=nYZ'
        var9 = module0.search(var7, var8)
        assert var9 == 0
        var10 = '3AXl=cxV4w'
        var11 = module0.search(var10, var10)
        assert var11 == 1
        var12 = 'AUl^K\nv\\_['
        var13 = 'JXKN'
        var14 = module0.search(var12, var13)
        assert var14 == 0
        var15 = '3AXl=cxV4w'
        var16 = module0.search(var15, var15)
        assert var16 == 1
        var17 = True
        var18 = module0.search(var17, var10)
    except BaseException:
        pass


def test_case_32():
    try:
        var0 = '3AXl=cxV4w'
        var1 = module0.search(var0, var0)
        assert var1 == 1
        var2 = 'l`$GH"F_>zG|#M`'
        var3 = 'K'
        var4 = module0.search(var2, var3)
        assert var4 == 1
        var5 = '3AXl=cxV4w'
        var6 = module0.search(var5, var5)
        assert var6 == 1
        var7 = '=*'
        var8 = '|Y$I'
        var9 = module0.search(var7, var8)
        assert var9 == 0
        var10 = '3AXl=cxV4w'
        var11 = module0.search(var10, var10)
        assert var11 == 1
        var12 = 'AUl^K\nv\\_['
        var13 = 'JXKN'
        var14 = module0.search(var12, var13)
        assert var14 == 0
        var15 = 3997.73709
        var16 = False
        var17 = module0.search(var15, var16)
    except BaseException:
        pass


def test_case_33():
    try:
        var0 = '3AXl=cxV4w'
        var1 = module0.search(var0, var0)
        assert var1 == 1
        var2 = '=*'
        var3 = '|Y$I'
        var4 = module0.search(var2, var3)
        assert var4 == 0
        var5 = '3AXl=cxV4w'
        var6 = module0.search(var5, var5)
        assert var6 == 1
        var7 = 'AUl^K\nv\\_['
        var8 = 'JXKN'
        var9 = module0.search(var7, var8)
        assert var9 == 0
        var10 = '3AXl=cxV4w'
        var11 = module0.search(var10, var10)
        assert var11 == 1
        var12 = 'j$cm:"|3Ezi;Egn'
        var13 = 'lB>=nYZ'
        var14 = module0.search(var12, var13)
        assert var14 == 0
        var15 = '3AXl=cxV4w'
        var16 = module0.search(var15, var15)
        assert var16 == 1
        var17 = 'l`$GH"F_>zG|#M`'
        var18 = 'K'
        var19 = module0.search(var17, var18)
        assert var19 == 1
        var20 = 'KwfdN`hsMV}4s{4'
        var21 = -1821
        var22 = module0.search(var20, var21)
    except BaseException:
        pass


def test_case_34():
    try:
        var0 = 'B&dF/}?|;|'
        var1 = True
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_35():
    try:
        var0 = -1594
        var1 = False
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_36():
    try:
        var0 = 'B/|V'
        var1 = True
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_37():
    try:
        var0 = '3AXl=cxV4w'
        var1 = module0.search(var0, var0)
        assert var1 == 1
        var2 = 'j$cm:"|3Ezi;Egn'
        var3 = 'lB>=nYZ'
        var4 = module0.search(var2, var3)
        assert var4 == 0
        var5 = '3AXl=cxV4w'
        var6 = module0.search(var5, var5)
        assert var6 == 1
        var7 = False
        var8 = module0.search(var7, var7)
    except BaseException:
        pass


def test_case_38():
    try:
        var0 = '=*'
        var1 = '|Y$I'
        var2 = module0.search(var0, var1)
        assert var2 == 0
        var3 = '3AXl=cxV4w'
        var4 = module0.search(var3, var3)
        assert var4 == 1
        var5 = 'AUl^K\nv\\_['
        var6 = 'JXKN'
        var7 = module0.search(var5, var6)
        assert var7 == 0
        var8 = '3AXl=cxV4w'
        var9 = module0.search(var8, var8)
        assert var9 == 1
        var10 = 'l`$GH"F_>zG|#M`'
        var11 = 'K'
        var12 = module0.search(var10, var11)
        assert var12 == 1
        var13 = '3AXl=cxV4w'
        var14 = module0.search(var13, var13)
        assert var14 == 1
        var15 = 'j$cm:"|3Ezi;Egn'
        var16 = 'lB>=nYZ'
        var17 = module0.search(var15, var16)
        assert var17 == 0
        var18 = '3AXl=cxV4w'
        var19 = module0.search(var18, var18)
        assert var19 == 1
        var20 = True
        var21 = ';i!F|@v'
        var22 = module0.search(var20, var21)
    except BaseException:
        pass


def test_case_39():
    try:
        var0 = '3AXl=cxV4w'
        var1 = module0.search(var0, var0)
        assert var1 == 1
        var2 = '/hxn?&m'
        var3 = False
        var4 = module0.search(var2, var3)
    except BaseException:
        pass


def test_case_40():
    try:
        var0 = '=*'
        var1 = '|Y$I'
        var2 = module0.search(var0, var1)
        assert var2 == 0
        var3 = '3AXl=cxV4w'
        var4 = module0.search(var3, var3)
        assert var4 == 1
        var5 = '3AXl=cxV4w'
        var6 = module0.search(var5, var5)
        assert var6 == 1
        var7 = 'AUl^K\nv\\_['
        var8 = 'JXKN'
        var9 = module0.search(var7, var8)
        assert var9 == 0
        var10 = 1077.694651
        var11 = 'O\r`o=T41A]\x0c^\\Uj'
        var12 = module0.search(var10, var11)
    except BaseException:
        pass


def test_case_41():
    try:
        var0 = '=*'
        var1 = '|Y$I'
        var2 = module0.search(var0, var1)
        assert var2 == 0
        var3 = -1246
        var4 = True
        var5 = module0.search(var3, var4)
    except BaseException:
        pass


def test_case_42():
    try:
        var0 = '3AXl=cxV4w'
        var1 = module0.search(var0, var0)
        assert var1 == 1
        var2 = 'j$cm:"|3Ezi;Egn'
        var3 = 'lB>=nYZ'
        var4 = module0.search(var2, var3)
        assert var4 == 0
        var5 = '3AXl=cxV4w'
        var6 = module0.search(var5, var5)
        assert var6 == 1
        var7 = 'l`$GH"F_>zG|#M`'
        var8 = 'K'
        var9 = module0.search(var7, var8)
        assert var9 == 1
        var10 = '=*'
        var11 = '|Y$I'
        var12 = module0.search(var10, var11)
        assert var12 == 0
        var13 = '3AXl=cxV4w'
        var14 = module0.search(var13, var13)
        assert var14 == 1
        var15 = 'AUl^K\nv\\_['
        var16 = 'JXKN'
        var17 = module0.search(var15, var16)
        assert var17 == 0
        var18 = '=*'
        var19 = '|Y$I'
        var20 = module0.search(var18, var19)
        assert var20 == 0
        var21 = '\\A`I5b'
        var22 = '\x0c[Q<Y&.SA3vw'
        var23 = module0.search(var21, var22)
        assert var23 == 10
        var24 = '3AXl=cxV4w'
        var25 = module0.search(var24, var24)
        assert var25 == 1
        var26 = False
        var27 = module0.search(var21, var26)
    except BaseException:
        pass


def test_case_43():
    try:
        var0 = '3AXl=cxV4w'
        var1 = module0.search(var0, var0)
        assert var1 == 1
        var2 = 'j$cm:"|3Ezi;Egn'
        var3 = 'lB>=nYZ'
        var4 = module0.search(var2, var3)
        assert var4 == 0
        var5 = '3AXl=cxV4w'
        var6 = module0.search(var5, var5)
        assert var6 == 1
        var7 = 'l`$GH"F_>zG|#M`'
        var8 = 'K'
        var9 = module0.search(var7, var8)
        assert var9 == 1
        var10 = '=*'
        var11 = '|Y$I'
        var12 = module0.search(var10, var11)
        assert var12 == 0
        var13 = '3AXl=cxV4w'
        var14 = module0.search(var13, var13)
        assert var14 == 1
        var15 = '=*'
        var16 = '|Y$I'
        var17 = module0.search(var15, var16)
        assert var17 == 0
        var18 = '\\A`I5b'
        var19 = '\x0c[Q<Y&.SA3vw'
        var20 = module0.search(var18, var19)
        assert var20 == 10
        var21 = '3AXl=cxV4w'
        var22 = module0.search(var21, var21)
        assert var22 == 1
        var23 = 'AUl^K\nv\\_['
        var24 = 'JXKN'
        var25 = module0.search(var23, var24)
        assert var25 == 0
        var26 = 3093
        var27 = -1007.4221
        var28 = module0.search(var26, var27)
    except BaseException:
        pass


def test_case_44():
    try:
        var0 = '3AXl=cxV4w'
        var1 = module0.search(var0, var0)
        assert var1 == 1
        var2 = 'l`$GH"F_>zG|#M`'
        var3 = 'K'
        var4 = module0.search(var2, var3)
        assert var4 == 1
        var5 = '3AXl=cxV4w'
        var6 = module0.search(var5, var5)
        assert var6 == 1
        var7 = 'AUl^K\nv\\_['
        var8 = 'JXKN'
        var9 = module0.search(var7, var8)
        assert var9 == 0
        var10 = '3AXl=cxV4w'
        var11 = module0.search(var10, var10)
        assert var11 == 1
        var12 = 999.9
        var13 = '`sn\x0cZF\r'
        var14 = module0.search(var12, var13)
    except BaseException:
        pass


def test_case_45():
    try:
        var0 = '3AXl=cxV4w'
        var1 = module0.search(var0, var0)
        assert var1 == 1
        var2 = 'j$cm:"|3Ezi;Egn'
        var3 = 'lB>=nYZ'
        var4 = module0.search(var2, var3)
        assert var4 == 0
        var5 = '=*'
        var6 = '|Y$I'
        var7 = module0.search(var5, var6)
        assert var7 == 0
        var8 = '=*'
        var9 = '|Y$I'
        var10 = module0.search(var8, var9)
        assert var10 == 0
        var11 = '\\A`I5b'
        var12 = '\x0c[Q<Y&.SA3vw'
        var13 = module0.search(var11, var12)
        assert var13 == 10
        var14 = False
        var15 = module0.search(var14, var14)
    except BaseException:
        pass


def test_case_46():
    try:
        var0 = "'@U_ea,v"
        var1 = False
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_47():
    try:
        var0 = '3AXl=cxV4w'
        var1 = module0.search(var0, var0)
        assert var1 == 1
        var2 = 'AUl^K\nv\\_['
        var3 = 'JXKN'
        var4 = module0.search(var2, var3)
        assert var4 == 0
        var5 = True
        var6 = module0.search(var2, var5)
    except BaseException:
        pass


def test_case_48():
    try:
        var0 = '3AXl=cxV4w'
        var1 = module0.search(var0, var0)
        assert var1 == 1
        var2 = '=*'
        var3 = '|Y$I'
        var4 = module0.search(var2, var3)
        assert var4 == 0
        var5 = '3AXl=cxV4w'
        var6 = module0.search(var5, var5)
        assert var6 == 1
        var7 = 'l`$GH"F_>zG|#M`'
        var8 = 'K'
        var9 = module0.search(var7, var8)
        assert var9 == 1
        var10 = '=*'
        var11 = '|Y$I'
        var12 = module0.search(var10, var11)
        assert var12 == 0
        var13 = '\\A`I5b'
        var14 = '\x0c[Q<Y&.SA3vw'
        var15 = module0.search(var13, var14)
        assert var15 == 10
        var16 = None
        var17 = '.HGZ=]h'
        var18 = module0.search(var16, var17)
    except BaseException:
        pass


def test_case_49():
    try:
        var0 = '=*'
        var1 = '|Y$I'
        var2 = module0.search(var0, var1)
        assert var2 == 0
        var3 = '\\A`I5b'
        var4 = '\x0c[Q<Y&.SA3vw'
        var5 = module0.search(var3, var4)
        assert var5 == 10
        var6 = '3AXl=cxV4w'
        var7 = module0.search(var6, var6)
        assert var7 == 1
        var8 = 'j$cm:"|3Ezi;Egn'
        var9 = 'lB>=nYZ'
        var10 = module0.search(var8, var9)
        assert var10 == 0
        var11 = 'dq(SUh'
        var12 = -1921
        var13 = module0.search(var11, var12)
    except BaseException:
        pass


def test_case_50():
    try:
        var0 = 1465
        var1 = 1327.9
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_51():
    try:
        var0 = '3AXl=cxV4w'
        var1 = module0.search(var0, var0)
        assert var1 == 1
        var2 = 609
        var3 = module0.search(var2, var0)
    except BaseException:
        pass


def test_case_52():
    try:
        var0 = '=*'
        var1 = '|Y$I'
        var2 = module0.search(var0, var1)
        assert var2 == 0
        var3 = '\\A`I5b'
        var4 = '\x0c[Q<Y&.SA3vw'
        var5 = module0.search(var3, var4)
        assert var5 == 10
        var6 = '3AXl=cxV4w'
        var7 = module0.search(var6, var6)
        assert var7 == 1
        var8 = 'j$cm:"|3Ezi;Egn'
        var9 = 'lB>=nYZ'
        var10 = module0.search(var8, var9)
        assert var10 == 0
        var11 = '3AXl=cxV4w'
        var12 = module0.search(var11, var11)
        assert var12 == 1
        var13 = '3AXl=cxV4w'
        var14 = module0.search(var13, var13)
        assert var14 == 1
        var15 = 'AUl^K\nv\\_['
        var16 = 'JXKN'
        var17 = module0.search(var15, var16)
        assert var17 == 0
        var18 = '=*'
        var19 = '|Y$I'
        var20 = module0.search(var18, var19)
        assert var20 == 0
        var21 = -468.041961
        var22 = '>_cl;K!Pl5Rg*'
        var23 = module0.search(var21, var22)
    except BaseException:
        pass


def test_case_53():
    try:
        var0 = '3AXl=cxV4w'
        var1 = module0.search(var0, var0)
        assert var1 == 1
        var2 = 'AUl^K\nv\\_['
        var3 = 'JXKN'
        var4 = module0.search(var2, var3)
        assert var4 == 0
        var5 = '=*'
        var6 = '|Y$I'
        var7 = module0.search(var5, var6)
        assert var7 == 0
        var8 = '\\A`I5b'
        var9 = '\x0c[Q<Y&.SA3vw'
        var10 = module0.search(var8, var9)
        assert var10 == 10
        var11 = '3AXl=cxV4w'
        var12 = module0.search(var11, var11)
        assert var12 == 1
        var13 = 'j$cm:"|3Ezi;Egn'
        var14 = 'lB>=nYZ'
        var15 = module0.search(var13, var14)
        assert var15 == 0
        var16 = '3AXl=cxV4w'
        var17 = module0.search(var16, var16)
        assert var17 == 1
        var18 = '=*'
        var19 = '|Y$I'
        var20 = module0.search(var18, var19)
        assert var20 == 0
        var21 = '3AXl=cxV4w'
        var22 = module0.search(var21, var21)
        assert var22 == 1
        var23 = 'l`$GH"F_>zG|#M`'
        var24 = 'K'
        var25 = module0.search(var23, var24)
        assert var25 == 1
        var26 = -1757.630111
        var27 = 1379
        var28 = module0.search(var26, var27)
    except BaseException:
        pass


def test_case_54():
    try:
        var0 = '3AXl=cxV4w'
        var1 = module0.search(var0, var0)
        assert var1 == 1
        var2 = '=*'
        var3 = '|Y$I'
        var4 = module0.search(var2, var3)
        assert var4 == 0
        var5 = '\\A`I5b'
        var6 = '\x0c[Q<Y&.SA3vw'
        var7 = module0.search(var5, var6)
        assert var7 == 10
        var8 = '=*'
        var9 = '|Y$I'
        var10 = module0.search(var8, var9)
        assert var10 == 0
        var11 = '3AXl=cxV4w'
        var12 = module0.search(var11, var11)
        assert var12 == 1
        var13 = 'j$cm:"|3Ezi;Egn'
        var14 = 'lB>=nYZ'
        var15 = module0.search(var13, var14)
        assert var15 == 0
        var16 = '3AXl=cxV4w'
        var17 = module0.search(var16, var16)
        assert var17 == 1
        var18 = 'l`$GH"F_>zG|#M`'
        var19 = 'K'
        var20 = module0.search(var18, var19)
        assert var20 == 1
        var21 = '3AXl=cxV4w'
        var22 = module0.search(var21, var21)
        assert var22 == 1
        var23 = 'AUl^K\nv\\_['
        var24 = 'JXKN'
        var25 = module0.search(var23, var24)
        assert var25 == 0
        var26 = True
        var27 = 'P?0im%YQf7z(Z~p*\\A\r]'
        var28 = module0.search(var26, var27)
    except BaseException:
        pass


def test_case_55():
    try:
        var0 = '3AXl=cxV4w'
        var1 = module0.search(var0, var0)
        assert var1 == 1
        var2 = 'AUl^K\nv\\_['
        var3 = 'JXKN'
        var4 = module0.search(var2, var3)
        assert var4 == 0
        var5 = '3AXl=cxV4w'
        var6 = module0.search(var5, var5)
        assert var6 == 1
        var7 = 74
        var8 = module0.search(var5, var7)
    except BaseException:
        pass


def test_case_56():
    try:
        var0 = '=*'
        var1 = '|Y$I'
        var2 = module0.search(var0, var1)
        assert var2 == 0
        var3 = '3AXl=cxV4w'
        var4 = module0.search(var3, var3)
        assert var4 == 1
        var5 = 'AUl^K\nv\\_['
        var6 = 'JXKN'
        var7 = module0.search(var5, var6)
        assert var7 == 0
        var8 = '3AXl=cxV4w'
        var9 = module0.search(var8, var8)
        assert var9 == 1
        var10 = 'l`$GH"F_>zG|#M`'
        var11 = 'K'
        var12 = module0.search(var10, var11)
        assert var12 == 1
        var13 = '=*'
        var14 = '|Y$I'
        var15 = module0.search(var13, var14)
        assert var15 == 0
        var16 = '\\A`I5b'
        var17 = '\x0c[Q<Y&.SA3vw'
        var18 = module0.search(var16, var17)
        assert var18 == 10
        var19 = 'iH 39oD%N\x0b@'
        var20 = -2663
        var21 = module0.search(var19, var20)
    except BaseException:
        pass


def test_case_57():
    try:
        var0 = '=*'
        var1 = '|Y$I'
        var2 = module0.search(var0, var1)
        assert var2 == 0
        var3 = '=*'
        var4 = '|Y$I'
        var5 = module0.search(var3, var4)
        assert var5 == 0
        var6 = '\\A`I5b'
        var7 = '\x0c[Q<Y&.SA3vw'
        var8 = module0.search(var6, var7)
        assert var8 == 10
        var9 = '3AXl=cxV4w'
        var10 = module0.search(var9, var9)
        assert var10 == 1
        var11 = 'l`$GH"F_>zG|#M`'
        var12 = 'K'
        var13 = module0.search(var11, var12)
        assert var13 == 1
        var14 = '3AXl=cxV4w'
        var15 = module0.search(var14, var14)
        assert var15 == 1
        var16 = '3AXl=cxV4w'
        var17 = module0.search(var16, var16)
        assert var17 == 1
        var18 = 'AUl^K\nv\\_['
        var19 = 'JXKN'
        var20 = module0.search(var18, var19)
        assert var20 == 0
        var21 = '3AXl=cxV4w'
        var22 = module0.search(var21, var21)
        assert var22 == 1
        var23 = 'j$cm:"|3Ezi;Egn'
        var24 = 'lB>=nYZ'
        var25 = module0.search(var23, var24)
        assert var25 == 0
        var26 = True
        var27 = module0.search(var26, var26)
    except BaseException:
        pass


def test_case_58():
    try:
        var0 = '3AXl=cxV4w'
        var1 = module0.search(var0, var0)
        assert var1 == 1
        var2 = 'AUl^K\nv\\_['
        var3 = 'JXKN'
        var4 = module0.search(var2, var3)
        assert var4 == 0
        var5 = '=*'
        var6 = '|Y$I'
        var7 = module0.search(var5, var6)
        assert var7 == 0
        var8 = '3AXl=cxV4w'
        var9 = module0.search(var8, var8)
        assert var9 == 1
        var10 = '=*'
        var11 = '|Y$I'
        var12 = module0.search(var10, var11)
        assert var12 == 0
        var13 = '\\A`I5b'
        var14 = '\x0c[Q<Y&.SA3vw'
        var15 = module0.search(var13, var14)
        assert var15 == 10
        var16 = -2118
        var17 = 'Vl\x0bc.P72'
        var18 = module0.search(var16, var17)
    except BaseException:
        pass


def test_case_59():
    try:
        var0 = '3AXl=cxV4w'
        var1 = module0.search(var0, var0)
        assert var1 == 1
        var2 = 'j$cm:"|3Ezi;Egn'
        var3 = 'lB>=nYZ'
        var4 = module0.search(var2, var3)
        assert var4 == 0
        var5 = '=*'
        var6 = '|Y$I'
        var7 = module0.search(var5, var6)
        assert var7 == 0
        var8 = '\\A`I5b'
        var9 = '\x0c[Q<Y&.SA3vw'
        var10 = module0.search(var8, var9)
        assert var10 == 10
        var11 = -1441.98927
        var12 = module0.search(var11, var5)
    except BaseException:
        pass


def test_case_60():
    try:
        var0 = '3AXl=cxV4w'
        var1 = module0.search(var0, var0)
        assert var1 == 1
        var2 = 'AUl^K\nv\\_['
        var3 = 'JXKN'
        var4 = module0.search(var2, var3)
        assert var4 == 0
        var5 = '3AXl=cxV4w'
        var6 = module0.search(var5, var5)
        assert var6 == 1
        var7 = 'l`$GH"F_>zG|#M`'
        var8 = 'K'
        var9 = module0.search(var7, var8)
        assert var9 == 1
        var10 = '=*'
        var11 = '|Y$I'
        var12 = module0.search(var10, var11)
        assert var12 == 0
        var13 = '3AXl=cxV4w'
        var14 = module0.search(var13, var13)
        assert var14 == 1
        var15 = 'j$cm:"|3Ezi;Egn'
        var16 = 'lB>=nYZ'
        var17 = module0.search(var15, var16)
        assert var17 == 0
        var18 = '3AXl=cxV4w'
        var19 = module0.search(var18, var18)
        assert var19 == 1
        var20 = 'Y*Yy'
        var21 = -2932
        var22 = module0.search(var20, var21)
    except BaseException:
        pass
