# Automatically generated by Pynguin.
import caso_covertura_007 as module0


def test_case_0():
    try:
        var0 = None
        var1 = '?s.;Hb=E\rBMN[PGe5}'
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_1():
    try:
        var0 = -248
        var1 = '_-AD\x0bP"=~x#I#'
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_2():
    try:
        var0 = -2249.934648
        var1 = '0158-\\rj]`'
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_3():
    try:
        var0 = None
        var1 = 'TFWt/rZ%Oxl0qt\x0c/'
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_4():
    try:
        var0 = None
        var1 = -3170
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_5():
    try:
        var0 = 'z`('
        var1 = ';q28/5rz_3'
        var2 = module0.search(var0, var1)
        assert var2 == 10
        var3 = False
        var4 = -2225.1
        var5 = module0.search(var3, var4)
    except BaseException:
        pass


def test_case_6():
    try:
        var0 = 'z`('
        var1 = ';q28/5rz_3'
        var2 = module0.search(var0, var1)
        assert var2 == 10
        var3 = -2396.4476
        var4 = '\njKks&&#m=^Q/0\t4RT'
        var5 = module0.search(var3, var4)
    except BaseException:
        pass


def test_case_7():
    try:
        var0 = '!\x0c lEI'
        var1 = False
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_8():
    try:
        var0 = ''
        var1 = False
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_9():
    try:
        var0 = -707
        var1 = ''
        var2 = module0.search(var0, var1)
        assert var2 == 0
        var3 = 't!2y\\sZH>BwL='
        var4 = False
        var5 = module0.search(var3, var4)
    except BaseException:
        pass


def test_case_10():
    try:
        var0 = 'z`('
        var1 = ';q28/5rz_3'
        var2 = module0.search(var0, var1)
        assert var2 == 10
        var3 = '/(]&L"-5"oo.'
        var4 = -3319
        var5 = module0.search(var3, var4)
    except BaseException:
        pass


def test_case_11():
    try:
        var0 = -707
        var1 = ''
        var2 = module0.search(var0, var1)
        assert var2 == 0
        var3 = 'z`('
        var4 = ';q28/5rz_3'
        var5 = module0.search(var3, var4)
        assert var5 == 10
        var6 = "i@'8oA46W[ \r=La"
        var7 = True
        var8 = module0.search(var6, var7)
    except BaseException:
        pass


def test_case_12():
    try:
        var0 = None
        var1 = True
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_13():
    try:
        var0 = 'z`('
        var1 = ';q28/5rz_3'
        var2 = module0.search(var0, var1)
        assert var2 == 10
        var3 = -1133.6851
        var4 = True
        var5 = module0.search(var3, var4)
    except BaseException:
        pass


def test_case_14():
    try:
        var0 = 'z`('
        var1 = ';q28/5rz_3'
        var2 = module0.search(var0, var1)
        assert var2 == 10
        var3 = '.WbjOT@91_114Xy'
        var4 = None
        var5 = module0.search(var3, var4)
    except BaseException:
        pass


def test_case_15():
    try:
        var0 = 'z`('
        var1 = ';q28/5rz_3'
        var2 = module0.search(var0, var1)
        assert var2 == 10
        var3 = -3123.7402
        var4 = False
        var5 = module0.search(var3, var4)
    except BaseException:
        pass


def test_case_16():
    try:
        var0 = 'z`('
        var1 = ';q28/5rz_3'
        var2 = module0.search(var0, var1)
        assert var2 == 10
        var3 = -707
        var4 = ''
        var5 = module0.search(var3, var4)
        assert var5 == 0
        var6 = '_v\x0co(3T+\r\rZ:'
        var7 = False
        var8 = module0.search(var6, var7)
    except BaseException:
        pass


def test_case_17():
    try:
        var0 = -707
        var1 = ''
        var2 = module0.search(var0, var1)
        assert var2 == 0
        var3 = 'z`('
        var4 = ';q28/5rz_3'
        var5 = module0.search(var3, var4)
        assert var5 == 10
        var6 = 3717.6
        var7 = True
        var8 = module0.search(var6, var7)
    except BaseException:
        pass


def test_case_18():
    try:
        var0 = " ='n#\\5x1o\n:!;/@"
        var1 = -936
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_19():
    try:
        var0 = 'z`('
        var1 = ';q28/5rz_3'
        var2 = module0.search(var0, var1)
        assert var2 == 10
        var3 = -707
        var4 = ''
        var5 = module0.search(var3, var4)
        assert var5 == 0
        var6 = False
        var7 = 'Dg/1mH>S)_5}'
        var8 = module0.search(var6, var7)
    except BaseException:
        pass


def test_case_20():
    try:
        var0 = 'z`('
        var1 = ';q28/5rz_3'
        var2 = module0.search(var0, var1)
        assert var2 == 10
        var3 = '=V(1KEF61xp%ouK(_qb'
        var4 = False
        var5 = module0.search(var3, var4)
    except BaseException:
        pass


def test_case_21():
    try:
        var0 = 'J\x0b;['
        var1 = True
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_22():
    try:
        var0 = -707
        var1 = ''
        var2 = module0.search(var0, var1)
        assert var2 == 0
        var3 = 'z`('
        var4 = ';q28/5rz_3'
        var5 = module0.search(var3, var4)
        assert var5 == 10
        var6 = -1321
        var7 = False
        var8 = module0.search(var6, var7)
    except BaseException:
        pass


def test_case_23():
    try:
        var0 = False
        var1 = '\rVxRQ\x0c\nd4x'
        var2 = module0.search(var0, var1)
    except BaseException:
        pass


def test_case_24():
    try:
        var0 = -707
        var1 = ''
        var2 = module0.search(var0, var1)
        assert var2 == 0
        var3 = 'z`('
        var4 = ';q28/5rz_3'
        var5 = module0.search(var3, var4)
        assert var5 == 10
        var6 = ' O#:o"N#=H#NpPZ@8"'
        var7 = False
        var8 = module0.search(var6, var7)
    except BaseException:
        pass


def test_case_25():
    try:
        var0 = -707
        var1 = ''
        var2 = module0.search(var0, var1)
        assert var2 == 0
        var3 = -141
        var4 = 268.9
        var5 = module0.search(var3, var4)
    except BaseException:
        pass


def test_case_26():
    try:
        var0 = -707
        var1 = ''
        var2 = module0.search(var0, var1)
        assert var2 == 0
        var3 = 'z`('
        var4 = ';q28/5rz_3'
        var5 = module0.search(var3, var4)
        assert var5 == 10
        var6 = None
        var7 = True
        var8 = module0.search(var6, var7)
    except BaseException:
        pass


def test_case_27():
    try:
        var0 = 'z`('
        var1 = ';q28/5rz_3'
        var2 = module0.search(var0, var1)
        assert var2 == 10
        var3 = True
        var4 = module0.search(var3, var1)
    except BaseException:
        pass


def test_case_28():
    try:
        var0 = 'z`('
        var1 = ';q28/5rz_3'
        var2 = module0.search(var0, var1)
        assert var2 == 10
        var3 = '><X|^[~I$`fE:8wX'
        var4 = None
        var5 = module0.search(var3, var4)
    except BaseException:
        pass


def test_case_29():
    try:
        var0 = 'z`('
        var1 = ';q28/5rz_3'
        var2 = module0.search(var0, var1)
        assert var2 == 10
        var3 = -707
        var4 = ''
        var5 = module0.search(var3, var4)
        assert var5 == 0
        var6 = -913.2
        var7 = True
        var8 = module0.search(var6, var7)
    except BaseException:
        pass


def test_case_30():
    try:
        var0 = -707
        var1 = ''
        var2 = module0.search(var0, var1)
        assert var2 == 0
        var3 = 'z`('
        var4 = ';q28/5rz_3'
        var5 = module0.search(var3, var4)
        assert var5 == 10
        var6 = 'sW-J4m'
        var7 = module0.search(var6, var0)
    except BaseException:
        pass


def test_case_31():
    try:
        var0 = -707
        var1 = ''
        var2 = module0.search(var0, var1)
        assert var2 == 0
        var3 = "xyss[M8wPhFcOx'E7"
        var4 = True
        var5 = module0.search(var3, var4)
    except BaseException:
        pass


def test_case_32():
    try:
        var0 = -569.5928
        var1 = -729
        var2 = module0.search(var0, var1)
    except BaseException:
        pass
