# Automatically generated by Pynguin.
import caso_covertura_190 as module0


def test_case_0():
    try:
        var0 = 262.8
        var1 = module0.remove_extras(var0)
    except BaseException:
        pass


def test_case_1():
    try:
        var0 = 809.0
        var1 = module0.remove_extras(var0)
    except BaseException:
        pass


def test_case_2():
    try:
        var0 = 722.931
        var1 = module0.remove_extras(var0)
    except BaseException:
        pass


def test_case_3():
    try:
        var0 = -986
        var1 = module0.remove_extras(var0)
    except BaseException:
        pass


def test_case_4():
    try:
        var0 = "9$<$(/_cZgeB'_i"
        var1 = module0.remove_extras(var0)
        assert var1 is not None
        var2 = None
        var3 = module0.remove_extras(var2)
    except BaseException:
        pass


def test_case_5():
    try:
        var0 = "9$<$(/_cZgeB'_i"
        var1 = module0.remove_extras(var0)
        assert var1 is not None
        var2 = True
        var3 = module0.remove_extras(var2)
    except BaseException:
        pass


def test_case_6():
    try:
        var0 = "9$<$(/_cZgeB'_i"
        var1 = module0.remove_extras(var0)
        assert var1 is not None
        var2 = 825.90599
        var3 = module0.remove_extras(var2)
    except BaseException:
        pass


def test_case_7():
    try:
        var0 = "9$<$(/_cZgeB'_i"
        var1 = module0.remove_extras(var0)
        assert var1 is not None
        var2 = 2504
        var3 = module0.remove_extras(var2)
    except BaseException:
        pass


def test_case_8():
    try:
        var0 = False
        var1 = module0.remove_extras(var0)
    except BaseException:
        pass


def test_case_9():
    try:
        var0 = "9$<$(/_cZgeB'_i"
        var1 = module0.remove_extras(var0)
        assert var1 is not None
        var2 = 2049
        var3 = module0.remove_extras(var2)
    except BaseException:
        pass


def test_case_10():
    try:
        var0 = "9$<$(/_cZgeB'_i"
        var1 = module0.remove_extras(var0)
        assert var1 is not None
        var2 = 4230.346
        var3 = module0.remove_extras(var2)
    except BaseException:
        pass


def test_case_11():
    try:
        var0 = "9$<$(/_cZgeB'_i"
        var1 = module0.remove_extras(var0)
        assert var1 is not None
        var2 = False
        var3 = module0.remove_extras(var2)
    except BaseException:
        pass


def test_case_12():
    try:
        var0 = "9$<$(/_cZgeB'_i"
        var1 = module0.remove_extras(var0)
        assert var1 is not None
        var2 = 'Bn?Ysm`<;\\G "si30jE;'
        var3 = module0.remove_extras(var2)
        assert var3 is not None
        var4 = True
        var5 = module0.remove_extras(var4)
    except BaseException:
        pass
